#' compiled_data_json: Generates a json file with descriptions of demographic and dexa variables 
#'
#' This function generates a json file for the TSV file exported by code/compile_databases.R
#' 
#' @return A string with data stored in JSON format containing meta-data for the TSV file exported by code/compile_databases.R

compiled_data_json <- function() {
  
  data_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Demographic and Dual Energy X-Ray Absorptiometry (DEXA) metrics of body composition (Hologic Inc., Waltham, MA) from studies Food and Brain (5R01DK110060; ages 7-8y; data collection 2017-2022) and REACH (5R01DK126050; ages 7-9y; data collection 2022-ongoing)',
      Reference = 'Advanced Body Composition Reporting and Interpretation, A Technical Discussion. Thomas L. Kelly, Hologic, Inc.',
      TermURL = 'https://hologiced.com/library/advanced-body-composition-reporting-and-interpretation-a-technical-discussion/'),
    
    CEBL_ID = list( Description = 'Child Eating Behavior Lab (CEBL) ID. This is a participant identifier that is consistent across studies in the CEBL'),
    study_id = list( Description = 'Study-specific participant ID'),
    dxa_date = list( Description = 'Date of dxa scan'),
    mri_date = list( Description = 'Date of MRI'),
    
    # demo variables
    ethnicity = list( Description = 'Parent-reported child ethnicicy'),
    race = list( Description = 'Parent-reported child race'),
    income = list( Description = 'Parent-reported family income. Parent\'s were asked: "Including ALL sources (such as social security income, child support payments, government assistance, dividends from investments, etc.) what was your household\'s combined yearly income last year BEFORE taxes?"',
                   Levels = list ('0' = 'Less than $20,000',
                                  '1' = '$21,000 - $35,000',
                                  '2' = '$36,000 - $50,000',
                                  '3' = '$51,000 - $75,000',
                                  '4' = '$76,000 - $100,000',
                                  '5' = '$100,000 +')),
    sex = list( Description = 'Parent-reported child sex'),
    age_yr = list( Description = 'child age on dxa_date. Calculated using child DOB (not shared) and dxa_date',
                   Unit = "years"),
    bmi = list( Description = 'Child body mass index. Derived from average of 2 height and weight measures on date of dxa scan',
                      Unit = "kg/(m^2)",
                      Derivative = TRUE),
    bmi_percentile = list( Description = 'Child BMI-for-age percentile based on the LMS Parameters for the Centers for Disease Control and Prevention 2000 Growth Charts. Calculated in R using childsds package',
                        Derivative = TRUE),
    bmi_z = list( Description = 'Child BMI-for-age z-score baesd on the LMS Parameters for the Centers for Disease Control and Prevention 2000 Growth Charts. Calculated in R using childsds package',
                        Derivative = TRUE),
    
    # dexa variables
    dxa_l_arm_area = list( Description = 'L Arm Area',
                           Unit = "cm^2"),
    dxa_l_arm_bmc = list( Description = 'L Arm bone mineral content (BMC)',
                          Unit = "g"),
    dxa_l_arm_bmd = list( Description = 'L Arm bone mineral density (BMD)',
                          Unit = "g/cm^2"),
    dxa_r_arm_area = list( Description = 'R Arm Area',
                           Unit = "cm^2"),
    dxa_r_arm_bmc = list( Description = 'R Arm bone mineral content (BMC)',
                          Unit = "g"),
    dxa_r_arm_bmd = list( Description = 'R Arm bone mineral density (BMD)',
                          Unit = "g/cm^2"),
    
    dxa_l_ribs_area = list( Description = 'L Ribs Area',
                            Unit = "cm^2"),
    dxa_l_ribs_bmc = list( Description = 'L Ribs bone mineral content (BMC)',
                           Unit = "g"),
    dxa_l_ribs_bmd = list( Description = 'L Ribs bone mineral density (BMD)',
                           Unit = "g/cm^2"),
    dxa_r_ribs_area = list( Description = 'R Ribs Area',
                            Unit = "cm^2"),
    dxa_r_ribs_bmc = list( Description = 'R Ribs bone mineral content (BMC)',
                           Unit = "g"),
    dxa_r_ribs_bmd = list( Description = 'R Ribs bone mineral density (BMD)',
                           Unit = "g/cm^2"),
    
    dxa_t_spine_area = list( Description = 'T Spine Area',
                             Unit = "cm^2"),
    dxa_t_spine_bmc = list( Description = 'T Spine bone mineral content (BMC)',
                            Unit = "g"),
    dxa_t_spine_bmd = list( Description = 'T Spine bone mineral density (BMD)',
                            Unit = "g/cm^2"),
    
    dxa_l_spine_area = list( Description = 'L Spine Area',
                             Unit = "cm^2"),
    dxa_l_spine_bmc = list( Description = 'L Spine bone mineral content (BMC)',
                            Unit = "g"),
    dxa_l_spine_bmd = list( Description = 'L Spine bone mineral density (BMD)',
                            Unit = "g/cm^2"),
    
    dxa_pelvis_area = list( Description = 'Pelvis Area',
                            Unit = "cm^2"),
    dxa_pelvis_bmc = list( Description = 'Pelvis bone mineral content (BMC)',
                           Unit = "g"),
    dxa_pelvis_bmd = list( Description = 'Pelvis bone mineral density (BMD)',
                           Unit = "g/cm^2"),
    
    dxa_l_leg_area = list( Description = 'L Leg Area',
                           Unit = "cm^2"),
    dxa_l_leg_bmc = list( Description = 'L Leg bone mineral content (BMC)',
                          Unit = "g"),
    dxa_l_leg_bmd = list( Description = 'L Leg bone mineral density (BMD)',
                          Unit = "g/cm^2"),
    dxa_r_leg_area = list( Description = 'R Leg Area',
                           Unit = "cm^2"),
    dxa_r_leg_bmc = list( Description = 'R Leg bone mineral content (BMC)',
                          Unit = "g"),
    dxa_r_leg_bmd = list( Description = 'R Leg bone mineral density (BMD)',
                          Unit = "g/cm^2"),
    
    dxa_subtotal_area = list( Description = 'Subtotal Area',
                              Unit = "cm^2"),
    dxa_subtotal_bmc = list( Description = 'Subtotal bone mineral content (BMC)',
                             Unit = "g"),
    dxa_subtotal_bmd = list( Description = 'Subtotal bone mineral density (BMD)',
                             Unit = "g/cm^2"),
    dxa_subtotal_zscore = list( Description = 'Subtotal Z Score'),
    
    dxa_head_area = list( Description = 'Head Area',
                          Unit = "cm^2"),
    dxa_head_bmc = list( Description = 'Head bone mineral content (BMC)',
                         Unit = "g"),
    dxa_head_bmd = list( Description = 'Head bone mineral density (BMD)',
                         Unit = "g/cm^2"),
    
    dxa_total_area = list( Description = 'Total Area',
                           Unit = "cm^2"),
    dxa_total_bmc = list( Description = 'Total bone mineral content (BMC)',
                          Unit = "g"),
    dxa_total_bmd = list( Description = 'Total bone mineral density (BMD)',
                          Unit = "g/cm^2"),
    dxa_total_zscore = list( Description = 'Total Z Score'),
    
    dxa_l_arm_fat_mass = list( Description = 'L Arm Fat Mass',
                               Unit = "g"),
    dxa_l_arm_lean_bmc_comb = list( Description = 'L Arm Lean And bone mineral content (BMC) Combined',
                                    Unit = "g"),
    dxa_l_arm_total_mass = list( Description = 'L Arm Total Mass',
                                 Unit = "g"),
    dxa_l_arm_perc_fat = list( Description = 'dxa_l_arm_perc_fat'),
    dxa_l_arm_perc_fat_ptile = list( Description = 'L Arm Percent Fat aged matched percentile. Percentiles are based on NHANES data reported by Kelly et al. 2009 and only avaiable for children aged 8+',
                                     Reference = 'Kelly TL, Wilson KE, Heymsfield SB (2009) Dual Energy X-Ray Absorptiometry Body Composition Reference Values from NHANES. PLOS ONE 4(9): e7038.'),
    dxa_r_arm_fat_mass = list( Description = 'R Arm Fat Mass',
                               Unit = "g"),
    dxa_r_arm_lean_bmc_comb = list( Description = 'R Arm Lean and bone mineral content (BMC) Combined',
                                    Unit = "g"),
    dxa_r_arm_total_mass = list( Description = 'R Arm Total Mass',
                                 Unit = "g"),
    dxa_r_arm_perc_fat = list( Description = 'R Arm Percent Fat'),
    dxa_r_arm_perc_fat_ptile = list( Description = 'R Arm Percent Fat aged matched percentile. Percentiles are based on NHANES data reported by Kelly et al. 2009 and only avaiable for children aged 8+',
                                     Reference = 'Kelly TL, Wilson KE, Heymsfield SB (2009) Dual Energy X-Ray Absorptiometry Body Composition Reference Values from NHANES. PLOS ONE 4(9): e7038.'),
    
    dxa_trunk_fat_mass = list( Description = 'Trunk Fat Mass',
                               Unit = "g"),
    dxa_trunk_lean_bmc_comb = list( Description = 'Trunk Lean and bone mineral content (BMC) Combined',
                                    Unit = "g"),
    dxa_trunk_total_mass = list( Description = 'Trunk Total Mass',
                                 Unit = "g"),
    dxa_trunk_perc_fat = list( Description = 'Trunk Percent Fat'),
    dxa_trunk_perc_fat_ptile = list( Description = 'Trunk Percent Fat aged matched percentile. Percentiles are based on NHANES data reported by Kelly et al. 2009 and only avaiable for children aged 8+',
                                     Reference = 'Kelly TL, Wilson KE, Heymsfield SB (2009) Dual Energy X-Ray Absorptiometry Body Composition Reference Values from NHANES. PLOS ONE 4(9): e7038.'),
    
    dxa_l_leg_fat_mass = list( Description = 'L Leg Fat Mass',
                               Unit = "g"),
    dxa_l_leg_lean_bmc_comb = list( Description = 'L Leg Lean And bone mineral content (BMC) Combined',
                                    Unit = "g"),
    dxa_l_leg_total_mass = list( Description = 'L Leg Total Mass',
                                 Unit = "g"),
    dxa_l_leg_perc_fat = list( Description = 'L Leg Percent Fat'),
    dxa_l_leg_perc_fat_ptile = list( Description = 'L Leg Percent Fat aged matched percentile. Percentiles are based on NHANES data reported by Kelly et al. 2009 and only avaiable for children aged 8+',
                                     Reference = 'Kelly TL, Wilson KE, Heymsfield SB (2009) Dual Energy X-Ray Absorptiometry Body Composition Reference Values from NHANES. PLOS ONE 4(9): e7038.'),
    dxa_r_leg_fat_mass = list( Description = 'R Leg Fat Mass',
                               Unit = "g"),
    dxa_r_leg_lean_bmc_comb = list( Description = 'R Leg Lean And bone mineral content (BMC) Combined',
                                    Unit = "g"),
    dxa_r_leg_total_mass = list( Description = 'R Leg Total Mass',
                                 Unit = "g"),
    dxa_r_leg_perc_fat = list( Description = 'R Leg Percent Fat'),
    dxa_r_leg_perc_fat_ptile = list( Description = 'R Leg Percent Fat aged matched percentile. Percentiles are based on NHANES data reported by Kelly et al. 2009 and only avaiable for children aged 8+',
                                     Reference = 'Kelly TL, Wilson KE, Heymsfield SB (2009) Dual Energy X-Ray Absorptiometry Body Composition Reference Values from NHANES. PLOS ONE 4(9): e7038.'),
    
    dxa_subtotal_fat_mass = list( Description = 'Subtotal Fat Mass',
                                  Unit = "g"),
    dxa_subtotal_lean_bmc_comb = list( Description = 'Subtotal Lean and bone mineral content (BMC) Combined',
                                       Unit = "g"),
    dxa_subtotal_total_mass = list( Description = 'Subtotal Total Mass',
                                    Unit = "g"),
    dxa_subtotal_perc_fat = list( Description = 'Subtotal Percent Fat'),
    dxa_subtotal_perc_fat_ptile = list( Description = 'Subtotal Percent Fat aged matched percentile. Percentiles are based on NHANES data reported by Kelly et al. 2009 and only avaiable for children aged 8+',
                                        Reference = 'Kelly TL, Wilson KE, Heymsfield SB (2009) Dual Energy X-Ray Absorptiometry Body Composition Reference Values from NHANES. PLOS ONE 4(9): e7038.'),
    
    dxa_head_fat_mass = list( Description = 'Head Fat Mass',
                              Unit = "g"),
    dxa_head_lean_bmc_comb = list( Description = 'Head Lean and bone mineral content (BMC) Combined',
                                   Unit = "g"),
    dxa_head_total_mass = list( Description = 'Head Total Mass',
                                Unit = "g"),
    dxa_head_perc_fat = list( Description = 'Head Percent Fat'),
    
    dxa_total_fat_mass = list( Description = 'Total Fat Mass',
                               Unit = "g"),
    dxa_total_lean_bmc_comb = list( Description = 'Total Lean and bone mineral content (BMC) Combined'),
    dxa_total_total_mass = list( Description = 'Total Total Mass',
                                 Unit = "g"),
    dxa_total_perc_fat = list( Description = 'Total Percent Fat'),
    dxa_total_perc_fat_ptile = list( Description = 'Total Percent Fat aged matched percentile. Percentiles are based on NHANES data reported by Kelly et al. 2009 and only avaiable for children aged 8+',
                                     Reference = 'Kelly TL, Wilson KE, Heymsfield SB (2009) Dual Energy X-Ray Absorptiometry Body Composition Reference Values from NHANES. PLOS ONE 4(9): e7038.'),
    
    dxa_android_fat_mass = list( Description = 'Android Fat Mass',
                                 Unit = "g"),
    dxa_android_lean_bmc_comb = list( Description = 'Android Lean And bone mineral content (BMC) Combined',
                                      Unit = "g"),
    dxa_android_total_mass = list( Description = 'Android Total Mass',
                                   Unit = "g"),
    dxa_android_perc_fat = list( Description = 'Android Percent Fat'),
    
    dxa_gynoid_fat_mass = list( Description = 'Gynoid Fat Mass',
                                Unit = "g"),
    dxa_gynoid_lean_bmc_comb = list( Description = 'Gynoid Lean and bone mineral content (BMC) Combined',
                                     Unit = "g"),
    dxa_gynoid_total_mass = list( Description = 'Gynoid Total Mass',
                                  Unit = "g"),
    dxa_gynoid_perc_fat = list( Description = 'Gynoid Percent Fat'),
    
    dxa_fatmass_height_ratio = list( Description = 'Fat Mass Over Height Result',
                                     Unit = "kg/m^2"),
    dxa_fatmass_height_ratio_ptile = list( Description = 'Fat Mass Over Height aged matched percentile. Percentiles are based on NHANES data reported by Kelly et al. 2009 and only avaiable for children aged 8+',
                                           Reference = 'Kelly TL, Wilson KE, Heymsfield SB (2009) Dual Energy X-Ray Absorptiometry Body Composition Reference Values from NHANES. PLOS ONE 4(9): e7038.'),
    
    dxa_android_gynoid_ratio = list( Description = 'Android Over Gynoid Ratio Result'),
    
    dxa_percfat_trunk_legs_ratio = list( Description = 'Percent Fat Trunk Over Percent Fat Legs Result'),
    dxa_percfat_trunk_legs_ratio_ptile = list( Description = 'Percent Fat Trunk Over Percent Fat Legs aged matched percentile. Percentiles are based on NHANES data reported by Kelly et al. 2009 and only avaiable for children aged 8+',
                                               Reference = 'Kelly TL, Wilson KE, Heymsfield SB (2009) Dual Energy X-Ray Absorptiometry Body Composition Reference Values from NHANES. PLOS ONE 4(9): e7038.'),
    
    dxa_fatmass_trunk_limb_ratio = list( Description = 'Trunk Over Limb Fat Mass Ratio Result'),
    dxa_fatmass_trunk_limb_ratio_ptile = list( Description = 'Trunk Over Limb Fat Mass Ratio aged matched percentile. Percentiles are based on NHANES data reported by Kelly et al. 2009 and only avaiable for children aged 8+',
                                               Reference = 'Kelly TL, Wilson KE, Heymsfield SB (2009) Dual Energy X-Ray Absorptiometry Body Composition Reference Values from NHANES. PLOS ONE 4(9): e7038.'),
    
    dxa_est_vat_mass = list( Description = 'Est viseral adipose tissue (VAT) Mass',
                             Unit = "g"),
    dxa_est_vat_volume = list( Description = 'Est viseral adipose tissue (VAT) Volume',
                               Unit = "cm^3"),
    dxa_est_vat_area = list( Description = 'Est viseral adipose tissue (VAT) Area',
                             Unit = "cm^2"),
    
    dxa_lean_height_ratio = list( Description = 'Lean Over Height Result',
                                  Unit = "kg/m^2"),
    dxa_lean_height_ratio_ptile = list( Description = 'Lean Over Height aged matched percentile. Percentiles are based on NHANES data reported by Kelly et al. 2009 and only avaiable for children aged 8+',
                                        Reference = 'Kelly TL, Wilson KE, Heymsfield SB (2009) Dual Energy X-Ray Absorptiometry Body Composition Reference Values from NHANES. PLOS ONE 4(9): e7038.'),
    
    dxa_appen_lean_height = list( Description = 'Appen Lean Over Height Result',
                                  Unit = "kg/m^2"),
    dxa_appen_lean_height_ptile = list( Description = 'Appen Lean Over Height aged matched percentile. Percentiles are based on NHANES data reported by Kelly et al. 2009 and only avaiable for children aged 8+',
                                        Reference = 'Kelly TL, Wilson KE, Heymsfield SB (2009) Dual Energy X-Ray Absorptiometry Body Composition Reference Values from NHANES. PLOS ONE 4(9): e7038.'),
    
    dxa_l_arm_lean_mass = list( Description = 'L Arm Lean Mass',
                                Unit = "g"),
    dxa_r_arm_lean_mass = list( Description = 'R Arm Lean Mass',
                                Unit = "g"),
    
    dxa_trunk_bmc = list( Description = 'Trunk bone mineral content (BMC)',
                          Unit = "g"),
    
    dxa_trunk_lean_mass = list( Description = 'Trunk Lean Mass',
                                Unit = "g"),
    dxa_l_leg_lean_mass = list( Description = 'L Leg Lean Mass',
                                Unit = "g"),
    dxa_r_leg_lean_mass = list( Description = 'R Leg Lean Mass',
                                Unit = "g"),
    dxa_subtotal_lean_mass = list( Description = 'Subtotal Lean Mass',
                                   Unit = "g"),
    dxa_head_lean_mass = list( Description = 'Head Lean Mass',
                               Unit = "g"),
    dxa_total_lean_mass = list( Description = 'Total Lean Mass',
                                Unit = "g"),
    
    
    brief1 = list( Description = 'My child is fidgety',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief2 = list( Description = 'My child resists or has trouble accepting a different way to solve a problem with schoolwork, friends, tasks, etc.',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief3 = list( Description = 'My child, when given three things to do, remembers only the first or last',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief4 = list( Description = 'My child is unaware of how his/her behavior affects or bothers others',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief5 = list( Description = 'My child\'s work is sloppy',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief6 = list( Description = 'My child has explosive, angry outbursts',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief7 = list( Description = 'My child does not plan ahead for school assignments',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief8 = list( Description = 'My child cannot find things in their room or in their school desk',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief9 = list( Description = 'My child is not a self-starter',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief10 = list( Description = 'My child does not think before doing (is impulsive)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief11 = list( Description = 'My child has trouble getting used to new situations (classes, groups, friends, etc.)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief12 = list( Description = 'My child has a short attention span',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief13 = list( Description = 'My child has poor understanding of own strengths and weaknesses',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief14 = list( Description = 'My child has outbursts for little reason',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief15 = list( Description = 'My child gets caught up in details and misses the big picture',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief16 = list( Description = 'My child gets out of control more than friends',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief17 = list( Description = 'My child gets stuck on one topic or activity',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief18 = list( Description = 'My child forgets his/her name',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief19 = list( Description = 'My child has trouble with chores or tasks that have more than one step',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief20 = list( Description = 'My child does not realize that certain actions bother others',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief21 = list( Description = 'My child\'s written work is poorly organized',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief22 = list( Description = 'Small events trigger big reactions with my child',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief23 = list( Description = 'My child has good ideas but does not get the job done (lacks follow-through)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief24 = list( Description = 'My child talks at the wrong time',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief25 = list( Description = 'My child has trouble finishing tasks (chores, homework, etc.)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief26 = list( Description = 'My child does not notice when his/her behavior causes negative reactions',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief27 = list( Description = 'My child reacts more strongly to situations than other children',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief28 = list( Description = 'My child has trouble remembering things, even for a few minutes',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief29 = list( Description = 'My child makes careless errors',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief30 = list( Description = 'My child gets out of seat at the wrong times',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief31 = list( Description = 'My child becomes upset with new situations',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief32 = list( Description = 'My child has trouble concentrating on tasks, schoolwork, etc.',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief33 = list( Description = 'My child has poor handwriting',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief34 = list( Description = 'My child\'s mood changes frequently',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief35 = list( Description = 'My child has good ideas but cannot get them on paper',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief36 = list( Description = 'My child has trouble counting to three',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief37 = list( Description = 'My child leaves messes that others have to clean up',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief38 = list( Description = 'My child needs to be told when to begin a task even when willing',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief39 = list( Description = 'My child acts too wild or "out of control"',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief40 = list( Description = 'My child thinks too much about the same topic',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief41 = list( Description = 'My child forgets what he/she was doing',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief42 = list( Description = 'My child does not check work for mistakes',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief43 = list( Description = 'My child\'s angry or tearful outbursts are intense but end suddenly',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief44 = list( Description = 'My child becomes overwhelmed by large assignments',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief45 = list( Description = 'My child loses lunch box, lunch money, permission slips, homework, etc.',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief46 = list( Description = 'My child needs help from an adult to stay on task',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief47 = list( Description = 'My child forgets to hand in homework, even when completed',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief48 = list( Description = 'My child has trouble putting the brakes on his/her actions',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief49 = list( Description = 'My child resists change of routine, foods, places, etc.',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief50 = list( Description = 'My child has trouble getting started on homework or tasks',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief51= list( Description = 'My child\'s mood is easily influenced by the situation',
                   Levels = list ('0' = 'Never',
                                  '1' = 'Sometimes',
                                  '2' = 'Often')),
    brief52 = list( Description = 'My child underestimates time needed to finish tasks',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief53 = list( Description = 'My child does not bring home homework, assignment sheets, materials, etc.',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief54 = list( Description = 'My child cannot find the front door of home',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief55 = list( Description = 'My child does not take initiative',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief56 = list( Description = 'My child becomes upset too easily',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief57 = list( Description = 'My child starts assignments or tasks at the last minute',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief58 = list( Description = 'My child has trouble moving from one activity to another',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief59 = list( Description = 'My child has trouble carrying out the actions needed to reach goals (saving money for special item, studying to get a good grade, etc.)',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief60 = list( Description = 'My child is disturbed by change of teacher or class',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief61 = list( Description = 'My child has trouble organizing activities with friends',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief62 = list( Description = 'My child becomes too silly',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                    Levels = list ('0' = 'Never',
                                   '1' = 'Sometimes',
                                   '2' = 'Often')),
    brief2_inhibit = list( Description = 'Inhibition raw score (sum of all items in subscale)',
                           Derivative = TRUE),
    brief2_inhibit_t = list( Description = 'Inhibition T-score (age and sex normed)',
                             Derivative = TRUE),
    brief2_inhibit_p = list( Description = 'Inhibition Percentile (age and sex normed)',
                             Derivative = TRUE),
    brief2_selfmon = list( Description = 'Self-Monitoring raw score (sum of all items in subscale)',
                           Derivative = TRUE),
    brief2_selfmon_t = list( Description = 'Self-Monitoring T-score (age and sex normed)',
                             Derivative = TRUE),
    brief2_selfmon_p = list( Description = 'Self-Monitoring Percentile (age and sex normed)',
                             Derivative = TRUE),
    brief2_shift = list( Description = 'Shifting raw score (sum of all items in subscale)',
                         Derivative = TRUE),
    brief2_shift_t = list( Description = 'Shifting T-score (age and sex normed)',
                           Derivative = TRUE),
    brief2_shift_p = list( Description = 'Shifting Percentile (age and sex normed)',
                           Derivative = TRUE),
    brief2_emcont = list( Description = 'Emotional Control raw score (sum of all items in subscale)',
                          Derivative = TRUE),
    brief2_emcont_t = list( Description = 'Emotional Control T-score (age and sex normed)',
                            Derivative = TRUE),
    brief2_emcont_p = list( Description = 'Emotional Control Percentile (age and sex normed)',
                            Derivative = TRUE),
    brief2_initiate = list( Description = 'Initiate raw score (sum of all items in subscale)',
                            Derivative = TRUE),
    brief2_initiate_t = list( Description = 'Initiate T-score (age and sex normed)',
                              Derivative = TRUE),
    brief2_initiate_p = list( Description = 'Initiate Percentile (age and sex normed)',
                              Derivative = TRUE),
    brief2_wm = list( Description = 'Working Memory raw score (sum of all items in subscale)',
                      Derivative = TRUE),
    brief2_wm_t = list( Description = 'Working Memory T-score (age and sex normed)',
                        Derivative = TRUE),
    brief2_wm_p = list( Description = 'Working Memory Percentile (age and sex normed)',
                        Derivative = TRUE),
    brief2_planorg = list( Description = 'Planning/Organization raw score (sum of all items in subscale)',
                           Derivative = TRUE),
    brief2_planorg_t = list( Description = 'Planning/Organization T-score (age and sex normed)',
                             Derivative = TRUE),
    brief2_planorg_p = list( Description = 'Planning/Organization Percentile (age and sex normed)',
                             Derivative = TRUE),
    brief2_taskmon = list( Description = 'Task Monitoring raw score (sum of all items in subscale)',
                           Derivative = TRUE),
    brief2_taskmon_t = list( Description = 'Task Monitoring T-score (age and sex normed)',
                             Derivative = TRUE),
    brief2_taskmon_p = list( Description = 'Task Monitoring Percentile (age and sex normed)',
                             Derivative = TRUE),
    brief2_orgmat = list( Description = 'Organiation of Materials raw score (sum of all items in subscale)',
                          Derivative = TRUE),
    brief2_orgmat_t = list( Description = 'Organiation of Materials T-score (age and sex normed)',
                            Derivative = TRUE),
    brief2_orgmat_p = list( Description = 'Organiation of Materials Percentile (age and sex normed)',
                            Derivative = TRUE),
    brief2_bri = list( Description = 'Behavioral Regulation Index raw score (sum of all items in composite index)',
                       Derivative = TRUE),
    brief2_bri_t = list( Description = 'Behavioral Regulation Index T-score (age and sex normed)',
                         Derivative = TRUE),
    brief2_bri_p = list( Description = 'Behavioral Regulation Index Percentile (age and sex normed)',
                         Derivative = TRUE),
    brief2_eri = list( Description = 'Emotional Regulaiton Index raw score (sum of all items in composite index)',
                       Derivative = TRUE),
    brief2_eri_t = list( Description = 'Emotional Regulaiton Index T-score (age and sex normed)',
                         Derivative = TRUE),
    brief2_eri_p = list( Description = 'Emotional Regulaiton Index Percentile (age and sex normed)',
                         Derivative = TRUE),
    brief2_cri = list( Description = 'Cognitive Regulation Index raw score (sum of all items in composite index)',
                       Derivative = TRUE),
    brief2_cri_t = list( Description = 'Cognitive Regulation Index T-score (age and sex normed)',
                         Derivative = TRUE),
    brief2_cri_p = list( Description = 'Cognitive Regulation Index Percentile (age and sex normed)',
                         Derivative = TRUE),
    brief2_gec = list( Description = 'General Executive Composite raw score (sum of all items in questionnaire)',
                       Derivative = TRUE),
    brief2_gec_t = list( Description = 'General Executive Composite T-score (age and sex normed)',
                         Derivative = TRUE),
    brief2_gec_p = list( Description = 'General Executive Composite Percentile (age and sex normed)',
                         Derivative = TRUE),
    brief2_negativity = list( Description = 'Negativity Check - raw score',
                              Derivative = TRUE),
    brief2_negativity_p = list( Description = 'Negativity Check Percentile',
                                Levels = list ('0' = '<=98',
                                               '1' = '99',
                                               '2' = '>99'),
                                Derivative = TRUE),
    brief2_negativity_cat = list( Description = 'Negativity Check Category',
                                  Levels = list ('0' = 'Acceptable',
                                                 '1' = 'Elevated',
                                                 '2' = 'Highly Elevated'),
                                  Derivative = TRUE),
    brief2_inconsistency = list( Description = 'Inconsistency Check - raw score',
                                 Derivative = TRUE),
    brief2_inconsistency_p = list( Description = 'Inconsistency Check Percentile',
                                   Levels = list ('0' = '<=98',
                                                  '1' = '99',
                                                  '2' = '>99'),
                                   Derivative = TRUE),
    brief2_inconsistency_cat = list( Description = 'Inconsistency Check Category',
                                     Levels = list ('0' = 'Acceptable',
                                                    '1' = 'Questionable',
                                                    '2' = 'Inconsistent'),
                                     Derivative = TRUE),
    brief2_infrequency = list( Description = 'Infrequency - raw score',
                               Derivative = TRUE),
    brief2_infrequency_p = list( Description = 'Infrequency Percentile',
                                 Levels = list ('0' = '99',
                                                '1' = '>99'),
                                 Derivative = TRUE),
    brief2_infrequency_cat = list( Description = 'Infrequency Category',
                                   Levels = list ('0' = 'Acceptable',
                                                  '1' = 'Questionable'),
                                   Derivative = TRUE)
  )
  
  # convert formatting to JSON
  data_json <- RJSONIO::toJSON(data_list, pretty = TRUE)
  
  # double check
  if (isFALSE(RJSONIO::isValidJSON(data_json, asText = TRUE))){
    print('JSON file may be invalid')
  }
  
  return(data_json)
  
}
