#' json_tastetest: Generates a json file for the Taste-Test derivative database file
#'
#' This function generates a json file for the sTaste-Test derivative database
#'
#' @return A json file documenting the Taste-Test derivative database
#'
#'
#' @export

json_tastetest <- function() {
  
  tastetest_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'The Taste-Test Task has participants rate how much they want to eat a sample of food, consume the food, rate how much they liked the food sample, and then take a sip of water both before and after a meal.',
      DatasetType = 'derivative'),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-baseline' = 'baseline',
                                      'ses-followup' = '1-year follow-up')),
    visit_date = list( Description = 'Date of visit',
                       Unit = 'YYYY-MM-DD'),
    pre_meal_mean_want = list( Description = 'Pre-Meal Wanting - Meal Foods: mean rating'),
    pre_low_ed_mean_want = list( Description = 'Pre-Meal Wanting - Low-ED Food: mean rating'),
    pre_high_ed_mean_want = list( Description = 'Pre-Meal Wanting - High-ED Food: mean rating'),
    pre_carrot_want = list( Description = 'Pre-Meal Wanting - Carrot: practice rating',
                            Levels = list ( '0' = 'Not At All',
                                            '1' = 'A Little',
                                            '2' = 'A Lot',
                                            '3' = 'Very Much')),
    pre_cknug1_want = list( Description = 'Pre-Meal Wanting - Chicken Nugget: sample 1 rating',
                        Levels = list ( '0' = 'Not At All',
                                        '1' = 'A Little',
                                        '2' = 'A Lot',
                                        '3' = 'Very Much')),
    pre_cknug2_want = list( Description = 'Pre-Meal Wanting - Chicken Nugget: sample 2 rating',
                        Levels = list ( '0' = 'Not At All',
                                        '1' = 'A Little',
                                        '2' = 'A Lot',
                                        '3' = 'Very Much')),
    pre_cknug3_want = list( Description = 'Pre-Meal Wanting - Chicken Nugget: sample 3 rating',
                        Levels = list ( '0' = 'Not At All',
                                        '1' = 'A Little',
                                        '2' = 'A Lot',
                                        '3' = 'Very Much')),
    pre_cknug_mean_want = list( Description = 'Pre-Meal Wanting - Chicken Nugget: mean rating'),
    pre_mac1_want = list( Description = 'Pre-Meal Wanting - Macarroni and Cheese: sample 1 rating',
                      Levels = list ( '0' = 'Not At All',
                                      '1' = 'A Little',
                                      '2' = 'A Lot',
                                      '3' = 'Very Much')),
    pre_mac2_want = list( Description = 'Pre-Meal Wanting - Macarroni and Cheese: sample 2 rating',
                      Levels = list ( '0' = 'Not At All',
                                      '1' = 'A Little',
                                      '2' = 'A Lot',
                                      '3' = 'Very Much')),
    pre_mac3_want = list( Description = 'Pre-Meal Wanting - Macarroni and Cheese: sample 3 rating',
                      Levels = list ( '0' = 'Not At All',
                                      '1' = 'A Little',
                                      '2' = 'A Lot',
                                      '3' = 'Very Much')),
    pre_mac_mean_want = list( Description = 'Pre-Meal Wanting - Macarroni and Cheese: mean rating'),
    pre_grape1_want = list( Description = 'Pre-Meal Wanting - Grapes: sample 1 rating',
                        Levels = list ( '0' = 'Not At All',
                                        '1' = 'A Little',
                                        '2' = 'A Lot',
                                        '3' = 'Very Much')),
    pre_grape2_want = list( Description = 'Pre-Meal Wanting - Grapes: sample 2 rating',
                        Levels = list ( '0' = 'Not At All',
                                        '1' = 'A Little',
                                        '2' = 'A Lot',
                                        '3' = 'Very Much')),
    pre_grape3_want = list( Description = 'Pre-Meal Wanting - Grapes: sample 3 rating',
                        Levels = list ( '0' = 'Not At All',
                                        '1' = 'A Little',
                                        '2' = 'A Lot',
                                        '3' = 'Very Much')),
    pre_grape_mean_want = list( Description = 'Pre-Meal Wanting - Grapes rating'),
    pre_orange_want = list( Description = 'Pre-Meal Wanting - Mandarine Orange rating',
                        Levels = list ( '0' = 'Not At All',
                                        '1' = 'A Little',
                                        '2' = 'A Lot',
                                        '3' = 'Very Much')),
    pre_broccoli_want = list( Description = 'Pre-Meal Wanting - Broccoli rating',
                          Levels = list ( '0' = 'Not At All',
                                          '1' = 'A Little',
                                          '2' = 'A Lot',
                                          '3' = 'Very Much')),
    pre_gbean_want = list( Description = 'Pre-Meal Wanting - Green Bean rating',
                       Levels = list ( '0' = 'Not At All',
                                       '1' = 'A Little',
                                       '2' = 'A Lot',
                                       '3' = 'Very Much')),
    pre_hershey_want = list( Description = 'Pre-Meal Wanting - Hershey Kiss rating',
                         Levels = list ( '0' = 'Not At All',
                                         '1' = 'A Little',
                                         '2' = 'A Lot',
                                         '3' = 'Very Much')),
    pre_cracker_want = list( Description = 'Pre-Meal Wanting - Cracker rating',
                         Levels = list ( '0' = 'Not At All',
                                         '1' = 'A Little',
                                         '2' = 'A Lot',
                                         '3' = 'Very Much')),
    pre_fruitsnack_want = list( Description = 'Pre-Meal Wanting - Fruit Snack rating',
                            Levels = list ( '0' = 'Not At All',
                                            '1' = 'A Little',
                                            '2' = 'A Lot',
                                            '3' = 'Very Much')),
    pre_meal_mean_like = list( Description = 'Pre-Meal Liking - Meal Foods: mean rating'),
    pre_low_ed_mean_like = list( Description = 'Pre-Meal Liking - Low-ED Food: mean rating'),
    pre_high_ed_mean_like = list( Description = 'Pre-Meal Liking - High-ED Food: mean rating'),
    pre_carrot_like = list( Description = 'Pre-Meal Liking - Carrot: practice rating',
                            Levels = list ( '0' = 'Very Bad',
                                            '1' = 'Bad',
                                            '2' = 'Good',
                                            '3' = 'Very Good')),
    pre_cknug1_like = list( Description = 'Pre-Meal Liking - Chicken Nugget: sample 1 rating',
                        Levels = list ( '0' = 'Very Bad',
                                        '1' = 'Bad',
                                        '2' = 'Good',
                                        '3' = 'Very Good')),
    pre_cknug2_like = list( Description = 'Pre-Meal Liking - Chicken Nugget: sample 2 rating',
                        Levels = list ( '0' = 'Very Bad',
                                        '1' = 'Bad',
                                        '2' = 'Good',
                                        '3' = 'Very Good')),
    pre_cknug3_like = list( Description = 'Pre-Meal Liking - Chicken Nugget: sample 3 rating',
                        Levels = list ( '0' = 'Very Bad',
                                        '1' = 'Bad',
                                        '2' = 'Good',
                                        '3' = 'Very Good')),
    pre_cknug_mean_like = list( Description = 'Pre-Meal Liking - Chicken Nugget: mean rating'),
    pre_mac1_like = list( Description = 'Pre-Meal Liking - Macarroni and Cheese: sample 1 rating',
                      Levels = list ( '0' = 'Very Bad',
                                      '1' = 'Bad',
                                      '2' = 'Good',
                                      '3' = 'Very Good')),
    pre_mac2_like = list( Description = 'Pre-Meal Liking - Macarroni and Cheese: sample 2 rating',
                      Levels = list ( '0' = 'Very Bad',
                                      '1' = 'Bad',
                                      '2' = 'Good',
                                      '3' = 'Very Good')),
    pre_mac3_like = list( Description = 'Pre-Meal Liking - Macarroni and Cheese: sample 3 rating',
                      Levels = list ( '0' = 'Very Bad',
                                      '1' = 'Bad',
                                      '2' = 'Good',
                                      '3' = 'Very Good')),
    pre_mac_mean_like = list( Description = 'Pre-Meal Liking - Macarroni and Cheese: mean rating'),
    pre_grape1_like = list( Description = 'Pre-Meal Liking - Grapes: sample 1 rating',
                        Levels = list ( '0' = 'Very Bad',
                                        '1' = 'Bad',
                                        '2' = 'Good',
                                        '3' = 'Very Good')),
    pre_grape2_like = list( Description = 'Pre-Meal Liking - Grapes: sample 2 rating',
                        Levels = list ( '0' = 'Very Bad',
                                        '1' = 'Bad',
                                        '2' = 'Good',
                                        '3' = 'Very Good')),
    pre_grape3_like = list( Description = 'Pre-Meal Liking - Grapes: sample 3 rating',
                        Levels = list ( '0' = 'Very Bad',
                                        '1' = 'Bad',
                                        '2' = 'Good',
                                        '3' = 'Very Good')),
    pre_grape_mean_like = list( Description = 'Pre-Meal Liking - Grapes rating'),
    pre_orange_like = list( Description = 'Pre-Meal Liking - Mandarine Orange rating',
                        Levels = list ( '0' = 'Very Bad',
                                        '1' = 'Bad',
                                        '2' = 'Good',
                                        '3' = 'Very Good')),
    pre_broccoli_like = list( Description = 'Pre-Meal Liking - Broccoli rating',
                          Levels = list ( '0' = 'Very Bad',
                                          '1' = 'Bad',
                                          '2' = 'Good',
                                          '3' = 'Very Good')),
    pre_gbean_like = list( Description = 'Pre-Meal Liking - Green Bean rating',
                       Levels = list ( '0' = 'Very Bad',
                                       '1' = 'Bad',
                                       '2' = 'Good',
                                       '3' = 'Very Good')),
    pre_hershey_like = list( Description = 'Pre-Meal Liking - Hershey Kiss rating',
                         Levels = list ( '0' = 'Very Bad',
                                         '1' = 'Bad',
                                         '2' = 'Good',
                                         '3' = 'Very Good')),
    pre_cracker_like = list( Description = 'Pre-Meal Liking - Cracker rating',
                         Levels = list ( '0' = 'Very Bad',
                                         '1' = 'Bad',
                                         '2' = 'Good',
                                         '3' = 'Very Good')),
    pre_fruitsnack_like = list( Description = 'Pre-Meal Liking - Fruit Snack rating',
                            Levels = list ( '0' = 'Very Bad',
                                            '1' = 'Bad',
                                            '2' = 'Good',
                                            '3' = 'Very Good')),
    post_meal_mean_want = list( Description = 'Post-Meal Wanting - Meal Foods: mean rating'),
    post_low_ed_mean_want = list( Description = 'Post-Meal Wanting - Low-ED Food: mean rating'),
    post_high_ed_mean_want = list( Description = 'Post-Meal Wanting - High-ED Food: mean rating'),
    post_carrot_want = list( Description = 'Post-Meal Wanting - Carrot: practice rating',
                            Levels = list ( '0' = 'Not At All',
                                            '1' = 'A Little',
                                            '2' = 'A Lot',
                                            '3' = 'Very Much')),
    post_cknug1_want = list( Description = 'Post-Meal Wanting - Chicken Nugget: sample 1 rating',
                            Levels = list ( '0' = 'Not At All',
                                            '1' = 'A Little',
                                            '2' = 'A Lot',
                                            '3' = 'Very Much')),
    post_cknug2_want = list( Description = 'Post-Meal Wanting - Chicken Nugget: sample 2 rating',
                            Levels = list ( '0' = 'Not At All',
                                            '1' = 'A Little',
                                            '2' = 'A Lot',
                                            '3' = 'Very Much')),
    post_cknug3_want = list( Description = 'Post-Meal Wanting - Chicken Nugget: sample 3 rating',
                            Levels = list ( '0' = 'Not At All',
                                            '1' = 'A Little',
                                            '2' = 'A Lot',
                                            '3' = 'Very Much')),
    post_cknug_mean_want = list( Description = 'Post-Meal Wanting - Chicken Nugget: mean rating'),
    post_mac1_want = list( Description = 'Post-Meal Wanting - Macarroni and Cheese: sample 1 rating',
                          Levels = list ( '0' = 'Not At All',
                                          '1' = 'A Little',
                                          '2' = 'A Lot',
                                          '3' = 'Very Much')),
    post_mac2_want = list( Description = 'Post-Meal Wanting - Macarroni and Cheese: sample 2 rating',
                          Levels = list ( '0' = 'Not At All',
                                          '1' = 'A Little',
                                          '2' = 'A Lot',
                                          '3' = 'Very Much')),
    post_mac3_want = list( Description = 'Post-Meal Wanting - Macarroni and Cheese: sample 3 rating',
                          Levels = list ( '0' = 'Not At All',
                                          '1' = 'A Little',
                                          '2' = 'A Lot',
                                          '3' = 'Very Much')),
    post_mac_mean_want = list( Description = 'Post-Meal Wanting - Macarroni and Cheese: mean rating'),
    post_grape1_want = list( Description = 'Post-Meal Wanting - Grapes: sample 1 rating',
                            Levels = list ( '0' = 'Not At All',
                                            '1' = 'A Little',
                                            '2' = 'A Lot',
                                            '3' = 'Very Much')),
    post_grape2_want = list( Description = 'Post-Meal Wanting - Grapes: sample 2 rating',
                            Levels = list ( '0' = 'Not At All',
                                            '1' = 'A Little',
                                            '2' = 'A Lot',
                                            '3' = 'Very Much')),
    post_grape3_want = list( Description = 'Post-Meal Wanting - Grapes: sample 3 rating',
                            Levels = list ( '0' = 'Not At All',
                                            '1' = 'A Little',
                                            '2' = 'A Lot',
                                            '3' = 'Very Much')),
    post_grape_mean_want = list( Description = 'Post-Meal Wanting - Grapes rating'),
    post_orange_want = list( Description = 'Post-Meal Wanting - Mandarine Orange rating',
                            Levels = list ( '0' = 'Not At All',
                                            '1' = 'A Little',
                                            '2' = 'A Lot',
                                            '3' = 'Very Much')),
    post_broccoli_want = list( Description = 'Post-Meal Wanting - Broccoli rating',
                              Levels = list ( '0' = 'Not At All',
                                              '1' = 'A Little',
                                              '2' = 'A Lot',
                                              '3' = 'Very Much')),
    post_gbean_want = list( Description = 'Post-Meal Wanting - Green Bean rating',
                           Levels = list ( '0' = 'Not At All',
                                           '1' = 'A Little',
                                           '2' = 'A Lot',
                                           '3' = 'Very Much')),
    post_hershey_want = list( Description = 'Post-Meal Wanting - Hershey Kiss rating',
                             Levels = list ( '0' = 'Not At All',
                                             '1' = 'A Little',
                                             '2' = 'A Lot',
                                             '3' = 'Very Much')),
    post_cracker_want = list( Description = 'Post-Meal Wanting - Cracker rating',
                             Levels = list ( '0' = 'Not At All',
                                             '1' = 'A Little',
                                             '2' = 'A Lot',
                                             '3' = 'Very Much')),
    post_fruitsnack_want = list( Description = 'Post-Meal Wanting - Fruit Snack rating',
                                Levels = list ( '0' = 'Not At All',
                                                '1' = 'A Little',
                                                '2' = 'A Lot',
                                                '3' = 'Very Much')),
    post_meal_mean_like = list( Description = 'Post-Meal Liking - Meal Foods: mean rating'),
    post_low_ed_mean_like = list( Description = 'Post-Meal Liking - Low-ED Food: mean rating'),
    post_high_ed_mean_like = list( Description = 'Post-Meal Liking - High-ED Food: mean rating'),
    post_carrot_like = list( Description = 'Post-Meal Liking - Carrot: practice rating',
                            Levels = list ( '0' = 'Very Bad',
                                            '1' = 'Bad',
                                            '2' = 'Good',
                                            '3' = 'Very Good')),
    post_cknug1_like = list( Description = 'Post-Meal Liking - Chicken Nugget: sample 1 rating',
                            Levels = list ( '0' = 'Very Bad',
                                            '1' = 'Bad',
                                            '2' = 'Good',
                                            '3' = 'Very Good')),
    post_cknug2_like = list( Description = 'Post-Meal Liking - Chicken Nugget: sample 2 rating',
                            Levels = list ( '0' = 'Very Bad',
                                            '1' = 'Bad',
                                            '2' = 'Good',
                                            '3' = 'Very Good')),
    post_cknug3_like = list( Description = 'Post-Meal Liking - Chicken Nugget: sample 3 rating',
                            Levels = list ( '0' = 'Very Bad',
                                            '1' = 'Bad',
                                            '2' = 'Good',
                                            '3' = 'Very Good')),
    post_cknug_mean_like = list( Description = 'Post-Meal Liking - Chicken Nugget: mean rating'),
    post_mac1_like = list( Description = 'Post-Meal Liking - Macarroni and Cheese: sample 1 rating',
                          Levels = list ( '0' = 'Very Bad',
                                          '1' = 'Bad',
                                          '2' = 'Good',
                                          '3' = 'Very Good')),
    post_mac2_like = list( Description = 'Post-Meal Liking - Macarroni and Cheese: sample 2 rating',
                          Levels = list ( '0' = 'Very Bad',
                                          '1' = 'Bad',
                                          '2' = 'Good',
                                          '3' = 'Very Good')),
    post_mac3_like = list( Description = 'Post-Meal Liking - Macarroni and Cheese: sample 3 rating',
                          Levels = list ( '0' = 'Very Bad',
                                          '1' = 'Bad',
                                          '2' = 'Good',
                                          '3' = 'Very Good')),
    post_mac_mean_like = list( Description = 'Post-Meal Liking - Macarroni and Cheese: mean rating'),
    post_grape1_like = list( Description = 'Post-Meal Liking - Grapes: sample 1 rating',
                            Levels = list ( '0' = 'Very Bad',
                                            '1' = 'Bad',
                                            '2' = 'Good',
                                            '3' = 'Very Good')),
    post_grape2_like = list( Description = 'Post-Meal Liking - Grapes: sample 2 rating',
                            Levels = list ( '0' = 'Very Bad',
                                            '1' = 'Bad',
                                            '2' = 'Good',
                                            '3' = 'Very Good')),
    post_grape3_like = list( Description = 'Post-Meal Liking - Grapes: sample 3 rating',
                            Levels = list ( '0' = 'Very Bad',
                                            '1' = 'Bad',
                                            '2' = 'Good',
                                            '3' = 'Very Good')),
    post_grape_mean_like = list( Description = 'Post-Meal Liking - Grapes rating'),
    post_orange_like = list( Description = 'Post-Meal Liking - Mandarine Orange rating',
                            Levels = list ( '0' = 'Very Bad',
                                            '1' = 'Bad',
                                            '2' = 'Good',
                                            '3' = 'Very Good')),
    post_broccoli_like = list( Description = 'Post-Meal Liking - Broccoli rating',
                              Levels = list ( '0' = 'Very Bad',
                                              '1' = 'Bad',
                                              '2' = 'Good',
                                              '3' = 'Very Good')),
    post_gbean_like = list( Description = 'Post-Meal Liking - Green Bean rating',
                           Levels = list ( '0' = 'Very Bad',
                                           '1' = 'Bad',
                                           '2' = 'Good',
                                           '3' = 'Very Good')),
    post_hershey_like = list( Description = 'Post-Meal Liking - Hershey Kiss rating',
                             Levels = list ( '0' = 'Very Bad',
                                             '1' = 'Bad',
                                             '2' = 'Good',
                                             '3' = 'Very Good')),
    post_cracker_like = list( Description = 'Post-Meal Liking - Cracker rating',
                             Levels = list ( '0' = 'Very Bad',
                                             '1' = 'Bad',
                                             '2' = 'Good',
                                             '3' = 'Very Good')),
    post_fruitsnack_like = list( Description = 'Post-Meal Liking - Fruit Snack rating',
                                Levels = list ( '0' = 'Very Bad',
                                                '1' = 'Bad',
                                                '2' = 'Good',
                                                '3' = 'Very Good'))
    
    )
  
  # convert formatting to JSON
  tastetest_json <- RJSONIO::toJSON(tastetest_list, pretty = TRUE)
  
  # double check
  if (isFALSE(RJSONIO::isValidJSON(tastetest_json, asText = TRUE))){
    print('tastetest JSON file may be invalid')
  }
  
  return(tastetest_json)
  
}