#' json_intake: Generates a json file for intake data along with all associated meal, liking, and wanting information
#'
#' This function generates a json file for intake data along with all associated meal, liking, and wanting information
#'
#' @return A string with data stored in JSON format containing meta-data for intake along with all associated meal, liking, and wanting information data
#'
#'
#' @export

json_intake <- function() {

  intake_list <- list(
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-baseline' = 'baseline',
                                      'ses-followup' = '1-year follow-up')),
    visit_protocol = list( Description = 'child visit protocol number (does not necessarilty reflect visit order. See participants.tsv for child visit protocol dates)',
                           Levels = list ('1' =	'Child visit protocol 1 (baseline)',
                                          '3'	= 'Child visit protocol 3 (follow-up')),
    visit_date = list( Description = 'Date of visit',
                       Unit = 'YYYY-MM-DD'),
    
    # liking variables ----
    pre_liking_fullness_time = list( Description = 'Pre-liking (i.e., before VAS liking ratings) fullness rating time',
                                     Unit = "hh:mm:ss"),
    pre_liking_fullness = list( Description = 'Pre-liking (i.e., before VAS liking ratings) fullness rating on a 150 mm visual analgue scale',
                                Reference = 'Keller KL, Assur SA, Torres M, Lofink HE, Thornton JC, Faith MS, Kissileff HR. Potential of an analog scaling device for measuring fullness in children: development and preliminary testing. Appetite. 2006 Sep;47(2):233-43. doi: 10.1016/j.appet.2006.04.004. Epub 2006 Jul 7. PMID: 16828929.',
                                Unit = "mm"),
    liking_mac = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this macaroni and cheese?',
                       Levels = list ('0' =	'Hate it',
                                      '1'	= 'Dislike it',
                                      '2'	= 'It\'s okay',
                                      '3'	= 'Like it',
                                      '4'	= 'Love it')),
    liking_cknug = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this chicken nugget?',
                         Levels = list ('0' =	'Hate it',
                                        '1'	= 'Dislike it',
                                        '2'	= 'It\'s okay',
                                        '3'	= 'Like it',
                                        '4'	= 'Love it')),
    liking_grapes = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this grape?',
                          Levels = list ('0' =	'Hate it',
                                         '1'	= 'Dislike it',
                                         '2'	= 'It\'s okay',
                                         '3'	= 'Like it',
                                         '4'	= 'Love it')),
    liking_carrot = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this carrot?',
                          Levels = list ('0' =	'Hate it',
                                         '1'	= 'Dislike it',
                                         '2'	= 'It\'s okay',
                                         '3'	= 'Like it',
                                         '4'	= 'Love it')),
    liking_water = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this water?',
                         Levels = list ('0' =	'Hate it',
                                        '1'	= 'Dislike it',
                                        '2'	= 'It\'s okay',
                                        '3'	= 'Like it',
                                        '4'	= 'Love it')),
    liking_popcorn = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this popcorn?',
                           Levels = list ('0' =	'Hate it',
                                          '1'	= 'Dislike it',
                                          '2'	= 'It\'s okay',
                                          '3'	= 'Like it',
                                          '4'	= 'Love it')),
    liking_pretzel = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this pretzel?',
                           Levels = list ('0' =	'Hate it',
                                          '1'	= 'Dislike it',
                                          '2'	= 'It\'s okay',
                                          '3'	= 'Like it',
                                          '4'	= 'Love it')),
    liking_fritos = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this corn chip (Fritos)?',
                             Levels = list ('0' =	'Hate it',
                                            '1'	= 'Dislike it',
                                            '2'	= 'It\'s okay',
                                            '3'	= 'Like it',
                                            '4'	= 'Love it')),
    liking_oreo = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this cookie?',
                        Levels = list ('0' =	'Hate it',
                                       '1'	= 'Dislike it',
                                       '2'	= 'It\'s okay',
                                       '3'	= 'Like it',
                                       '4'	= 'Love it')),
    liking_brownie = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this brownie?',
                           Levels = list ('0' =	'Hate it',
                                          '1'	= 'Dislike it',
                                          '2'	= 'It\'s okay',
                                          '3'	= 'Like it',
                                          '4'	= 'Love it')),
    liking_starburst = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this Starburst?',
                             Levels = list ('0' =	'Hate it',
                                            '1'	= 'Dislike it',
                                            '2'	= 'It\'s okay',
                                            '3'	= 'Like it',
                                            '4'	= 'Love it')),
    liking_skittle = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this Skittle?',
                           Levels = list ('0' =	'Hate it',
                                          '1'	= 'Dislike it',
                                          '2'	= 'It\'s okay',
                                          '3'	= 'Like it',
                                          '4'	= 'Love it')),
    liking_chocolate = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this chocolate (Hershey Kiss)?',
                             Levels = list ('0' =	'Hate it',
                                            '1'	= 'Dislike it',
                                            '2'	= 'It\'s okay',
                                            '3'	= 'Like it',
                                            '4'	= 'Love it')),
    liking_icecream = list( Description = 'Food Liking Visual Analogue Scale (VAS): How much do you like this ice cream?',
                            Levels = list ('0' =	'Hate it',
                                           '1'	= 'Dislike it',
                                           '2'	= 'It\'s okay',
                                           '3'	= 'Like it',
                                           '4'	= 'Love it')),
    
    # food_paradigm_info variables ----
    pre_meal_fullness_time = list( Description = 'Pre-meal fullness rating time',
                                   Unit = "hh:mm:ss"),
    pre_meal_fullness = list( Description = 'Pre-meal fullness rating on a 150 mm visual analgue scale',
                              Reference = 'Keller KL, Assur SA, Torres M, Lofink HE, Thornton JC, Faith MS, Kissileff HR. Potential of an analog scaling device for measuring fullness in children: development and preliminary testing. Appetite. 2006 Sep;47(2):233-43. doi: 10.1016/j.appet.2006.04.004. Epub 2006 Jul 7. PMID: 16828929.',
                              Unit = "mm"),
    test_meal_book = list( Description = 'Book the child selected to listen to during the test meal'),
    test_meal_start_time = list( Description = 'Meal start time',
                                 Unit = "hh:mm"),
    test_meal_end_time = list( Description = 'Meal end time',
                               Unit = "hh:mm"),
    test_meal_duration = list( Description = 'Meal duration. Derived in redcap from test_meal_start_time and test_meal_end_time',
                               Derivative = TRUE),

    # intake data ----
    mac_pre_w_o_plate = list( Description = 'Pre-meal weight of macaroni and cheese without plate',
                              Unit = "grams"),
    mac_pre_w_plate = list( Description = 'Pre-meal weight of macaroni and cheese with plate',
                            Unit = "grams"),
    cknug_pre_w_o_plate = list( Description = 'Pre-meal weight of chicken nuggets without plate',
                                Unit = "grams"),
    cknug_pre_w_plate = list( Description = 'Pre-meal weight of chicken nuggets with a plate',
                              Unit = "grams"),
    grapes_pre_w_o_plate = list( Description = 'Pre-meal weight of grapes without plate',
                                 Unit = "grams"),
    grapes_pre_w_plate = list( Description = 'Pre-meal weight of grapes with plate',
                               Unit = "grams"),
    carrots_pre_w_o_plate = list( Description = 'Post-meal weight of carrots without a plate',
                                  Unit = "grams"),
    carrots_pre_w_plate = list( Description = 'Pre-meal weight of carrots with plate',
                                Unit = "grams"),
    ketchup_pre_w_o_plate = list( Description = 'Pre-meal weight of ketchup without plate',
                                  Unit = "grams"),
    ketchup_pre_w_plate = list( Description = 'Pre-meal weight of ketchup with plate',
                                Unit = "grams"),
    water_pre_w_o_plate = list( Description = 'Post-meal weight of water without cup',
                                Unit = "grams"),
    water_pre_w_plate = list( Description = 'Pre-meal weight of water with cup',
                              Unit = "grams"),
    mac_post_w_plate = list( Description = 'Post-meal weight of macaroni and cheese with plate',
                             Unit = "grams"),
    cknug_post_w_plate = list( Description = 'Post-meal weight of chicken nuggets with a plate',
                               Unit = "grams"),
    grapes_post_w_plate = list( Description = 'Post-meal weight of grapes with plate',
                                Unit = "grams"),
    carrots_post_w_plate = list( Description = 'Post-meal weight of carrots with plate',
                                 Unit = "grams"),
    ketchup_post_w_plate = list( Description = 'Post-meal weight of ketchup with plate',
                                 Unit = "grams"),
    water_post_w_plate = list( Description = 'Post-meal weight of water with cup',
                               Unit = "grams"),
    cknug_g_consumed = list( Description = 'Weight of chicken nuggets consumed during test meal. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                              Derivative = TRUE,
                              Unit = "grams"),
    carrot_kcal_consumed = list( Description = 'Energy of chicken nuggets consumed during test meal. Computed by multiplying [item]_g_consumed by [item] energy density',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    mac_g_consumed = list( Description = 'Weight of macarroni and cheese consumed during test meal. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                             Derivative = TRUE,
                             Unit = "grams"),
    mac_kcal_consumed = list( Description = 'Energy of macarroni and cheese consumed during test meal. Computed by multiplying [item]_g_consumed by [item] energy density',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    grapes_g_consumed = list( Description = 'Weight of grapes consumed during test meal. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                              Derivative = TRUE,
                              Unit = "grams"),
    grapes_kcal_consumed = list( Description = 'Energy of grapes consumed during test meal. Computed by multiplying [item]_g_consumed by [item] energy density',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    carrots_g_consumed = list( Description = 'Weight of carrots consumed during test meal. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                              Derivative = TRUE,
                              Unit = "grams"),
    carrots_kcal_consumed = list( Description = 'Energy of carrots consumed during test meal. Computed by multiplying [item]_g_consumed by [item] energy density',
                                 Derivative = TRUE,
                                 Unit = "kcal"),
    ketchup_g_consumed = list( Description = 'Weight of ketchup consumed during test meal. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                               Derivative = TRUE,
                               Unit = "grams"),
    ketchup_kcal_consumed = list( Description = 'Energy of ketchup consumed during test meal. Computed by multiplying [item]_g_consumed by [item] energy density',
                                  Derivative = TRUE,
                                  Unit = "kcal"),
    meal_g_consumed = list( Description = 'Total weight of food consumed during test meal (does not include water)',
                            Derivative = TRUE,
                            Unit = "grams"),
    meal_g_consumed_inc_water = list( Description = 'Total weight of food and water consumed during test meal',
                                      Derivative = TRUE,
                                      Unit = "grams"),
    meal_kcal_consumed = list( Description = 'Total energy of food consumed during test meal',
                               Derivative = TRUE,
                               Unit = "kcal"),
    post_meal_fullness_time = list( Description = 'Post-meal fullness rating time',
                                    Unit = "hh:mm:ss"),
    post_meal_fullness = list( Description = 'Post-meal fullness rating on a 150 mm visual analgue scale',
                               Reference = 'Keller KL, Assur SA, Torres M, Lofink HE, Thornton JC, Faith MS, Kissileff HR. Potential of an analog scaling device for measuring fullness in children: development and preliminary testing. Appetite. 2006 Sep;47(2):233-43. doi: 10.1016/j.appet.2006.04.004. Epub 2006 Jul 7. PMID: 16828929.',
                               Unit = "mm"),
    # EAH wanting variables ----
    pre_wanting_fullness_time = list( Description = 'Pre-EAH liking and wanting (i.e., before VAS liking and wanting ratings for EAH) fullness rating time',
                                   Unit = "hh:mm:ss"),
    pre_wanting_liking_fullness = list( Description = 'Pre-EAH liking and wanting (i.e., before VAS liking and wanting ratings for EAH) fullness rating on a 150 mm visual analgue scale',
                               Reference = 'Keller KL, Assur SA, Torres M, Lofink HE, Thornton JC, Faith MS, Kissileff HR. Potential of an analog scaling device for measuring fullness in children: development and preliminary testing. Appetite. 2006 Sep;47(2):233-43. doi: 10.1016/j.appet.2006.04.004. Epub 2006 Jul 7. PMID: 16828929.',
                               Unit = "mm"),
    eah_wanting_popcorn = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat popcorn right now?'),
    eah_wanting_pretzels = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat pretzels right now?'),
    eah_wanting_corn_chips = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat corn chips right now?'),
    eah_wanting_oreos = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat Oreos right now?'),
    eah_wanting_brownies = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat brownies right now?'),
    eah_wanting_starburst = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat Starbursts right now?'),
    eah_wanting_skittles = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat skittles right now?'),
    eah_wanting_chocolate = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat Hershey Kiss right now?'),
    eah_wanting_ice_cream = list( Description = 'EAH Wanting Questionnaire item: How much do you want to eat ice cream right now?'),
    
    eah_wanting_markers = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with these markers right now?'),
    eah_wanting_crayons = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with these crayons right now?'),
    eah_wanting_color_book_marvels = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with this coloring book right now?'),
    eah_wanting_oonies_inflate = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with this Oonies Inflator right now?'),
    eah_wanting_colorpencils = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with these colored pencils right now?'),
    eah_wanting_activitybook = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with this activity book right now?'),
    eah_wanting_colorbook = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with this coloring book right now?'),
    eah_wanting_legos = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with Legos right now?'),
    eah_wanting_squeakee = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with Squeakee the Balloon Dog right now?'),
    eah_wanting_dinosaurs = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with dinosaurs right now?'),
    eah_wanting_oonies = list( Description = 'EAH Wanting Questionnaire item: How much do you want to play with Oonies right now?'),


    
    # EAH intake variables ----
    pre_meal_fullness_time = list( Description = 'Pre-meal fullness rating time',
                                   Unit = "hh:mm:ss"),
    pre_eah_fullness = list( Description = 'Pre-EAH fullness rating on a 150 mm visual analgue scale',
                             Reference = 'Keller KL, Assur SA, Torres M, Lofink HE, Thornton JC, Faith MS, Kissileff HR. Potential of an analog scaling device for measuring fullness in children: development and preliminary testing. Appetite. 2006 Sep;47(2):233-43. doi: 10.1016/j.appet.2006.04.004. Epub 2006 Jul 7. PMID: 16828929.',
                             Unit = "mm"),
    eah_start_time = list( Description = 'EAH protocol start time',
                           Unit = "hh:mm"),
    eah_end_time = list( Description = 'EAH protocol start time',
                         Unit = "hh:mm"),
    hershey_pre_w_o_plate = list( Description = 'Pre-EAH weight of Hersheys kiss without plate',
                                  Unit = "grams"),
    hershey_pre_w_plate = list( Description = 'Pre-EAH weight of Hersheys kiss with plate',
                                Unit = "grams"),
    starburst_pre_w_o_plate = list( Description = 'Pre-EAH weight of starbursts without plate',
                                    Unit = "grams"),
    starburst_pre_w_plate = list( Description = 'Pre-EAH weight of starbursts with plate',
                                  Unit = "grams"),
    oreo_pre_w_o_plate = list( Description = 'Pre-EAH weight of oreos without plate',
                               Unit = "grams"),
    oreo_pre_w_plate = list( Description = 'Pre-EAH weight of oreos with plate',
                             Unit = "grams"),
    popcorn_pre_w_o_plate = list( Description = 'Pre-EAH weight of popcorn without plate',
                                  Unit = "grams"),
    popcorn_pre_w_plate = list( Description = 'Pre-EAH weight of popcorn with plate',
                                Unit = "grams"),
    fritos_pre_w_o_plate = list( Description = 'Pre-EAH weight of Fritos without plate',
                                 Unit = "grams"),
    fritos_pre_w_plate = list( Description = 'Pre-EAH weight of Fritos with plate',
                               Unit = "grams"),
    pretzel_pre_w_o_plate = list( Description = 'Pre-EAH weight of pretzels without plate',
                                  Unit = "grams"),
    pretzel_pre_w_plate = list( Description = 'Pre-EAH weight of pretzels with plate',
                                Unit = "grams"),
    skittles_pre_w_o_plate = list( Description = 'Pre-EAH weight of Skilles without plate',
                                   Unit = "grams"),
    skittles_pre_w_plate = list( Description = 'Pre-EAH weight of brownies with plate',
                                 Unit = "grams"),
    brownie_pre_w_o_plate = list( Description = 'Pre-EAH weight of brownies without plate',
                                  Unit = "grams"),
    brownie_pre_w_plate = list( Description = 'Pre-EAH weight of brownies with plate',
                                Unit = "grams"),
    ice_cream_pre_w_o_plate = list( Description = 'Pre-EAH weight of Ice cream without plate',
                                    Unit = "grams"),
    ice_cream_pre_w_plate = list( Description = 'Pre-EAH weight of Ice cream with plate',
                                  Unit = "grams"),
    water_eah_pre_w_o_plate = list( Description = 'Pre-EAH weight of water without container',
                                    Unit = "grams"),
    water_eah_pre_w_plate = list( Description = 'Pre-EAH weight of water with container',
                                  Unit = "grams"),
    hershy_post_w_plate = list( Description = 'Post-EAH weight of Hersheys kiss with plate',
                                Unit = "grams"),
    starburst_post_w_plate = list( Description = 'Post-EAH weight of starbursts with plate',
                                   Unit = "grams"),
    oreo_post_w_plate = list( Description = 'Post-EAH weight of oreos with plate',
                              Unit = "grams"),
    popcorn_post_w_plate = list( Description = 'Post-EAH weight of popcorn with plate',
                                 Unit = "grams"),
    fritos_post_w_plate = list( Description = 'Post-EAH weight of Fritos with plate',
                                Unit = "grams"),
    pretzel_post_w_plate = list( Description = 'Post-EAH weight of pretzels with plate',
                                 Unit = "grams"),
    skittles_post_w_plate = list( Description = 'Post-EAH weight of Skittles with plate',
                                  Unit = "grams"),
    brownie_post_w_plate = list( Description = 'Post-EAH weight of brownies with plate',
                                 Unit = "grams"),
    ice_cream_post_w_plate = list( Description = 'Post-EAH weight of Ice cream with plate',
                                   Unit = "grams"),
    water_eah_post_w_plate = list( Description = 'Post-EAH weight of water with container',
                                   Unit = "grams"),
    brownie_g_consumed = list( Description = 'Weight of brownies consumed during EAH. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                               Derivative = TRUE,
                               Unit = "grams"),
    brownie_kcal_consumed = list( Description = 'Energy of brownies consumed during EAH. Computed by multiplying [item]_g_consumed by [item] energy density',
                                  Derivative = TRUE,
                                  Unit = "kcal"),
    fritos_g_consumed = list( Description = 'Weight of Fritos consumed during EAH. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                                 Derivative = TRUE,
                                 Unit = "grams"),
    fritos_kcal_consumed = list( Description = 'Energy of Fritos consumed during EAH. Computed by multiplying [item]_g_consumed by [item] energy density',
                                    Derivative = TRUE,
                                    Unit = "kcal"),
    hershey_g_consumed = list( Description = 'Weight of Hershey\'s kisses consumed during EAH. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                            Derivative = TRUE,
                            Unit = "grams"),
    hershey_kcal_consumed = list( Description = 'Energy of Hershey\'s kisses consumed during EAH. Computed by multiplying [item]_g_consumed by [item] energy density',
                               Derivative = TRUE,
                               Unit = "kcal"),
    icecream_g_consumed = list( Description = 'Weight of ice cream consumed during EAH. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                                 Derivative = TRUE,
                                 Unit = "grams"),
    icecream_kcal_consumed = list( Description = 'Energy of ice cream consumed during EAH. Computed by multiplying [item]_g_consumed by [item] energy density',
                                    Derivative = TRUE,
                                    Unit = "kcal"),
    oreos_g_consumed = list( Description = 'Weight of oreos consumed during EAH. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                            Derivative = TRUE,
                            Unit = "grams"),
    oreos_kcal_consumed = list( Description = 'Energy of oreos consumed during EAH. Computed by multiplying [item]_g_consumed by [item] energy density',
                               Derivative = TRUE,
                               Unit = "kcal"),
    popcorn_g_consumed = list( Description = 'Weight of popcorn consumed during EAH. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                               Derivative = TRUE,
                               Unit = "grams"),
    popcorn_kcal_consumed = list( Description = 'Energy of popcorn consumed during EAH. Computed by multiplying [item]_g_consumed by [item] energy density',
                                  Derivative = TRUE,
                                  Unit = "kcal"),
    pretzel_g_consumed = list( Description = 'Weight of pretzels consumed during EAH. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                               Derivative = TRUE,
                               Unit = "grams"),
    pretzel_kcal_consumed = list( Description = 'Energy of pretzels consumed during EAH. Computed by multiplying [item]_g_consumed by [item] energy density',
                                  Derivative = TRUE,
                                  Unit = "kcal"),
    skittles_g_consumed = list( Description = 'Weight of skittles consumed during EAH. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                               Derivative = TRUE,
                               Unit = "grams"),
    skittles_kcal_consumed = list( Description = 'Energy of skittles consumed during EAH. Computed by multiplying [item]_g_consumed by [item] energy density',
                                  Derivative = TRUE,
                                  Unit = "kcal"),
    starburst_g_consumed = list( Description = 'Weight of starbursts consumed during EAH. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                                 Derivative = TRUE,
                                 Unit = "grams"),
    starburst_kcal_consumed = list( Description = 'Energy of starbursts consumed during EAH. Computed by multiplying [item]_g_consumed by [item] energy density',
                                    Derivative = TRUE,
                                    Unit = "kcal"),
    eah_water_g_consumed = list( Description = 'Weight of water consumed during EAH. Computed by subtracting [item]_post_w_plate from [item]_pre_w_plate',
                                 Derivative = TRUE,
                                 Unit = "grams"),
    eah_water_kcal_consumed = list( Description = 'Energy of water consumed during EAH. Computed by multiplying [item]_g_consumed by [item] energy density',
                                    Derivative = TRUE,
                                    Unit = "kcal"),
    
    eah_g_consumed = list( Description = 'Total weight of food consumed during EAH (does not include water)',
                           Derivative = TRUE,
                           Unit = "grams"),
    eah_g_consumed_inc_water = list( Description = 'Total weight of food and water consumed during EAH',
                                     Derivative = TRUE,
                                     Unit = "grams"),
    eah_kcal_consumed = list( Description = 'Total energy of food consumed during EAH',
                              Derivative = TRUE,
                              Unit = "kcal"),
    total_g_consumed = list( Description = 'Total weight of food consumed during test meal and EAH (does not include water)',
                             Derivative = TRUE,
                             Unit = "grams"),
    total_g_consumed_inc_water = list( Description = 'Total weight of food and water consumed during test meal and EAH',
                                       Derivative = TRUE,
                                       Unit = "grams"),
    totak_kcal_consumed = list( Description = 'Total energy of food consumed during test meal and EAH',
                                Derivative = TRUE,
                                Unit = "kcal"),
    post_eah_fullness_time = list( Description = 'Post-EAH fullness rating time',
                                   Unit = "hh:mm:ss"),
    post_eah_fullness = list( Description = 'Post-EAH fullness rating on a 150 mm visual analgue scale',
                              Reference = 'Keller KL, Assur SA, Torres M, Lofink HE, Thornton JC, Faith MS, Kissileff HR. Potential of an analog scaling device for measuring fullness in children: development and preliminary testing. Appetite. 2006 Sep;47(2):233-43. doi: 10.1016/j.appet.2006.04.004. Epub 2006 Jul 7. PMID: 16828929.',
                              Unit = "mm"),

    # notes ----
    pre_liking_fullness_notes = list( Description = 'Notes about pre-liking (i.e., before VAS meal liking ratings) fullness rating'),
    pre_meal_fullness_notes = list( Description = 'Notes about pre-meal fullness rating'),
    post_meal_fullness_notes = list( Description = 'Notes about post-meal fullness rating'),
    pre_wanting_fullness_notes = list( Description = 'Notes about pre-eah liking and wanting (i.e., before VAS liking and wanting ratings for EAH) fullness rating'),
    post_eah_fullness_notes = list( Description = 'Notes about post-EAH fullness rating'),
    want_liking_eah_notes = list( Description = 'Notes on pre-EAH liking and wanting data for EAH foods'),
    game_want_eah_notes = list( Description = 'Notes about pre-EAH game wanting ratings'),
    test_meal_notes = list( Description = 'Notes about meal protocol'),
    eah_notes = list( Description = 'Notes about EAH protocol'),
    preweight_notes = list( Description = 'Notes about meal pre-weights'),
    mac_post_notes = list( Description = 'Notes about macaroni and cheese'),
    cknug_post_notes = list( Description = 'Notes about chicken nugges'),
    grapes_post_notes = list( Description = 'Notes about grapes'),
    carrots_post_notes = list( Description = 'Notes about carrots'),
    ketchup_post_notes = list( Description = 'Notes about ketchup'),
    water_post_notes = list( Description = 'Notes about water'),
    postweight_notes = list( Description = 'Notes about meal post-weights'),
    pretzel_notes = list( Description = 'Notes about pretzel'),
    eah_preweight_notes = list( Description = 'Notes about EAH pre-weights'),
    eah_taste_prep_notes = list( Description = 'Notes about EAH taste sample prep'),
    hershey_post_notes = list( Description = 'Notes about Hershey Kiss'),
    starburst_post_notes = list( Description = 'Notes about Starbursts'),
    oreos_post_notes = list( Description = 'Notes about Oreos'),
    popcorn_post_notes = list( Description = 'Notes about popcorn'),
    fritos_post_notes = list( Description = 'Notes about Fritos'),
    pretzel_post_notes = list( Description = 'Notes about pretzels'),
    skittles_post_notes = list( Description = 'Notes about Skittles'),
    brownie_post_notes = list( Description = 'Notes about brownies'),
    icecream_post_notes = list( Description = 'Notes about ice-cream'),
    eah_postweight_notes = list( Description = 'Notes about EAH post-weights')
  )

  # convert formatting to JSON
  intake_json <- RJSONIO::toJSON(intake_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(intake_json, asText = TRUE))){
    print('Intake visit JSON file may be invalid')
  }

  return(intake_json)

}
