#' json_tastetest_long: Generates a json file for the Taste-Test derivative database long-formated file
#'
#' This function generates a json file for the Taste-Test derivative database long-formated file
#'
#' @return A json file documenting the Taste-Test derivative database long-formated file
#'
#'
#' @export

json_tastetest_long <- function() {
  
  tastetest_long_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'The Taste-Test Task has participants rate how much they want to eat a sample of food, consume the food, rate how much they liked the food sample, and then take a sip of water both before and after a meal.',
      DatasetType = 'derivative'),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-baseline' = 'baseline',
                                      'ses-followup' = '1-year follow-up')),
    visit_date = list( Description = 'Date of visit',
                       Unit = 'YYYY-MM-DD'),
    meal_cond = list( Description = 'Meal condition',
                      Levels = list ( 'pre_meal' = 'Before meal/when hungry',
                                      'post_meal' = 'After meal/when sated')),
    meal_mean_want = list( Description = 'Wanting - Meal Foods: mean rating'),
    low_ed_mean_want = list( Description = 'Wanting - Low-ED Food: mean rating'),
    high_ed_mean_want = list( Description = 'Wanting - High-ED Food: mean rating'),
    carrot_want = list( Description = 'Wanting - Carrot: practice rating',
                        Levels = list ( '0' = 'Not At All',
                                        '1' = 'A Little',
                                        '2' = 'A Lot',
                                        '3' = 'Very Much')),
    cknug1_want = list( Description = 'Wanting - Chicken Nugget: sample 1 rating',
                        Levels = list ( '0' = 'Not At All',
                                        '1' = 'A Little',
                                        '2' = 'A Lot',
                                        '3' = 'Very Much')),
    cknug2_want = list( Description = 'Wanting - Chicken Nugget: sample 2 rating',
                        Levels = list ( '0' = 'Not At All',
                                        '1' = 'A Little',
                                        '2' = 'A Lot',
                                        '3' = 'Very Much')),
    cknug3_want = list( Description = 'Wanting - Chicken Nugget: sample 3 rating',
                        Levels = list ( '0' = 'Not At All',
                                        '1' = 'A Little',
                                        '2' = 'A Lot',
                                        '3' = 'Very Much')),
    cknug_mean_want = list( Description = 'Wanting - Chicken Nugget: mean rating'),
    mac1_want = list( Description = 'Wanting - Macarroni and Cheese: sample 1 rating',
                      Levels = list ( '0' = 'Not At All',
                                      '1' = 'A Little',
                                      '2' = 'A Lot',
                                      '3' = 'Very Much')),
    mac2_want = list( Description = 'Wanting - Macarroni and Cheese: sample 2 rating',
                      Levels = list ( '0' = 'Not At All',
                                      '1' = 'A Little',
                                      '2' = 'A Lot',
                                      '3' = 'Very Much')),
    mac3_want = list( Description = 'Wanting - Macarroni and Cheese: sample 3 rating',
                      Levels = list ( '0' = 'Not At All',
                                      '1' = 'A Little',
                                      '2' = 'A Lot',
                                      '3' = 'Very Much')),
    mac_mean_want = list( Description = 'Wanting - Macarroni and Cheese: mean rating'),
    grape1_want = list( Description = 'Wanting - Grapes: sample 1 rating',
                        Levels = list ( '0' = 'Not At All',
                                        '1' = 'A Little',
                                        '2' = 'A Lot',
                                        '3' = 'Very Much')),
    grape2_want = list( Description = 'Wanting - Grapes: sample 2 rating',
                        Levels = list ( '0' = 'Not At All',
                                        '1' = 'A Little',
                                        '2' = 'A Lot',
                                        '3' = 'Very Much')),
    grape3_want = list( Description = 'Wanting - Grapes: sample 3 rating',
                        Levels = list ( '0' = 'Not At All',
                                        '1' = 'A Little',
                                        '2' = 'A Lot',
                                        '3' = 'Very Much')),
    grape_mean_want = list( Description = 'Wanting - Grapes rating'),
    orange_want = list( Description = 'Wanting - Mandarine Orange rating',
                        Levels = list ( '0' = 'Not At All',
                                        '1' = 'A Little',
                                        '2' = 'A Lot',
                                        '3' = 'Very Much')),
    broccoli_want = list( Description = 'Wanting - Broccoli rating',
                          Levels = list ( '0' = 'Not At All',
                                          '1' = 'A Little',
                                          '2' = 'A Lot',
                                          '3' = 'Very Much')),
    gbean_want = list( Description = 'Wanting - Green Bean rating',
                       Levels = list ( '0' = 'Not At All',
                                       '1' = 'A Little',
                                       '2' = 'A Lot',
                                       '3' = 'Very Much')),
    hershey_want = list( Description = 'Wanting - Hershey Kiss rating',
                         Levels = list ( '0' = 'Not At All',
                                         '1' = 'A Little',
                                         '2' = 'A Lot',
                                         '3' = 'Very Much')),
    cracker_want = list( Description = 'Wanting - Cracker rating',
                         Levels = list ( '0' = 'Not At All',
                                         '1' = 'A Little',
                                         '2' = 'A Lot',
                                         '3' = 'Very Much')),
    fruitsnack_want = list( Description = 'Wanting - Fruit Snack rating',
                            Levels = list ( '0' = 'Not At All',
                                            '1' = 'A Little',
                                            '2' = 'A Lot',
                                            '3' = 'Very Much')),
    meal_mean_like = list( Description = 'Liking - Meal Foods: mean rating'),
    low_ed_mean_like = list( Description = 'Liking - Low-ED Food: mean rating'),
    high_ed_mean_like = list( Description = 'Liking - High-ED Food: mean rating'),
    carrot_like = list( Description = 'Liking - Carrot: practice rating',
                        Levels = list ( '0' = 'Very Bad',
                                        '1' = 'Bad',
                                        '2' = 'Good',
                                        '3' = 'Very Good')),
    cknug1_like = list( Description = 'Liking - Chicken Nugget: sample 1 rating',
                        Levels = list ( '0' = 'Very Bad',
                                        '1' = 'Bad',
                                        '2' = 'Good',
                                        '3' = 'Very Good')),
    cknug2_like = list( Description = 'Liking - Chicken Nugget: sample 2 rating',
                        Levels = list ( '0' = 'Very Bad',
                                        '1' = 'Bad',
                                        '2' = 'Good',
                                        '3' = 'Very Good')),
    cknug3_like = list( Description = 'Liking - Chicken Nugget: sample 3 rating',
                        Levels = list ( '0' = 'Very Bad',
                                        '1' = 'Bad',
                                        '2' = 'Good',
                                        '3' = 'Very Good')),
    cknug_mean_like = list( Description = 'Liking - Chicken Nugget: mean rating'),
    mac1_like = list( Description = 'Liking - Macarroni and Cheese: sample 1 rating',
                      Levels = list ( '0' = 'Very Bad',
                                      '1' = 'Bad',
                                      '2' = 'Good',
                                      '3' = 'Very Good')),
    mac2_like = list( Description = 'Liking - Macarroni and Cheese: sample 2 rating',
                      Levels = list ( '0' = 'Very Bad',
                                      '1' = 'Bad',
                                      '2' = 'Good',
                                      '3' = 'Very Good')),
    mac3_like = list( Description = 'Liking - Macarroni and Cheese: sample 3 rating',
                      Levels = list ( '0' = 'Very Bad',
                                      '1' = 'Bad',
                                      '2' = 'Good',
                                      '3' = 'Very Good')),
    mac_mean_like = list( Description = 'Liking - Macarroni and Cheese: mean rating'),
    grape1_like = list( Description = 'Liking - Grapes: sample 1 rating',
                        Levels = list ( '0' = 'Very Bad',
                                        '1' = 'Bad',
                                        '2' = 'Good',
                                        '3' = 'Very Good')),
    grape2_like = list( Description = 'Liking - Grapes: sample 2 rating',
                        Levels = list ( '0' = 'Very Bad',
                                        '1' = 'Bad',
                                        '2' = 'Good',
                                        '3' = 'Very Good')),
    grape3_like = list( Description = 'Liking - Grapes: sample 3 rating',
                        Levels = list ( '0' = 'Very Bad',
                                        '1' = 'Bad',
                                        '2' = 'Good',
                                        '3' = 'Very Good')),
    grape_mean_like = list( Description = 'Liking - Grapes rating'),
    orange_like = list( Description = 'Liking - Mandarine Orange rating',
                        Levels = list ( '0' = 'Very Bad',
                                        '1' = 'Bad',
                                        '2' = 'Good',
                                        '3' = 'Very Good')),
    broccoli_like = list( Description = 'Liking - Broccoli rating',
                          Levels = list ( '0' = 'Very Bad',
                                          '1' = 'Bad',
                                          '2' = 'Good',
                                          '3' = 'Very Good')),
    gbean_like = list( Description = 'Liking - Green Bean rating',
                       Levels = list ( '0' = 'Very Bad',
                                       '1' = 'Bad',
                                       '2' = 'Good',
                                       '3' = 'Very Good')),
    hershey_like = list( Description = 'Liking - Hershey Kiss rating',
                         Levels = list ( '0' = 'Very Bad',
                                         '1' = 'Bad',
                                         '2' = 'Good',
                                         '3' = 'Very Good')),
    cracker_like = list( Description = 'Liking - Cracker rating',
                         Levels = list ( '0' = 'Very Bad',
                                         '1' = 'Bad',
                                         '2' = 'Good',
                                         '3' = 'Very Good')),
    fruitsnack_like = list( Description = 'Liking - Fruit Snack rating',
                            Levels = list ( '0' = 'Very Bad',
                                            '1' = 'Bad',
                                            '2' = 'Good',
                                            '3' = 'Very Good'))
    
    )
  
  # convert formatting to JSON
  tastetest_long_json <- RJSONIO::toJSON(tastetest_long_list, pretty = TRUE)
  
  # double check
  if (isFALSE(RJSONIO::isValidJSON(tastetest_long_json, asText = TRUE))){
    print('tastetest_long JSON file may be invalid')
  }
  
  return(tastetest_long_json)
  
}