#' json_ffq_helix: Generates a json file for the HELIX study Food Frequency Questionnaire
#'
#' This function generates a json file for the scored HELIX study Food Frequency Questionnaire and raw participant responses. This function provides accurate json files ONLY if data is processed using score_ffq_helix function in dataprepr and is only accurate for data collected in Study BRAKE.
#'
#' @return A json file documenting the raw inputs and scored values for the HELIX study Food Frequency Questionnaire
#'
#'
#' @export

json_ffq_helix <- function() {
  
  ffq_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'HELIX study Food Frequency Questionnaire',
      Reference = 'Maitre L, De Bont J, Casas M, et al. Human Early Life Exposome (HELIX) study: a European population-based exposome cohort. BMJ Open. 2018;8(9):e021311. doi:10.1136/bmjopen-2017-021311', 
      TermURL = 'https://pubmed.ncbi.nlm.nih.gov/30206078/'),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-baseline' = 'baseline',
                                      'ses-followup' = '1-year follow-up')),
    visit_protocol = list( Description = 'child visit protocol number (does not necessarilty reflect visit order. See participants.tsv for child visit protocol dates)',
                           Levels = list ('1' =	'Child visit protocol 1 (baseline)',
                                          '2' =	'Child visit protocol 2 (baseline)',
                                          '3'	= 'Child visit protocol 3 (follow-up')),
    ffq_dairy1 = list( Description = 'Milk (skimmed, semi-skimmed, full fat milk) - 1 glass or unit',
                 Levels = list ('0' = 'Never (coversion: 0/wk)',
                                '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                '3' = '1 time per week (coversion: 1 servings/wk)',
                                '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                '6' = '1 time per day (coversion: 7 servings/wk)',
                                '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_dairy2 = list( Description = 'Yogurt (excuding pro-biotic) - 1 glass or pot',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_dairy3 = list( Description = 'Pro-biotic Yogurt (e.g., actimel, keffir) - 1 glass or pot',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_dairy4 = list( Description = 'Cheese (e.g., American, cheddar, brie, feta, cured cheese, brown cheese, curd, cream cheese) - 1 slice or portion',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_egg1 = list( Description = 'Egg (fried, scrambled, boiled, omelette, etc) - 1 egg',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_meat1 = list( Description = 'Poultry (chicken, turkey) - 1 leg,1 burger, 2 nuggets, small curry',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_meat2 = list( Description = 'Red meat (beef, pork, lamb) - e.g., 1 small steak, 1 burger, 1 chop, 2 meat balls, small curry, 1 meat dumpling, minced meat',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_meat3 = list( Description = 'Sausages, bacon, chorizo, salami - 1 small portion',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_meat4 = list( Description = 'Ham - 2 slices',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_fish1 = list( Description = 'Lean/white fish (flat fish, perch, fish cakes) - 1 small serving size',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_fish2 = list( Description = 'Fatty/oily fish (sardines, salmon, mackerel, tuna, trout, carp) - 1 small serving size',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_fish3 = list( Description = 'Canned fish (tuna, sardines, sprat) - 1/2 small can',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_fish4 = list( Description = 'Seafood (shellfish, squid, shrimps) - 1 small serving size',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_dairy5 = list( Description = 'Dairy desert / milky pudding, ice cream -1 portion',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_veg1 = list( Description = 'Raw vegetables (lettuce, tomato, onion, pepper, carrot, cucumber, etc) - 1 small salad dish',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_veg2 = list( Description = 'Cooked or pureed vegetables (pumpkin, aubergine, green beans, spinach, carrots, cabbage, broccoli, cauliflower, tomato sauce, okra, etc) - 1 small dish (including in curry)',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_potato1 = list( Description = 'Potatoes (boiled, baked, mashed) - 1 portion (not chips/fries)',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_legume1 = list( Description = 'Legumes (chickpeas, lentils, beans, peas) - 1 small dish (including in curry)',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_potato2 = list( Description = 'French fries - 1 portion',
                        Levels = list ('0' = 'Never (coversion: 0/wk)',
                                       '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                       '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                       '3' = '1 time per week (coversion: 1 servings/wk)',
                                       '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                       '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                       '6' = '1 time per day (coversion: 7 servings/wk)',
                                       '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                       '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_fruit1 = list( Description = 'Fruits (orange, kiwi, mandarines, pears, apples, bananas, berries, melon etc peaches purees/canned fruit without added sugar ) - 1 fruit or handful berries',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_fruit2 = list( Description = 'Natural/pure/freshly squeezed fruit juice - 1 glass',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_nuts1 = list( Description = 'Nuts (almonds, walnuts, etc) - 1 hand full',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_fruit3 = list( Description = 'Canned fruit with syrup / nectars - 1 small bowl',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_fruit4 = list( Description = 'Dried fruit (raisins, currant, dry apricots, prunes, dried figs) - 1 hand full',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_cereal1 = list( Description = 'White bread - 1 slice of bread, 1 roll, 1 chapatti',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_cereal2 = list( Description = 'Whole-grain / dark bread / \'50/50\' - 1 slice of bread, 1 roll, 1 chapatti',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_cereal3 = list( Description = 'Sugar-sweetened cereals for children - 3 tbs',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_cereal4 = list( Description = 'Other Breakfast cereals / porridge - 3 tbs',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_cereal5 = list( Description = 'Rice and pasta - 1 small dish',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_cereal6 = list( Description = 'Crispy bread, rice cakes, and corn cakes - 2 units',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_bakery1 = list( Description = 'Plain biscuits and cookies - 2 unitse',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_bakery2 = list( Description = 'Buns, cakes, pastries, croissant, donuts, halva - 1 unit',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_sweet1 = list( Description = 'Chocolate (bars, bonbon, spreads, cacao) - 1 unit',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_sweet2 = list( Description = 'Sugar, honey, jam- 1 tsp',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_sweet3 = list( Description = 'Sweets, gummy bears - 1 handful',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_bev1 = list( Description = 'Sugar-sweetened soft/fizzy drinks (e.g., Coca Cola, Mountain Dew, Fanta) - 1 can',
                  Levels = list ('0' = 'Never (coversion: 0/wk)',
                                 '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                 '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                 '3' = '1 time per week (coversion: 1 servings/wk)',
                                 '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                 '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                 '6' = '1 time per day (coversion: 7 servings/wk)',
                                 '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                 '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_bev2 = list( Description = 'Artificially sweetened/ low sugar/ sugar free soft drinks (diet soda) - 1 can',
                     Levels = list ('0' = 'Never (coversion: 0/wk)',
                                    '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                    '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                    '3' = '1 time per week (coversion: 1 servings/wk)',
                                    '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                    '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                    '6' = '1 time per day (coversion: 7 servings/wk)',
                                    '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                    '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_fats1 = list( Description = 'Olive oil, for cooking or seasoning - 1 tbsp',
                      Levels = list ('0' = 'Never (coversion: 0/wk)',
                                     '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                     '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                     '3' = '1 time per week (coversion: 1 servings/wk)',
                                     '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                     '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                     '6' = '1 time per day (coversion: 7 servings/wk)',
                                     '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                     '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_fats2 = list( Description = 'Other vegetable oils (e.g. canola oil) for cooking or seasoning - 1 tbsp',
                      Levels = list ('0' = 'Never (coversion: 0/wk)',
                                     '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                     '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                     '3' = '1 time per week (coversion: 1 servings/wk)',
                                     '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                     '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                     '6' = '1 time per day (coversion: 7 servings/wk)',
                                     '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                     '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_fats3 = list( Description = 'Butter or ghee - 1 tsp',
                      Levels = list ('0' = 'Never (coversion: 0/wk)',
                                     '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                     '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                     '3' = '1 time per week (coversion: 1 servings/wk)',
                                     '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                     '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                     '6' = '1 time per day (coversion: 7 servings/wk)',
                                     '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                     '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_fats4 = list( Description = 'Margarine - 1 tsp',
                      Levels = list ('0' = 'Never (coversion: 0/wk)',
                                     '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                     '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                     '3' = '1 time per week (coversion: 1 servings/wk)',
                                     '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                     '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                     '6' = '1 time per day (coversion: 7 servings/wk)',
                                     '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                     '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_dressing1 = list( Description = 'Mayonaise, ketchup, dressing - 1 tbsp',
                          Levels = list ('0' = 'Never (coversion: 0/wk)',
                                         '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                         '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                         '3' = '1 time per week (coversion: 1 servings/wk)',
                                         '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                         '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                         '6' = '1 time per day (coversion: 7 servings/wk)',
                                         '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                         '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    ffq_saltysnack1 = list( Description = 'Chips, salty snacks, sunflower seeds - 1 small bag or bowl',
                            Levels = list ('0' = 'Never (coversion: 0/wk)',
                                           '1' = 'Less than once per month (coversion: 0.25 servings/wk)',
                                           '2' = '1-3 times per month (coversion: 0.5 servings/wk)',
                                           '3' = '1 time per week (coversion: 1 servings/wk)',
                                           '4' = '2-4 times per week (coversion: 3 servings/wk)',
                                           '5' = '5-6 times per week (coversion: 5.5 servings/wk)',
                                           '6' = '1 time per day (coversion: 7 servings/wk)',
                                           '7' = '2-3 times per day (coversion: 17.5 servings/wk)',
                                           '8' = '5-6 times per day (coversion: 28 servings/wk)')),
    dairy = list( Description = 'Dairy servings per week', 
                     Derivative = TRUE),
    eggs = list( Description = 'Egg servings per week', 
                     Derivative = TRUE),
    meat = list( Description = 'Meat servings per week', 
                     Derivative = TRUE),
    fish = list( Description = 'Fish servings per week', 
                     Derivative = TRUE),
    nuts = list( Description = ' Nuts servings per week', 
                     Derivative = TRUE),
    vegetables = list( Description = 'Vegetable servings per week', 
                     Derivative = TRUE),
    pulses = list( Description = 'Pulses servings per week', 
                       Derivative = TRUE),
    fruit = list( Description = 'Fruit servings per week', 
                       Derivative = TRUE),
    potatoes = list( Description = 'Potato servings per week', 
                       Derivative = TRUE),
    breads_cereals = list( Description = 'Bread/cereal servings per week', 
                       Derivative = TRUE),
    beverages = list( Description = 'Beverage (non-milk and water) servings per week', 
                       Derivative = TRUE),
    sweet_bakery = list( Description = 'Sweet bakery servings per week', 
                       Derivative = TRUE),
    salty_snacks = list( Description = 'Saly snacks servings per week', 
                       Derivative = TRUE),
    added_fats = list( Description = 'Added fats servings per week', 
                       Derivative = TRUE),
    dressings = list( Description = 'Dressings servings per week', 
                       Derivative = TRUE),
    animal = list( Description = 'Animal-based servings per week', 
                      Derivative = TRUE),
    plants = list( Description = 'Plant-base food servings per week', 
                      Derivative = TRUE),
    upf = list( Description = '\'Ultra-processed food\' servings per week', 
                      Derivative = TRUE),
    not_upf = list( Description = 'Non-\'Ultra-processed food\' servings per week', 
                      Derivative = TRUE),
    prop_upf = list( Description = 'Proportion of \'Ultra-processed food\' servings per week relative to other food servings per week', 
                    Derivative = TRUE),
    ffq_suplements = list( Description = 'Has your child used nutritional supplements during last year? (e.g., vitamins)',
                            Levels = list ('0' = 'No',
                                           '1' = 'Yes')),
    ffq_multivit = list( Description = 'Did your child use Multivitamin supplements?',
                           Levels = list ('0' = 'No',
                                          '1' = 'Yes')),
    ffq_multivit_brand = list( Description = 'Do you remember the brand?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    ffq_multivit_brandname = list( Description = 'Brand:'),
    ffq_multivit_current = list( Description = 'Is your child currently taking this multivitamin supplement?',
                               Levels = list ('0' = 'No',
                                              '1' = 'Yes')),
    ffq_multivit_freq = list( Description = 'When your child is regularly taking this multivitamin supplement, how many times do they take it per week?'),
    ffq_minerals = list( Description = 'Did your child use mineral supplements?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    ffq_mineral_brand = list( Description = 'Do you remember the brand?',
                               Levels = list ('0' = 'No',
                                              '1' = 'Yes')),
    ffq_mineral_brandname = list( Description = 'Brand:'),
    ffq_mineral_current = list( Description = 'Is your child currently taking this mineral supplement?',
                                 Levels = list ('0' = 'No',
                                                '1' = 'Yes')),
    ffq_mineral_freq = list( Description = 'When your child is regularly taking this mineral supplement, how many times do they take it per week?'),
    ffq_vitd = list( Description = 'Did your child use Vitamin D supplements?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    ffq_vitd_brand = list( Description = 'Do you remember the brand?',
                              Levels = list ('0' = 'No',
                                             '1' = 'Yes')),
    ffq_vitd_brandname = list( Description = 'Brand:'),
    ffq_vitd_current = list( Description = 'Is your child currently taking this Vitamin D supplement?',
                                Levels = list ('0' = 'No',
                                               '1' = 'Yes')),
    ffq_vitd_freq = list( Description = 'When your child is regularly taking this Vitamin D supplement, how many times do they take it per week?'),
    ffq_omega3 = list( Description = 'Did your child use Omega-3 fatty acid supplements?',
                     Levels = list ('0' = 'No',
                                    '1' = 'Yes')),
    ffq_omega3_brand = list( Description = 'Do you remember the brand?',
                           Levels = list ('0' = 'No',
                                          '1' = 'Yes')),
    ffq_omega3_brandname = list( Description = 'Brand:'),
    ffq_omega3_current = list( Description = 'Is your child currently taking this Omega-3 fatty acid supplement?',
                             Levels = list ('0' = 'No',
                                            '1' = 'Yes')),
    ffq_omega3_freq = list( Description = 'When your child is regularly taking this Omega-3 fatty acid supplement, how many times do they take it per week?'),
    ffq_sup_other = list( Description = 'Is your child currently using any other supplements?',
                       Levels = list ('0' = 'No',
                                      '1' = 'Yes')),
    ffq_sup_other_list = list( Description = 'Please list the other supplements used')
    )
  
  # convert formatting to JSON
  ffq_json <- RJSONIO::toJSON(ffq_list, pretty = TRUE)
  
  # double check
  if (isFALSE(RJSONIO::isValidJSON(ffq_json, asText = TRUE))){
    print('ffq JSON file may be invalid')
  }
  
  return(ffq_json)
  
}