#' json_nonwear: Generates a json file for the Non-Wear logs for baseline actigraphy - NOTE: we did not use at follow-up due to low return/completion
#'
#' This function generates a json file for the Non-Wear logs for baseline actigraphy
#'
#' @return A string with data stored in JSON format containing meta-data for the Non-Wear logs for baseline actigraphy
#'
#'
#' @export

json_nonwear <- function() {

  nonwear_list <- list(
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-baseline' = 'baseline',
                                      'ses-followup' = '1-year follow-up')),
    nonwear_return = list( Description = 'Actigraph non-wear log returned'),
    nonwear1_date = list( Description = 'Date child removed the actigraph watch',
                       Unit = 'YYYY-MM-DD'),
    nonwear1_date2 = list( Description = 'Date child put the actigraph watch back on',
                          Unit = 'YYYY-MM-DD'),
    nonwear1_timeoff = list( Description = 'Time child removed the actigraph watch',
                             Unit = 'H:M'),
    nonwear1_timeon = list( Description = 'Time child put the actigraph watch back on',
                             Unit = 'H:M'),
    nonwear2_date = list( Description = 'Date child removed the actigraph watch',
                          Unit = 'YYYY-MM-DD'),
    nonwear2_date2 = list( Description = 'Date child put the actigraph watch back on',
                           Unit = 'YYYY-MM-DD'),
    nonwear2_timeoff = list( Description = 'Time child removed the actigraph watch',
                             Unit = 'H:M'),
    nonwear2_timeon = list( Description = 'Time child put the actigraph watch back on',
                            Unit = 'H:M'),
    nonwear3_date = list( Description = 'Date child removed the actigraph watch',
                          Unit = 'YYYY-MM-DD'),
    nonwear3_date2 = list( Description = 'Date child put the actigraph watch back on',
                           Unit = 'YYYY-MM-DD'),
    nonwear3_timeoff = list( Description = 'Time child removed the actigraph watch',
                             Unit = 'H:M'),
    nonwear3_timeon = list( Description = 'Time child put the actigraph watch back on',
                            Unit = 'H:M'),
    nonwear4_date = list( Description = 'Date child removed the actigraph watch',
                          Unit = 'YYYY-MM-DD'),
    nonwear4_date2 = list( Description = 'Date child put the actigraph watch back on',
                           Unit = 'YYYY-MM-DD'),
    nonwear4_timeoff = list( Description = 'Time child removed the actigraph watch',
                             Unit = 'H:M'),
    nonwear4_timeon = list( Description = 'Time child put the actigraph watch back on',
                            Unit = 'H:M'),
    nonwear5_date = list( Description = 'Date child removed the actigraph watch',
                          Unit = 'YYYY-MM-DD'),
    nonwear5_date2 = list( Description = 'Date child put the actigraph watch back on',
                           Unit = 'YYYY-MM-DD'),
    nonwear5_timeoff = list( Description = 'Time child removed the actigraph watch',
                             Unit = 'H:M'),
    nonwear5_timeon = list( Description = 'Time child put the actigraph watch back on',
                            Unit = 'H:M'),
    nonwear6_date = list( Description = 'Date child removed the actigraph watch',
                          Unit = 'YYYY-MM-DD'),
    nonwear6_date2 = list( Description = 'Date child put the actigraph watch back on',
                           Unit = 'YYYY-MM-DD'),
    nonwear6_timeoff = list( Description = 'Time child removed the actigraph watch',
                             Unit = 'H:M'),
    nonwear6_timeon = list( Description = 'Time child put the actigraph watch back on',
                            Unit = 'H:M'),
    nonwear7_date = list( Description = 'Date child removed the actigraph watch',
                          Unit = 'YYYY-MM-DD'),
    nonwear7_date2 = list( Description = 'Date child put the actigraph watch back on',
                           Unit = 'YYYY-MM-DD'),
    nonwear7_timeoff = list( Description = 'Time child removed the actigraph watch',
                             Unit = 'H:M'),
    nonwear7_timeon = list( Description = 'Time child put the actigraph watch back on',
                            Unit = 'H:M'),
    nonwear8_date = list( Description = 'Date child removed the actigraph watch',
                          Unit = 'YYYY-MM-DD'),
    nonwear8_date2 = list( Description = 'Date child put the actigraph watch back on',
                           Unit = 'YYYY-MM-DD'),
    nonwear8_timeoff = list( Description = 'Time child removed the actigraph watch',
                             Unit = 'H:M'),
    nonwear8_timeon = list( Description = 'Time child put the actigraph watch back on',
                            Unit = 'H:M'),
    nonwear9_date = list( Description = 'Date child removed the actigraph watch',
                          Unit = 'YYYY-MM-DD'),
    nonwear9_date2 = list( Description = 'Date child put the actigraph watch back on',
                           Unit = 'YYYY-MM-DD'),
    nonwear9_timeoff = list( Description = 'Time child removed the actigraph watch',
                             Unit = 'H:M'),
    nonwear9_timeon = list( Description = 'Time child put the actigraph watch back on',
                            Unit = 'H:M'),
    nonwear10_date = list( Description = 'Date child removed the actigraph watch',
                          Unit = 'YYYY-MM-DD'),
    nonwear10_date2 = list( Description = 'Date child put the actigraph watch back on',
                           Unit = 'YYYY-MM-DD'),
    nonwear10_timeoff = list( Description = 'Time child removed the actigraph watch',
                             Unit = 'H:M'),
    nonwear10_timeon = list( Description = 'Time child put the actigraph watch back on',
                            Unit = 'H:M'),
    nonwear11_date = list( Description = 'Date child removed the actigraph watch',
                          Unit = 'YYYY-MM-DD'),
    nonwear11_date2 = list( Description = 'Date child put the actigraph watch back on',
                           Unit = 'YYYY-MM-DD'),
    nonwear11_timeoff = list( Description = 'Time child removed the actigraph watch',
                             Unit = 'H:M'),
    nonwear11_timeon = list( Description = 'Time child put the actigraph watch back on',
                            Unit = 'H:M'),
    nonwear12_date = list( Description = 'Date child removed the actigraph watch',
                          Unit = 'YYYY-MM-DD'),
    nonwear12_date2 = list( Description = 'Date child put the actigraph watch back on',
                           Unit = 'YYYY-MM-DD'),
    nonwear12_timeoff = list( Description = 'Time child removed the actigraph watch',
                             Unit = 'H:M'),
    nonwear12_timeon = list( Description = 'Time child put the actigraph watch back on',
                            Unit = 'H:M'),
    nonwear13_date = list( Description = 'Date child removed the actigraph watch',
                          Unit = 'YYYY-MM-DD'),
    nonwear13_date2 = list( Description = 'Date child put the actigraph watch back on',
                           Unit = 'YYYY-MM-DD'),
    nonwear13_timeoff = list( Description = 'Time child removed the actigraph watch',
                             Unit = 'H:M'),
    nonwear13_timeon = list( Description = 'Time child put the actigraph watch back on',
                            Unit = 'H:M'),
    nonwear14_date = list( Description = 'Date child removed the actigraph watch',
                          Unit = 'YYYY-MM-DD'),
    nonwear14_date2 = list( Description = 'Date child put the actigraph watch back on',
                           Unit = 'YYYY-MM-DD'),
    nonwear14_timeoff = list( Description = 'Time child removed the actigraph watch',
                             Unit = 'H:M'),
    nonwear14_timeon = list( Description = 'Time child put the actigraph watch back on',
                            Unit = 'H:M'),
    nonwear15_date = list( Description = 'Date child removed the actigraph watch',
                          Unit = 'YYYY-MM-DD'),
    nonwear15_date2 = list( Description = 'Date child put the actigraph watch back on',
                           Unit = 'YYYY-MM-DD'),
    nonwear15_timeoff = list( Description = 'Time child removed the actigraph watch',
                             Unit = 'H:M'),
    nonwear15_timeon = list( Description = 'Time child put the actigraph watch back on',
                            Unit = 'H:M'))

  # convert formatting to JSON
  nonwear_json <- RJSONIO::toJSON(nonwear_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(nonwear_json, asText = TRUE))){
    print('nonwear JSON file may be invalid')
  }

  return(nonwear_json)

}
