#' json_household: Generates a json file for the household demographic questionnaire
#'
#' This function provides a json file for household demographic questionnaire collected in Study REACH
#'
#' @return A string with data stored in JSON format containing meta-data for the household demographic questionnaire
#'
#'
#' @export

json_household <- function() {

  household_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'A collection of items to assess parent demographics and household environment. This questionnaire was developed within the Keller Lab for Study REACH. Participants were provided the following instructions: "Please answer the following questions:"'),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-baseline' = 'baseline',
                                      'ses-followup' = '1-year follow-up')),
    visit_date = list( Description = 'Date of visit',
                       Unit = 'YYYY-MM-DD'),
    demo_relationship = list( Description = 'What is your relationship to the child in the study?',
                                    Levels = list ('0' = 'Biological mother',
                                                   '1' = 'Biological father',
                                                   '2' = 'Non-biological mother',
                                                   '3' = 'Non-biological father',
                                                   '4' = 'Other')),
    demo_nchildren = list( Description = 'How many children do you have? (Enter a number)'),
    demo_birth_order = list( Description = 'What is the birth number of the child in the study (E.g. If the child is first born, enter 1)'),
    demo_child_grade = list( Description = 'What is your child\'s current grade? For summer break, please select the grade your child just completed.',
                           Levels = list ('0' = 'Kindergarten',
                                          '1' = '1st grade',
                                          '2' = '2nd grade',
                                          '3' = '3rd grade',
                                          '4' = '4th grade',
                                          '5' = '5th grade',
                                          '6' = '6th grade')),
    demo_parent_ethnicity = list( Description = 'What is your ethnicity?',
                                  Levels = list ('0' = 'Hispanic or Latino',
                                                 '1' = 'Not Hispanic or Latino')),
    demo_parent_race = list( Description = 'What is your race?',
                             Levels = list ('0' = 'American Indian/Alaskan Native',
                                            '1' = 'Asian',
                                            '2' = 'Black or African American',
                                            '3' = 'White',
                                            '4' = 'Hawaiian/Pacific Islander',
                                            '5' = 'Other')),
    demo_parent_other_race = list( Description = 'Other race (please state):'),
    demo_partner = list( Description = 'Do you have a spouse, partner, or significant other?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    demo_parents_together = list( Description = 'Does your spouse, partner, or significant other currently reside in your child\'s primary household?'),
    demo_partner_relationship = list( Description = 'What is your spouse, partner, or significant other\'s relationship to the child?',
                                      Levels = list ('0' = 'Biological mother',
                                                     '1' = 'Biological father',
                                                     '2' = 'Non-biological mother',
                                                     '3' = 'Non-biological father',
                                                     '4' = 'Other')),
    demo_partner_relationship_other = list( Description = 'Please specify other relationship with child:'),
    demo_marital_status = list( Description = 'What is your marital status?',
                                Levels = list ('0' = 'Married',
                                               '1' = 'Single (never married)',
                                               '2' = 'Widowed',
                                               '3' = 'Divorced',
                                               '4' = 'Separated',
                                               '5' = 'Remarried',
                                               '6' = 'Living together, not married')),
    demo_income = list( Description = 'Including ALL sources (such as social security income, child support payments, government assistance, dividends from investments, etc.) what was your household\'s combined yearly income last year BEFORE taxes?',
                        Levels = list ('0' = 'Less than $20,000',
                                       '1' = '$21,000 - $35,000',
                                       '2' = '$36,000 - $50,000',
                                       '3' = '$51,000 - $75,000',
                                       '4' = '$76,000 - $100,000',
                                       '5' = '$100,000 +')),
    demo_mom_ed = list( Description = 'What is the child\'s biological mother\'s highest level of formal education?'),
    demo_ded_ed = list( Description = 'What is the child\'s biological father\'s highest level of formal education?'),
    demo_education_partner = list( Description = 'What is your partner\'s highest level of formal education?'),
    demo_employed = list( Description = 'Are you currently employed?',
                          Levels = list ('0' = 'No',
                                         '1' = 'Yes')),
    demo_workhours = list( Description = 'How many hours per week are you at work (not traveling to and from)?'),
    demo_retired = list( Description = 'Are you currently retired?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    demo_partner_employment = list( Description = 'Is your spouse, partner, or significant other currently employed?'),
    demo_partner_workhours = list( Description = 'How many hours per week is your spouse, partner, or significant other at work (not traveling to and from)?'),
    demo_partner_retired = list( Description = 'Is your spouse, partner, or significant other currently retired?',
                                 Levels = list ('0' = 'No',
                                                '1' = 'Yes')),
    demo_parent2_rep_height_ft = list( Description = 'What is your child\'s biological parent\'s height who was not measured or present at today\'s visit (Feet):', 
                                       Unit = 'feet'),
    demo_parent2_rep_height_in = list( Description = 'What is your child\'s biological parent\'s height who was not measured or present at today\'s visit (Inches):', 
                                       Unit = 'inches'),
    demo_parent2_rep_weight_lbs = list( Description = 'What is the weight, in pounds, of your child\'s biological parent who is not present at todays visit?', 
                                        Unit = 'pounds'),
    demo_feeding_child = list( Description = 'Who is primarily responsible for feeding your child?',
                               Levels = list ('0' = 'You',
                                              '1' = 'Your partner',
                                              '2' = 'Both',
                                              '3' = 'School',
                                              '4' = 'Other')),
    demo_buys_food = list( Description = 'Who is primarily responsible for buying food in your household?',
                           Levels = list ('0' = 'You',
                                          '1' = 'Your partner',
                                          '2' = 'Both',
                                          '3' = 'Other')),
    demo_eat_out = list( Description = 'On average, how frequently does your family eat out or get delivery/take out for dinner?',
                         Levels = list ('0' = 'Once a month or less',
                                        '1' = 'Twice a month',
                                        '2' = 'Once a week',
                                        '3' = 'Two times a week',
                                        '4' = 'Three times a week',
                                        '5' = 'Four or more times a week')),
    demo_dinner_together = list( Description = 'On average, how many nights a week does your family eat dinner together as a group (with most family members present)?'),
    demo_prepared_lunch = list( Description = 'On average, how many times per week does your child eat lunch that he/she brings from home?'),
    demo_food_condition = list( Description = 'Does anyone in your household have a condition that affects the food they eat?',
                                Levels = list ('0' = 'No',
                                               '1' = 'Yes')),
    demo_assist_program_no = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: I have not used assistance programs',
                                   Levels = list ('0' = 'No',
                                                  '1' = 'Yes')),
    demo_assist_program_snap = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: SNAP (food stamps)',
                                     Levels = list ('0' = 'No',
                                                    '1' = 'Yes')),
    demo_assist_program_wic = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: WIC',
                                    Levels = list ('0' = 'No',
                                                   '1' = 'Yes')),
    demo_assist_program_tnaf = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: TNAF (cash assistance)',
                                     Levels = list ('0' = 'No',
                                                    '1' = 'Yes')),
    demo_assist_program_medicaid = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: Medicaid (Medical assistance)',
                                         Levels = list ('0' = 'No',
                                                        '1' = 'Yes')),
    demo_assist_program_liheap = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: LIHEAP (Home energy assistance)',
                                       Levels = list ('0' = 'No',
                                                      '1' = 'Yes')),
    demo_assist_program_pfr_lunch = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: Partial Free/Reduced School Meal Program (only some meals)',
                                          Levels = list ('0' = 'No',
                                                         '1' = 'Yes')),
    demo_assist_program_fr_lunch = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: Full Free/Reduced School Meal Programs',
                                   Levels = list ('0' = 'No',
                                                  '1' = 'Yes')),
    demo_assist_program_other = list( Description = 'Have you or anyone in your household used any of the following programs in the past 12 months?: Other assistance programs',
                                      Levels = list ('0' = 'No',
                                                     '1' = 'Yes')),
    demo_programs_other = list( Description = 'Other assistance programs (please state):'),
    demo_food_pantry = list( Description = 'Have you ever received food from a food pantry or soup kitchen?',
                             Levels = list ('0' = 'No',
                                            '1' = 'Yes')),
    demo_foodpantry_times = list( Description = 'How many times have you received food from a food pantry or soup kitchen in the past 12 months?'),
    demo_food_costs = list( Description = 'In a typical month, how much money do you spend on food for your household, including food you buy at any stores and restaurants?',
                            Levels = list ('0' = 'Less than $100 a month',
                                           '1' = '$100 - $200 a month',
                                           '2' = '$200 - $300 a month',
                                           '3' = '$300 - $400 a month',
                                           '4' = '$400 - $500 a month',
                                           '5' = 'More than $500 a month')),
    demo_parent_age = list( Description = 'Age of parent calculated from self-reported parent date of birth (data not shared) and date of form completion (data not shared)',
                            Unit = "years",
                            Derivative = TRUE),
    demo_parent2_rep_height_m = list( Description = 'Parent2 (i.e., biological parent not at visit) height calculated from demo_parent2_rep_height_ft and demo_parent2_rep_height_in',
                            Unit = "meters",
                            Derivative = TRUE),
    parent2_rep_weight_kg = list( Description = 'Parent2 (i.e., biological parent not at visit) weight calculated from demo_parent2_rep_height_lbs',
                                      Unit = "kg",
                                      Derivative = TRUE),
    demo_parent2_rep_bmi = list( Description = 'Parent2 (i.e., biological parent not at visit) BMI calculated from parent2_rep_height_m and demo_parent2_rep_weight_lbs',
                            Unit = "kg/m^2",
                            Derivative = TRUE))

  # convert formatting to JSON
  household_json <- RJSONIO::toJSON(household_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(household_json, asText = TRUE))){
    print('household demo JSON file may be invalid')
  }

  return(household_json)

}
