#' json_sleeplog: Generates a json file for the Behavioral Rating Inventory of Executive Function-2
#'
#' This function generates a json file for the scored Behavioral Rating Inventory of Executive Function-2 and raw participant responses. This function provides accurate json files ONLY if data is processed using score_sleeplog function in dataprepr and is only accurate for data collected in Study BRAKE.
#'
#' @return A json file documenting the raw inputs and scored values for the Behavioral Rating Inventory of Executive Function-2
#'
#'
#' @export

json_sleeplog <- function() {
  
  sleeplog_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Home week-long sleep log'),
    participant_id = list( Description = 'participant id number'),
    date_mon = list( Description = 'Monday\'s Date'),
    date_tu = list( Description = 'Tuesday\'s Date'),
    date_wed = list( Description = 'Wednesday\'s Date'),
    date_th = list( Description = 'Thursday\'s Date'),
    date_fri = list( Description = 'Friday\'s Date'),
    date_sat = list( Description = 'Saturday\'s Date'),
    date_sun = list( Description = 'Sunday\'s Date'),
    bedtime_mon = list( Description = 'What time did you go to bed on Monday?'),
    bedtime_tu = list( Description = 'What time did you go to bed on Tuesday?'),
    bedtime_wed = list( Description = 'What time did you go to bed on Wednesday?'),
    bedtime_th = list( Description = 'What time did you go to bed on Thursday?'),
    bedtime_fri = list( Description = 'What time did you go to bed on Fridday?'),
    bedtime_sat = list( Description = 'What time did you go to bed on Saturday?'),
    bedtime_sun = list( Description = 'What time did you go to bed on Sunday?'),
    attempt_mon = list( Description = 'What time did you try to go to sleep on Monday?'),
    attempt_tu = list( Description = 'What time did you try to go to sleep on Tuesday?'),
    attempt_wed = list( Description = 'What time did you try to go to sleep on Wednesday?'),
    attempt_th = list( Description = 'What time did you try to go to sleep on Thursday?'),
    attempt_fri = list( Description = 'What time did you try to go to sleep on Friday?'),
    attempt_sat = list( Description = 'What time did you try to go to sleep on Saturday?'),
    attempt_sun = list( Description = 'What time did you try to go to sleep on Sunday?'),
    asleep_mon = list( Description = 'What time did you fall asleep on Monday?'),
    asleep_tu = list( Description = 'What time did you fall asleep on Tuesday?'),
    asleep_wed = list( Description = 'What time did you fall asleep on Wednesday?'),
    asleep_th = list( Description = 'What time did you fall asleep on Thursday?'),
    asleep_fri = list( Description = 'What time did you fall asleep on Friday?'),
    asleep_sat = list( Description = 'What time did you fall asleep on Saturday?'),
    asleep_sun = list( Description = 'What time did you fall asleep on sunday?'),
    times_mon = list( Description = 'How many times did you wake up during the night on Monday?'),
    times_tu = list( Description = 'How many times did you wake up during the night on Tuesday?'),
    times_wed = list( Description = 'How many times did you wake up during the night on Wednesday?'),
    times_th = list( Description = 'How many times did you wake up during the night on Thursday?'),
    times_fri = list( Description = 'How many times did you wake up during the night on Friday?'),
    times_sat = list( Description = 'How many times did you wake up during the night on Saturday?'),
    times_sun = list( Description = 'How many times did you wake up during the night on Sunday?'),
    waso_mon = list( Description = 'In total, how long did these awakenings last on Monday?'),
    waso_tu = list( Description = 'In total, how long did these awakenings last on Tuesday?'),
    waso_wed = list( Description = 'In total, how long did these awakenings last on Wednesday?'),
    waso_th = list( Description = 'In total, how long did these awakenings last on Thursday?'),
    waso_fri = list( Description = 'In total, how long did these awakenings last on Friday?'),
    waso_sat = list( Description = 'In total, how long did these awakenings last on Saturday?'),
    waso_sun = list( Description = 'In total, how long did these awakenings last on Sunday?'),
    awake_mon = list( Description = 'What time did you wake up from sleep Monday morning?'),
    awake_tu = list( Description = 'What time did you wake up from sleep Tuesday morning?'),
    awake_wed = list( Description = 'What time did you wake up from sleep Wednesday morning?'),
    awake_th = list( Description = 'What time did you wake up from sleep Thursday morning?'),
    awake_fri = list( Description = 'What time did you wake up from sleep Friday morning?'),
    awake_sat = list( Description = 'What time did you wake up from sleep Saturday morning?'),
    awake_sun = list( Description = 'What time did you wake up from sleep Sunday morning?'),
    out_on_mon = list( Description = 'What time did you get out of bed to start your day on Monday?'),
    out_on_tu = list( Description = 'What time did you get out of bed to start your day on Tuesday?'),
    out_on_wed = list( Description = 'What time did you get out of bed to start your day on Wednesday?'),
    out_on_th= list( Description = 'What time did you get out of bed to start your day on Thursday?'),
    out_on_fri = list( Description = 'What time did you get out of bed to start your day on Friday?'),
    out_on_sat = list( Description = 'What time did you get out of bed to start your day on Saturday?'),
    out_on_sun = list( Description = 'What time did you get out of bed to start your day on Sunday?'),
    is_summer = list( Description = 'Does the first date on the sleep log fall within summer holliday (non-school year)',
                    Levels = list ('0' = 'No',
                                   '1' = 'Y'), 
                    Derivative = TRUE),
    bedtime = list( Description = 'Average weekly bedtime',
                    Derivative = TRUE),
    bedtime_wkday = list( Description = 'Average bedtime during workweek',
                          Derivative = TRUE),
    bedtime_wkend = list( Description = 'Average bedtime during weekend',
                          Derivative = TRUE),
    bedtime_range_wkday = list( Description = 'Range in bedtime during workweek', 
                                Units = 'hours',
                                Derivative = TRUE),
    bedtime_range_wkend = list( Description = 'Range in bedtime during weekend', 
                                Units = 'hours',
                                Derivative = TRUE),
    awake = list( Description = 'Average weekly bedtime',
                    Derivative = TRUE),
    awake_wkday = list( Description = 'Average awake time during workweek',
                          Derivative = TRUE),
    awake_wkend = list( Description = 'Average awake time during weekend',
                          Derivative = TRUE),
    awake_range_wkday = list( Description = 'Range in awake time during workweek', 
                                Units = 'hours',
                                Derivative = TRUE),
    awake_range_wkend = list( Description = 'Range in awake time during weekend', 
                                Units = 'hours',
                                Derivative = TRUE),
    sleep_latency = list( Description = 'Average sleep latency (time from attempt to asleep)',
                    Derivative = TRUE),
    sleep_latency_wkday = list( Description = 'Average sleep latency (time from attempt to asleep) during workweek',
                          Derivative = TRUE),
    sleep_latency_wkend = list( Description = 'Average sleep latency (time from attempt to asleep) during weekend',
                          Derivative = TRUE),
    sleep_latency_range_wkday = list( Description = 'Range in sleep latency (time from attempt to asleep) during workweek', 
                                Units = 'hours',
                                Derivative = TRUE),
    sleep_latency_range_wkend = list( Description = 'Range in sleep latency (time from attempt to asleep) during weekend', 
                                Units = 'hours',
                                Derivative = TRUE),
    night_wakings = list( Description = 'Average night wakings',
                    Derivative = TRUE),
    night_wakings_wkday = list( Description = 'Average night wakings during workweek',
                          Derivative = TRUE),
    night_wakings_wkend = list( Description = 'Average night wakings during weekend',
                          Derivative = TRUE),
    night_wakings_range_wkday = list( Description = 'Range in number of night wakings during workweek', 
                                Derivative = TRUE),
    night_wakings_range_wkend = list( Description = 'Range in number of night wakings during weekend',
                                Derivative = TRUE),
    sleep_hrs = list( Description = 'Average hours of sleep per night',
                    Derivative = TRUE),
    sleep_hrs_wkday = list( Description = 'Average hours of sleep per night during workweek',
                          Derivative = TRUE),
    sleep_hrs_wkend = list( Description = 'Average hours of sleep per night during weekend',
                          Derivative = TRUE),
    sleep_hrs_range_wkday = list( Description = 'Range in hours of sleep per night during workweek', 
                                Units = 'hours',
                                Derivative = TRUE),
    sleep_hrs_range_wkend = list( Description = 'Range in hours of sleep per night during weekend', 
                                Units = 'hours',
                                Derivative = TRUE),
    in_bed_hr = list( Description = 'Average hours spent in bed per night',
                    Derivative = TRUE),
    in_bed_wkday = list( Description = 'Average hours spent in bed per night during workweek',
                          Derivative = TRUE),
    in_bed_wkend = list( Description = 'Average hours spent in bed per night during weekend',
                          Derivative = TRUE),
    in_bed_range_wkday = list( Description = 'Range in hours spent in bed per night during workweek', 
                                Units = 'hours',
                                Derivative = TRUE),
    in_bed_range_wkend = list( Description = 'Range in hours spent in bed per night during weekend', 
                                Units = 'hours',
                                Derivative = TRUE))
  

  # convert formatting to JSON
  sleeplog_json <- RJSONIO::toJSON(sleeplog_list, pretty = TRUE)
  
  # double check
  if (isFALSE(RJSONIO::isValidJSON(sleeplog_json, asText = TRUE))){
    print('Sleep Log JSON file may be invalid')
  }
  
  return(sleeplog_json)
  
}