#' json_micro_beh: Generates a json file for micro_beh 
#'
#' This function generates a json file for micro_beh 
#'
#' @return A json file documenting the Study BRAKE's micro_beh 
#'
#'
#' @export

json_micro_beh <- function() {
  
  micro_beh_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Meal microstructure coding following the extablished protocol',
      Reference = 'Pearce, A. L., N. V. Neuwald, J. S. Evans, O. Romano, B. J. Rolls, and K. L. Keller. "Child eating behaviors are consistently linked to intake across meals that vary in portion size." Appetite 196 (2024): 107258. https://doi.org/10.1016/j.appet.2024.107258',
      TermURL = 'https://zenodo.org/records/8140896'),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-baseline' = 'baseline',
                                      'ses-followup' = '1-year follow-up')),
    paradigm = list( Description = 'eating paradigm', 
                     Levels = list ('meal' = 'lab meal',
                                    'eah' = 'eating in the absence of hunger')),
    start_meal_affect_1 = list( Description = 'Coder 1: start of meal affect', 
                                Levels = list ('2' = 'Laughter, clapping, moving hands to show excitement, open mouth smiles, explicit and direct verbal excitement and approval', 
                                               '1' = 'Slight smiles, shaking head yes, verbal suggestion of approval', 
                                               '0' = 'Shows no emotion or reaction to meal start/end. Completely neutral', 
                                               '-1' = 'Frowning, shaking head, looking confused/disgusted, any verbal suggestion of dislike or disapproval', 
                                               '-2' = 'Vigorously shaking head or waving hands to reject food, explicit and direct negative verbal remark')),
    end_meal_affect_1 = list( Description = 'Coder 1: end of meal affect', 
                              Levels = list ('2' = 'Laughter, clapping, moving hands to show excitement, open mouth smiles, explicit and direct verbal excitement and approval', 
                                             '1' = 'Slight smiles, shaking head yes, verbal suggestion of approval', 
                                             '0' = 'Shows no emotion or reaction to meal start/end. Completely neutral', 
                                             '-1' = 'Frowning, shaking head, looking confused/disgusted, any verbal suggestion of dislike or disapproval', 
                                             '-2' = 'Vigorously shaking head or waving hands to reject food, explicit and direct negative verbal remark')),
    bite1_food_1 = list( Description = 'Coder 1: first bite of food'),
    nbites_1 = list( Description = 'Coder 1: number of bites'),
    nsips_1 = list( Description = 'Coder 1: number of sips'),
    meal_dur_1 = list( Description = 'Coder 1: meal duration', 
                       Units = 'min'),
    bite_latency_1 = list( Description = 'Coder 1: time from start of meal to first bite', 
                           Units = 'min'),
    nbeh_distract_1 = list( Description = 'Coder 1: number of distraction behaviors'),
    nswitch_1 = list( Description = 'Coder 1: number of food switches'),
    nswitch_ed_1 = list( Description = 'Coder 1: number of switches between food energy density categories'),
    nswitch_wsip_1 = list( Description = 'Coder 1: number of switched between foods, including water sips'),
    nswitch_wsip_distract_1 = list( Description = 'Coder 1: number of switches between foods, water sips, and distraction beahviors'), 
    bite_rate_1 = list( Description = 'Coder 1: bite rate using meal duration', 
                        Units = 'bites/min'),
    bite_rate_active_1 = list( Description = 'Coder 1: bite rate using active eating time', 
                               Units = 'bites/min'),
    sip_rate_1 = list( Description = 'Coder 1: sip rate using meal duration', 
                       Units = 'sips/min'),
    sip_rate_active_1 = list( Description = 'Coder 1: sip rate using active eating time', 
                              Units = 'sips/min'),
    switch_rate_1 = list( Description = 'Coder 1: food switch rate using meal duration', 
                          Units = 'switch/min'),
    switch_ed_rate_1 = list( Description = 'Coder 1: food energy density category switch rate using meal duration', 
                             Units = 'switch/min'),
    switch_wsip_rate_1 = list( Description = 'Coder 1: switch rate including foods and sips using meal duration', 
                               Units = 'switch/min'),
    eat_rate_kcal_1 = list( Description = 'Coder 1: eating rate in kcal using meal duriation', 
                            Units = 'kcal/min'),
    eat_rate_g_1 = list( Description = 'Coder 1: eating rate in grams using meal duariont', 
                         Units = 'g/min'),
    eat_rate_g_inc_water_1 = list( Description = 'Coder 1: eating rate with water in grams using meal duration', 
                                   Units = 'g/min'),
    eat_rate_active_kcal_1 = list( Description = 'Coder 1: eating rate in kcal using active eating time', 
                                   Units = 'kcal/min'),
    eat_rate_active_g_1 = list( Description = 'Coder 1: eating rate in grams using active eating time', 
                                Units = 'g/min'),
    eat_rate_active_g_inc_water_1 = list( Description = 'Coder 1: eating rate with water in grams using active eating time', 
                                          Units = 'g/min'),
    bite_size_kcal_1 = list( Description = 'Coder 1: bite size in kcal', 
                             Units = 'kcal/bite'),
    bite_size_g_1 = list( Description = 'Coder 1: bite size in grams', 
                          Units = 'g/bite'),
    start_meal_affect_2 = list( Description = 'Coder 2: start of meal affect', 
                                Levels = list ('2' = 'Laughter, clapping, moving hands to show excitement, open mouth smiles, explicit and direct verbal excitement and approval', 
                                               '1' = 'Slight smiles, shaking head yes, verbal suggestion of approval', 
                                               '0' = 'Shows no emotion or reaction to meal start/end. Completely neutral', 
                                               '-1' = 'Frowning, shaking head, looking confused/disgusted, any verbal suggestion of dislike or disapproval', 
                                               '-2' = 'Vigorously shaking head or waving hands to reject food, explicit and direct negative verbal remark')),
    end_meal_affect_2 = list( Description = 'Coder 2: end of meal affect', 
                              Levels = list ('2' = 'Laughter, clapping, moving hands to show excitement, open mouth smiles, explicit and direct verbal excitement and approval', 
                                             '1' = 'Slight smiles, shaking head yes, verbal suggestion of approval', 
                                             '0' = 'Shows no emotion or reaction to meal start/end. Completely neutral', 
                                             '-1' = 'Frowning, shaking head, looking confused/disgusted, any verbal suggestion of dislike or disapproval', 
                                             '-2' = 'Vigorously shaking head or waving hands to reject food, explicit and direct negative verbal remark')),
    bite1_food_2 = list( Description = 'Coder 2: first bite of food'),
    nbites_2 = list( Description = 'Coder 2: number of bites'),
    nsips_2 = list( Description = 'Coder 2: number of sips'),
    meal_dur_2 = list( Description = 'Coder 2: meal duration', 
                       Units = 'min'),
    bite_latency_2 = list( Description = 'Coder 2: time from start of meal to first bite', 
                           Units = 'min'),
    nbeh_distract_2 = list( Description = 'Coder 2: number of distraction behaviors'),
    nswitch_2 = list( Description = 'Coder 2: number of food switches'),
    nswitch_ed_2 = list( Description = 'Coder 2: number of switches between food energy density categories'),
    nswitch_wsip_2 = list( Description = 'Coder 2: number of switched between foods, including water sips'),
    nswitch_wsip_distract_2 = list( Description = 'Coder 2: number of switches between foods, water sips, and distraction beahviors'), 
    bite_rate_2 = list( Description = 'Coder 2: bite rate using meal duration', 
                        Units = 'bites/min'),
    bite_rate_active_2 = list( Description = 'Coder 2: bite rate using active eating time', 
                               Units = 'bites/min'),
    sip_rate_2 = list( Description = 'Coder 2: sip rate using meal duration', 
                       Units = 'sips/min'),
    sip_rate_active_2 = list( Description = 'Coder 2: sip rate using active eating time', 
                              Units = 'sips/min'),
    switch_rate_2 = list( Description = 'Coder 2: food switch rate using meal duration', 
                          Units = 'switch/min'),
    switch_ed_rate_2 = list( Description = 'Coder 2: food energy density category switch rate using meal duration', 
                             Units = 'switch/min'),
    switch_wsip_rate_2 = list( Description = 'Coder 2: switch rate including foods and sips using meal duration', 
                               Units = 'switch/min'),
    eat_rate_kcal_2 = list( Description = 'Coder 2: eating rate in kcal using meal duriation', 
                            Units = 'kcal/min'),
    eat_rate_g_2 = list( Description = 'Coder 2: eating rate in grams using meal duariont', 
                         Units = 'g/min'),
    eat_rate_g_inc_water_2 = list( Description = 'Coder 2: eating rate with water in grams using meal duration', 
                                   Units = 'g/min'),
    eat_rate_active_kcal_2 = list( Description = 'Coder 2: eating rate in kcal using active eating time', 
                                   Units = 'kcal/min'),
    eat_rate_active_g_2 = list( Description = 'Coder 2: eating rate in grams using active eating time', 
                                Units = 'g/min'),
    eat_rate_active_g_inc_water_2 = list( Description = 'Coder 2: eating rate with water in grams using active eating time', 
                                          Units = 'g/min'),
    bite_size_kcal_2 = list( Description = 'Coder 2: bite size in kcal', 
                             Units = 'kcal/bite'),
    bite_size_g_2 = list( Description = 'Coder 2: bite size in grams', 
                          Units = 'g/bite')
  )
  
  # convert formatting to JSON
  micro_beh_json <- RJSONIO::toJSON(micro_beh_list, pretty = TRUE)
  
  # double check
  if (isFALSE(RJSONIO::isValidJSON(micro_beh_json, asText = TRUE))){
    print('micro_beh JSON file may be invalid')
  }
  
  return(micro_beh_json)
  
}