#' json_brief2: Generates a json file for the Behavioral Rating Inventory of Executive Function-2
#'
#' This function generates a json file for the scored Behavioral Rating Inventory of Executive Function-2 and raw participant responses. This function provides accurate json files ONLY if data is processed using score_brief2 function in dataprepr and is only accurate for data collected in Study BRAKE.
#'
#' @return A json file documenting the raw inputs and scored values for the Behavioral Rating Inventory of Executive Function-2
#'
#'
#' @export

json_brief2 <- function() {
  
  brief_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Behavioral Rating Inventory of Executive Function-2',
      Reference = 'Gioia GA, Isquith PK, Guy SC, Kenworthy L. BRIEF-2: Behavior Rating Inventory of Executive Function: Professional Manual. Psychological Assessment Resources; 2015.', 
      TermURL = 'https://www.cognitiveatlas.org/task/id/tsk_4a57abb9498ab/'),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-baseline' = 'baseline',
                                      'ses-followup' = '1-year follow-up')),
    visit_protocol = list( Description = 'child visit protocol number (does not necessarilty reflect visit order. See participants.tsv for child visit protocol dates)',
                           Levels = list ('1' =	'Child visit protocol 1 (baseline)',
                                          '2' =	'Child visit protocol 2 (baseline)',
                                          '3'	= 'Child visit protocol 3 (follow-up')),
    sex = list( Description = 'sex',
                Levels = list ('0' = 'male',
                               '1' = 'female')),
    age = list( Description = 'child age at visit 1', 
                Units = 'years'),
    brief1 = list( Description = 'My child eats too quickly',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief2 = list( Description = 'My child eats too much',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief3 = list( Description = 'My child eats unhealthy snacks',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief4 = list( Description = 'My child whinges or whines about food',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief5 = list( Description = 'My child yells about food',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief6 = list( Description = 'My child throws a tantrum about food',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief7 = list( Description = 'My child refuses to eat certain foods (i.e. fussy eating)',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief8 = list( Description = 'My child argues about food (e.g. when you say "No More")',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief9 = list( Description = 'My child demands extra helpings at meals',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief10 = list( Description = 'My child requests food continuously between meals',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief11 = list( Description = 'My child demands food when shopping or on outings',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief12 = list( Description = 'My child sneaks food when they know they are not supposed to',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief13 = list( Description = 'My child hides food',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief14 = list( Description = 'My child steals food (e.g. from other children\'s lunchboxes)',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief15 = list( Description = 'My child eats food to comfort themselves when feeling let down or depressed',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief16 = list( Description = 'My child watches too much television',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief17 = list( Description = 'My child spends too much time playing video or computer games',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief18 = list( Description = 'My child complains about doing physical activity (e.g. "This is boring, I\'m too tired, My leg hurts")',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief19 = list( Description = 'My child refuses to do physical activity',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief20 = list( Description = 'My child complains about being unfit or feeling low in energy',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief21 = list( Description = 'My child complains about being overweight',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief22 = list( Description = 'My child complains about being teased',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief23 = list( Description = 'My child complains about not having enough friends',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief24 = list( Description = 'My child complains about being unattractive',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief25 = list( Description = 'My child complains about not fitting into clothes',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief26 = list( Description = 'My child does not notice when his/her behavior causes negative reactions',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief27 = list( Description = 'My child reacts more strongly to situations than other children',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief28 = list( Description = 'My child has trouble remembering things, even for a few minutes',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief29 = list( Description = 'My child makes careless errors',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief30 = list( Description = 'My child becomes upset with new situations',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief31 = list( Description = 'Confidence deal with: My child throws a tantrum about food',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief32 = list( Description = 'My child has trouble concentrating on tasks, schoolwork, etc.',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief33 = list( Description = 'My child has poor handwriting',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief34 = list( Description = 'My child\'s mood changes frequently',
                 Levels = list ('1' = 'Not at all',
                                '2' = 'Sometimes',
                                '3' = 'Never')),
    brief35 = list( Description = 'My child has good ideas but cannot get them on paper',
                  Levels = list ('1' = 'Not at all',
                                 '2' = 'Sometimes',
                                 '3' = 'Never')),
    brief36 = list( Description = 'My child has trouble counting to three',
                  Levels = list ('1' = 'Not at all',
                                 '2' = 'Sometimes',
                                 '3' = 'Never')),
    brief37 = list( Description = 'My child leaves messes that others have to clean up',
                  Levels = list ('1' = 'Not at all',
                                 '2' = 'Sometimes',
                                 '3' = 'Never')),
    brief38 = list( Description = 'My child needs to be told when to begin a task even when willing',
                  Levels = list ('1' = 'Not at all',
                                 '2' = 'Sometimes',
                                 '3' = 'Never')),
    brief39 = list( Description = 'My child acts too wild or "out of control"',
                  Levels = list ('1' = 'Not at all',
                                 '2' = 'Sometimes',
                                 '3' = 'Never')),
    brief40 = list( Description = 'My child thinks too much about the same topic',
                  Levels = list ('1' = 'Not at all',
                                 '2' = 'Sometimes',
                                 '3' = 'Never')),
    brief41 = list( Description = 'My child forgets what he/she was doing',
                  Levels = list ('1' = 'Not at all',
                                 '2' = 'Sometimes',
                                 '3' = 'Never')),
    brief42 = list( Description = 'My child does not check work for mistakes',
                  Levels = list ('1' = 'Not at all',
                                 '2' = 'Sometimes',
                                 '3' = 'Never')),
    brief43 = list( Description = 'My child\'s angry or tearful outbursts are intense but end suddenly',
                  Levels = list ('1' = 'Not at all',
                                 '2' = 'Sometimes',
                                 '3' = 'Never')),
    brief44 = list( Description = 'My child becomes overwhelmed by large assignments',
                  Levels = list ('1' = 'Not at all',
                                 '2' = 'Sometimes',
                                 '3' = 'Never')),
    brief45 = list( Description = 'My child loses lunch box, lunch money, permission slips, homework, etc.',
                  Levels = list ('1' = 'Not at all',
                                 '2' = 'Sometimes',
                                 '3' = 'Never')),
    brief46 = list( Description = 'My child needs help from an adult to stay on task',
                  Levels = list ('1' = 'Not at all',
                                 '2' = 'Sometimes',
                                 '3' = 'Never')),
    brief47 = list( Description = 'My child forgets to hand in homework, even when completed',
                  Levels = list ('1' = 'Not at all',
                                 '2' = 'Sometimes',
                                 '3' = 'Never')),
    brief48 = list( Description = 'My child has trouble putting the brakes on his/her actions',
                  Levels = list ('1' = 'Not at all',
                                 '2' = 'Sometimes',
                                 '3' = 'Never')),
    brief49 = list( Description = 'My child resists change of routine, foods, places, etc.',
                  Levels = list ('1' = 'Not at all',
                                 '2' = 'Sometimes',
                                 '3' = 'Never')),
    brief50 = list( Description = 'My child has trouble getting started on homework or tasks',
                  Levels = list ('1' = 'Not at all',
                                 '2' = 'Sometimes',
                                 '3' = 'Never')),
    brief51= list( Description = 'My child\'s mood is easily influenced by the situation',
                    Levels = list ('1' = 'Not at all',
                                   '2' = 'Sometimes',
                                   '3' = 'Never')),
    brief52 = list( Description = 'My child underestimates time needed to finish tasks',
                    Levels = list ('1' = 'Not at all',
                                   '2' = 'Sometimes',
                                   '3' = 'Never')),
    brief53 = list( Description = 'My child does not bring home homework, assignment sheets, materials, etc.',
                    Levels = list ('1' = 'Not at all',
                                   '2' = 'Sometimes',
                                   '3' = 'Never')),
    brief54 = list( Description = 'My child cannot find the front door of home',
                    Levels = list ('1' = 'Not at all',
                                   '2' = 'Sometimes',
                                   '3' = 'Never')),
    brief55 = list( Description = 'My child does not take initiative',
                    Levels = list ('1' = 'Not at all',
                                   '2' = 'Sometimes',
                                   '3' = 'Never')),
    brief56 = list( Description = 'My child becomes upset too easily',
                    Levels = list ('1' = 'Not at all',
                                   '2' = 'Sometimes',
                                   '3' = 'Never')),
    brief57 = list( Description = 'My child starts assignments or tasks at the last minute',
                    Levels = list ('1' = 'Not at all',
                                   '2' = 'Sometimes',
                                   '3' = 'Never')),
    brief58 = list( Description = 'My child has trouble moving from one activity to another',
                    Levels = list ('1' = 'Not at all',
                                   '2' = 'Sometimes',
                                   '3' = 'Never')),
    brief59 = list( Description = 'My child has trouble carrying out the actions needed to reach goals (saving money for special item, studying to get a good grade, etc.)',
                    Levels = list ('1' = 'Not at all',
                                   '2' = 'Sometimes',
                                   '3' = 'Never')),
    brief60 = list( Description = 'My child is disturbed by change of teacher or class',
                    Levels = list ('1' = 'Not at all',
                                   '2' = 'Sometimes',
                                   '3' = 'Never')),
    brief61 = list( Description = 'My child has trouble organizing activities with friends',
                    Levels = list ('1' = 'Not at all',
                                   '2' = 'Sometimes',
                                   '3' = 'Never')),
    brief62 = list( Description = 'My child becomes too silly',
                    Levels = list ('1' = 'Not at all',
                                   '2' = 'Sometimes',
                                   '3' = 'Never')),
    brief63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                    Levels = list ('1' = 'Not at all',
                                   '2' = 'Sometimes',
                                   '3' = 'Never')),
    brief2_inhibit = list( Description = 'Inhibition', 
                     Derivative = TRUE),
    brief2_inhibit_t = list( Description = 'Inhibition T-score', 
                           Derivative = TRUE),
    brief2_inhibit_p = list( Description = 'Inhibition Percentile', 
                           Derivative = TRUE),
    brief2_selfmon = list( Description = 'Self-Monitoring', 
                       Derivative = TRUE),
    brief2_selfmon_t = list( Description = 'Self-Monitoring T-score', 
                           Derivative = TRUE),
    brief2_selfmon_p = list( Description = 'Self-Monitoring Percentile', 
                           Derivative = TRUE),
    brief2_shift = list( Description = 'Shifting', 
                       Derivative = TRUE),
    brief2_shift_t = list( Description = 'Shifting T-score', 
                         Derivative = TRUE),
    brief2_shift_p = list( Description = 'Shifting Percentile', 
                         Derivative = TRUE),
    brief2_emcont = list( Description = 'Emotional Control', 
                       Derivative = TRUE),
    brief2_emcont_t = list( Description = 'Emotional Control T-score', 
                          Derivative = TRUE),
    brief2_emcont_p = list( Description = 'Emotional Control Percentile', 
                          Derivative = TRUE),
    brief2_initiate = list( Description = 'Initiate', 
                       Derivative = TRUE),
    brief2_initiate_t = list( Description = 'Initiate T-score', 
                            Derivative = TRUE),
    brief2_initiate_p = list( Description = 'Initiate Percentile', 
                            Derivative = TRUE),
    brief2_wm = list( Description = 'Working Memory', 
                          Derivative = TRUE),
    brief2_wm_t = list( Description = 'Working Memory T-score', 
                      Derivative = TRUE),
    brief2_wm_p = list( Description = 'Working Memory Percentile', 
                      Derivative = TRUE),
    brief2_planorg = list( Description = 'Planning/Organization', 
                          Derivative = TRUE),
    brief2_planorg_t = list( Description = 'Planning/Organization T-score', 
                           Derivative = TRUE),
    brief2_planorg_p = list( Description = 'Planning/Organization Percentile', 
                           Derivative = TRUE),
    brief2_taskmon = list( Description = 'Task Monitoring', 
                          Derivative = TRUE),
    brief2_taskmon_t = list( Description = 'Task Monitoring T-score', 
                           Derivative = TRUE),
    brief2_taskmon_p = list( Description = 'Task Monitoring Percentile', 
                           Derivative = TRUE),
    brief2_orgmat = list( Description = 'Organiation of Materials', 
                          Derivative = TRUE),
    brief2_orgmat_t = list( Description = 'Organiation of Materials T-score', 
                          Derivative = TRUE),
    brief2_orgmat_p = list( Description = 'Organiation of Materials Percentile', 
                          Derivative = TRUE),
    brief2_bri = list( Description = 'Behavioral Regulation Index', 
                          Derivative = TRUE),
    brief2_bri_t = list( Description = 'Behavioral Regulation Index T-score', 
                       Derivative = TRUE),
    brief2_bri_p = list( Description = 'Behavioral Regulation Index Percentile', 
                       Derivative = TRUE),
    brief2_eri = list( Description = 'Emotional Regulaiton Index', 
                       Derivative = TRUE),
    brief2_eri_t = list( Description = 'Emotional Regulaiton Index T-score', 
                       Derivative = TRUE),
    brief2_eri_p = list( Description = 'Emotional Regulaiton Index Percentile', 
                       Derivative = TRUE),
    brief2_cri = list( Description = 'Cognitive Regulation Index', 
                       Derivative = TRUE),
    brief2_cri_t = list( Description = 'Cognitive Regulation Index T-score', 
                       Derivative = TRUE),
    brief2_cri_p = list( Description = 'Cognitive Regulation Index Percentile', 
                       Derivative = TRUE),
    brief2_gec = list( Description = 'General Executive Composite', 
                       Derivative = TRUE),
    brief2_gec_t = list( Description = 'General Executive Composite T-score', 
                       Derivative = TRUE),
    brief2_gec_p = list( Description = 'General Executive Composite Percentile', 
                       Derivative = TRUE),
    brief2_negativity = list( Description = 'Negativity Check', 
                       Derivative = TRUE),
    brief2_negativity_p = list( Description = 'Negativity Check Percentile', 
                              Derivative = TRUE),
    brief2_negativity_cat = list( Description = 'Negativity Check Category',
                                  Levels = list ('0' = '<=98',
                                                 '1' = '99', 
                                                 '2' = '>99'),
                                  Derivative = TRUE),
    brief2_inconsistency = list( Description = 'Inconsistency Check', 
                       Derivative = TRUE),
    brief2_inconsistency_p = list( Description = 'Inconsistency Check Percentile', 
                                 Derivative = TRUE),
    brief2_inconsistency_cat = list( Description = 'Inconsistency Check Category', 
                                 Levels = list ('0' = '<=98',
                                                '1' = '99', 
                                                '2' = '>99'),
                                 Derivative = TRUE),
    brief2_infrequency = list( Description = 'Infrequency', 
                                 Derivative = TRUE),
    brief2_infrequency_p = list( Description = 'Infrequency Percentile', 
                               Derivative = TRUE),
    brief2_infrequency_cat = list( Description = 'Infrequency Category', 
                                   Levels = list ('0' = 'Acceptable',
                                                  '1' = 'Questionable'),
                                   Derivative = TRUE))
  

  # convert formatting to JSON
  brief_json <- RJSONIO::toJSON(brief_list, pretty = TRUE)
  
  # double check
  if (isFALSE(RJSONIO::isValidJSON(brief_json, asText = TRUE))){
    print('BRIEF JSON file may be invalid')
  }
  
  return(brief_json)
  
}