#' json_dkefs: Generates a json file for D-KEFS 
#'
#' This function generates a json file for D-KEFS 
#'
#' @return A json file documenting the Study BRAKE's D-KEFS 
#'
#'
#' @export

json_dkefs <- function() {
  
  dkefs_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Dellis-Kaplan Executive Functioning System',
      Reference = 'Delis, Dean C., Edith Kaplan, and Joel H. Kramer. "Delis-Kaplan executive function system." Assessment (2001).',
      TermURL = 'https://doi.org/10.1037/t15082-000'),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-baseline' = 'baseline',
                                      'ses-followup' = '1-year follow-up')),
    dkefs_collect = list( Description = 'Was the D-KEFS completed?',
                           Levels = list( '0' = 'No',
                                          '1' = 'Yes')),
    dkefs_no_reason = list( Description = 'If not completed, reason why'),
    dkefs_tmt_visualscan_raw = list( Description = 'Trail Making Test: Visual Scanning raw score'),
    dkefs_tmt_visualscan_ss = list( Description = 'Trail Making Test: Visual Scanning scaled score'),
    dkefs_tmt_num_raw = list( Description = 'Trail Making Test: Numbers raw score'),
    dkefs_tmt_num_ss = list( Description = 'Trail Making Test: Nubmers scaled score'),
    dkefs_tmt_letter_raw = list( Description = 'Trail Making Test: Letters raw score'),
    dkefs_tmt_letter_ss = list( Description = 'Trail Making Test: Letters scaled score'),
    dkefs_tmt_switch_raw = list( Description = 'Trail Making Test: Switching raw score'),
    dkefs_tmt_switch_ss = list( Description = 'Trail Making Test: Switching scaled score'),
    dkefs_tmt_motorspeed_raw = list( Description = 'Trail Making Test: Motor Speed raw score'),
    dkefs_tmt_motorspeed_ss = list( Description = 'Trail Making Test: Motor Speed scaled score'),
    dkefs_tmt_switch_scan_dif = list( Description = 'Trail Making Test: Difference in Switching and Visual Scanning'),
    dkefs_tmt_switch_scan_ss = list( Description = 'Trail Making Test: Difference in Switching and Visual Scanning scaled score'),
    dkefs_tmt_switch_num_dif = list( Description = 'Trail Making Test: Difference in Switching and Numbers'),
    dkefs_tmt_switch_num_ss = list( Description = 'Trail Making Test: Difference in Switching and Numbers scaled score'),
    dkefs_tmt_switch_letter_dif = list( Description = 'Trail Making Test: Difference in Switching and Letters'),
    dkefs_tmt_switch_letter_ss = list( Description = 'Trail Making Test: Difference in Switching and Letters scaled score'),
    dkefs_tmt_switch_numletter_dif = list( Description = 'Trail Making Test: Difference in Switching and combined Numbers and Letters'),
    dkefs_tmt_switch_numletter_ss = list( Description = 'Trail Making Test: Difference in Switching and combined Numbers and Letters scaled score'),
    dkefs_tmt_scan_miss = list( Description = 'Trail Making Test: Number missed on Visual Scan'),
    dkefs_tmt_scan_miss_p = list( Description = 'Trail Making Test: Percentile for Number missed on Visual Scan'),
    dkefs_tmt_switch_motor_dif = list( Description = 'Trail Making Test: Difference in Switching and Motor Speed'),
    dkefs_tmt_scan_fa = list( Description = 'Trail Making Test: Number of false alarms on Visual Scan'),
    dkefs_tmt_scan_fa_p = list( Description = 'Trail Making Test: Percentile for Number of false alarms on Visual Scan'),
    dkefs_tmt_switch_motor_ss = list( Description = 'Trail Making Test: Difference in Switching and Motor Speed scaled score'),
    dkefs_tmt_num_error = list( Description = 'Trail Making Test: Number sequencing errors'),
    dkefs_tmt_letter_error = list( Description = 'Trail Making Test: Letter sequencing errors'),
    dkefs_tmt_switch_error = list( Description = 'Trail Making Test: Switching sequencing errors'),
    dkefs_tmt_num_error_p = list( Description = 'Trail Making Test: Percentile for number of errors for Numbers'),
    dkefs_tmt_letter_error_p = list( Description = 'Trail Making Test: Percentile for number of errors for Letters'),
    dkefs_tmt_switch_error_p = list( Description = 'Trail Making Test: Percentile for number of errors for Switching'),
    dkefs_tmt_num_setloss = list( Description = 'Trail Making Test: Number of set-loss errors for Numbers'),
    dkefs_tmt_letter_setloss = list( Description = 'Trail Making Test: Number of set-loss errors for Letters'),
    dkefs_tmt_switch_setloss = list( Description = 'Trail Making Test: Number of set-loss errors for Switching'),
    dkefs_tmt_num_setloss_p = list( Description = 'Trail Making Test: Percentile for number of set-loss errors for Numbers'),
    dkefs_tmt_letter_setloss_p = list( Description = 'Trail Making Test: Percentile for number of set-loss errors for Letters'),
    dkefs_tmt_switch_setloss_p = list( Description = 'Trail Making Test: Percentile for number of set-loss errors for Switching'),
    dkefs_tmt_num_terrors = list( Description = 'Trail Making Test: Number of timming errors for Numbers'),
    dkefs_tmt_letter_terrors = list( Description = 'Trail Making Test: Number of timming errors for Letters'),
    dkefs_tmt_switch_terrors = list( Description = 'Trail Making Test: Number of timming errors for Switching'),
    dkefs_tmt_motor_terrors = list( Description = 'Trail Making Test: Number of timming errors for Motor Speed'),
    dkefs_tmt_letter_terrors_p = list( Description = 'Trail Making Test: Percentile for number of timming errors for Letters'),
    dkefs_tmt_letter_terrors_p = list( Description = 'Trail Making Test: Percentile for number of timming errors for Letters'),
    dkefs_tmt_switch_terrors_p = list( Description = 'Trail Making Test: Percentile for number of timming errors for Switching'),
    dkefs_tmt_motor_terrors_p = list( Description = 'Trail Making Test: Percentile for number of timming errors for Motor Speed'),
    dkefs_tmt_switch_allerror = list( Description = 'Trail Making Test: All errors for Switching'),
    dkefs_tmt_switch_allerror_p = list( Description = 'Trail Making Test: Percentile for all errors for Switching'),
    dkefs_vf_letter_cor = list( Description = 'Verbal Fluency: Letters number correct'),
    dkefs_vf_letter_cor_ss = list( Description = 'Verbal Fluency: Letters number correct scaled score'),
    dkefs_vf_cat_cor = list( Description = 'Verbal Fluency: Category number correct'),
    dkefs_vf_cat_cor_ss = list( Description = 'Verbal Fluency: Category number correct scaled score'),
    dkefs_vf_switch_cor = list( Description = 'Verbal Fluency: Switching number correct'),
    dkefs_vf_switch_cor_ss = list( Description = 'Verbal Fluency: Switching number correct scaled score'),
    dkefs_vf_switch_acc = list( Description = 'Verbal Fluency: Switching accuracy'),
    dkefs_vf_switch_acc_ss = list( Description = 'Verbal Fluency: Switching accuracy scaled score'),
    dkefs_vf_letter_cat_dif = list( Description = 'Verbal Fluency: Difference in Letter and Category fluency'),
    dkefs_vf_letter_cat_ss = list( Description = 'Verbal Fluency: Difference in Letter and Category fluency scaled score'),
    dkefs_vf_switch_cat_dif = list( Description = 'Verbal Fluency: Difference in Switching and Category fluency'),
    dkefs_vf_switch_cat_ss = list( Description = 'Verbal Fluency: Difference in Switching and Category fluency scaled score'),
    dkefs_vf_int1_letter_cor = list( Description = 'Verbal Fluency: Letter number correct - Interval 1'),
    dkefs_vf_int2_letter_cor = list( Description = 'Verbal Fluency: Letter number correct - Interval 2'),
    dkefs_vf_int3_letter_cor = list( Description = 'Verbal Fluency: Letter number correct - Interval 3'),
    dkefs_vf_int4_letter_cor = list( Description = 'Verbal Fluency: Letter number correct - Interval 4'),
    dkefs_vf_int1_cat_cor = list( Description = 'Verbal Fluency: Category number correct - Interval 1'),
    dkefs_vf_int2_cat_cor = list( Description = 'Verbal Fluency: Category number correct - Interval 2'),
    dkefs_vf_int3_cat_cor = list( Description = 'Verbal Fluency: Category number correct - Interval 3'),
    dkefs_vf_int4_cat_cor = list( Description = 'Verbal Fluency: Category number correct - Interval 4'),
    dkefs_vf_int1_switch_cor = list( Description = 'Verbal Fluency: Switching number correct - Interval 1'),
    dkefs_vf_int2_switch_cor = list( Description = 'Verbal Fluency: Switching number correct - Interval 2'),
    dkefs_vf_int3_switch_cor = list( Description = 'Verbal Fluency: Switching number correct - Interval 3'),
    dkefs_vf_int4_switch_cor = list( Description = 'Verbal Fluency: Switching number correct - Interval 4'),
    dkefs_vf_int1_total_cor = list( Description = 'Verbal Fluency: Total number correct - Interval 1'),
    dkefs_vf_int2_total_cor = list( Description = 'Verbal Fluency: Total number correct - Interval 2'),
    dkefs_vf_int3_total_cor = list( Description = 'Verbal Fluency: Total number correct - Interval 3'),
    dkefs_vf_int4_total_cor = list( Description = 'Verbal Fluency: Total number correct - Interval 4'),
    dkefs_vf_int1_total_cor_ss = list( Description = 'Verbal Fluency: Total number correct - Interval 1 scaled score'),
    dkefs_vf_int2_total_cor_ss = list( Description = 'Verbal Fluency: Total number correct - Interval 2 scaled score'),
    dkefs_vf_int3_total_cor_ss = list( Description = 'Verbal Fluency: Total number correct - Interval 3 scaled score'),
    dkefs_vf_int4_total_cor_ss = list( Description = 'Verbal Fluency: Total number correct - Interval 4 scaled score'),
    dkefs_vf_letter_setloss = list( Description = 'Verbal Fluency: Letter set-loss errors'),
    dkefs_vf_cat_setloss = list( Description = 'Verbal Fluency: Category set-loss errors'),
    dkefs_vf_switch_setloss = list( Description = 'Verbal Fluency: Switching set-loss errors'),
    dkefs_vf_total_setloss = list( Description = 'Verbal Fluency: Total set-loss errors'),
    dkefs_vf_total_setloss_ss = list( Description = 'Verbal Fluency: Total set-loss errors scaled score'),
    dkefs_vf_letter_rep = list( Description = 'Verbal Fluency: Letter repetition errors'),
    dkefs_vf_cat_rep = list( Description = 'Verbal Fluency: Category repetition errors'),
    dkefs_vf_switch_rep = list( Description = 'Verbal Fluency: Switching repetition errors'),
    dkefs_vf_total_rep = list( Description = 'Verbal Fluency: Total repetition errors'),
    dkefs_vf_total_rep_ss = list( Description = 'Verbal Fluency: Total repetition errors scaled score'),
    dkefs_vf_letter_total_resp = list( Description = 'Verbal Fluency: Letter number of responses'),
    dkefs_vf_cat_total_resp = list( Description = 'Verbal Category: Letter number of responses'),
    dkefs_vf_switch_total_resp = list( Description = 'Verbal Switching: Letter number of responses'),
    dkefs_vf_total_resp = list( Description = 'Verbal Total: Total number of responses'),
    dkefs_vf_total_resp_ss = list( Description = 'Verbal Total: Total number of responses scaled score'),
    dkefs_vf_setloss_perc = list( Description = 'Verbal Fluency: Total percent set-loss errors'),
    dkefs_vf_setloss_perc_ss = list( Description = 'Verbal Fluency: Total percent set-loss errors scaled score'),
    dkefs_vf_rep_perc = list( Description = 'Verbal Fluency: Total percent repetition errors'),
    dkefs_vf_rep_perc_ss = list( Description = 'Verbal Fluency: Total percent repetition errors'),
    dkefs_vf_switch_acc_perc = list( Description = 'Verbal Fluency: Switching accuracy percent'),
    dkefs_vf_switch_acc_perc_ss = list( Description = 'Verbal Fluency: Switching accuracy percent scaled score'),
    dkefs_df_filled_cor = list( Description = 'Design Fluency: Filled correct'),
    dkefs_df_filled_cor_ss = list( Description = 'Design Fluency: Filled correct scaled score'),
    dkefs_df_empty_cor = list( Description = 'Design Fluency: Empty correct'),
    dkefs_df_empty_cor_ss = list( Description = 'Design Fluency: Empty correct scaled score'),
    dkefs_df_switch_cor = list( Description = 'Design Fluency: Switching correct'),
    dkefs_df_switch_cor_ss = list( Description = 'Design Fluency: Switching correct scaled score'),
    dkefs_df_total_cor = list( Description = 'Design Fluency: Total correct'),
    dkefs_df_total_cor_sum_ss = list( Description = 'Design Fluency: Total correct sum of scaled scores'),
    dkefs_df_total_cor_ss = list( Description = 'Design Fluency: Total correct scaled scores'),
    dkefs_df_filled_empty_sum = list( Description = 'Design Fluency: Sum of Filled + Empty'),
    dkefs_df_filled_empty_ss = list( Description = 'Design Fluency: Sum of Filled + Empty'),
    dkefs_df_switch_fillempty_dif = list( Description = 'Design Fluency: Difference in Switching and the sum of Filled and Empty'),
    dkefs_df_switch_fillempty_ss = list( Description = 'Design Fluency: Difference in Switching and the sum of Filled and Empty'),
    dkefs_df_filled_setloss = list( Description = 'Design Fluency: Filled set-loss errors'),
    dkefs_df_empty_setloss = list( Description = 'Design Fluency: Empty set-loss errors'),
    dkefs_df_switch_setloss = list( Description = 'Design Fluency: Switching set-loss errors'),
    dkefs_df_total_setloss = list( Description = 'Design Fluency: Total set-loss errors'),
    dkefs_df_total_setloss_ss = list( Description = 'Design Fluency: Total set-loss errors scale score'),
    dkefs_df_filled_rep = list( Description = 'Design Fluency: Filled repetition errors'),
    dkefs_df_empty_rep = list( Description = 'Design Fluency: Empty repetition errors'),
    dkefs_df_switch_rep = list( Description = 'Design Fluency: Switching repetition errors'),
    dkefs_df_total_rep = list( Description = 'Design Fluency: Total repetition errors'),
    dkefs_df_total_rep_ss = list( Description = 'Design Fluency: Total repetition errors scaled score'),
    dkefs_df_filled_rep = list( Description = 'Design Fluency: Filled number of responses'),
    dkefs_df_filled_rep = list( Description = 'Design Fluency: Empty number of responses'),
    dkefs_df_filled_rep = list( Description = 'Design Fluency: Swithcing number of responses'),
    dkefs_df_filled_rep = list( Description = 'Design Fluency: Total number of responses'),
    dkefs_df_filled_rep_ss = list( Description = 'Design Fluency: Total number of responses'),
    dkefs_df_acc_perc = list( Description = 'Design Fluency: Total response accuracy percent'),
    dkefs_df_acc_perc_ss = list( Description = 'Design Fluency: Total response accuracy percent scaled score'),
    )
  
  # convert formatting to JSON
  dkefs_json <- RJSONIO::toJSON(dkefs_list, pretty = TRUE)
  
  # double check
  if (isFALSE(RJSONIO::isValidJSON(dkefs_json, asText = TRUE))){
    print('D-KEFS JSON file may be invalid')
  }
  
  return(dkefs_json)
  
}