#' json_nki_hfe: Generates a json file for the Home Food Environment Survey from the Neighborhood Impact on Kids Study
#'
#' This function generates a json file for the scored Home Food Environment Survey from the Neighborhood Impact on Kids Study and raw participant responses. This function provides accurate json files ONLY if data is processed using score_nki_hfe function in dataprepr and is only accurate for data collected in Study BRAKE.
#'
#' @return A json file documenting the raw inputs and scored values for the Home Food Environment Survey from the Neighborhood Impact on Kids Study
#'
#'
#' @export

json_nki_hfe <- function() {
  
  nki_hfe_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Home Food Environment Survey from the Neighborhood Impact on Kids Study.',
      Reference = 'B1. Couch SC, Glanz K, Zhou C, Sallis JF, Saelens BE. Home Food Environment in Relation to Children’s Diet Quality and Weight Status. Journal of the Academy of Nutrition and Dietetics. 2014;114(10):1569-1579.e1. doi:10.1016/j.jand.2014.05.015', 
      TermURL = 'https://pubmed.ncbi.nlm.nih.gov/25066057/'),
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-baseline' = 'baseline',
                                      'ses-followup' = '1-year follow-up')),
    visit_protocol = list( Description = 'child visit protocol number (does not necessarilty reflect visit order. See participants.tsv for child visit protocol dates)',
                           Levels = list ('1' =	'Child visit protocol 1 (baseline)',
                                          '2' =	'Child visit protocol 2 (baseline)',
                                          '3'	= 'Child visit protocol 3 (follow-up')),
    visit_date = list( Description = 'Date of visit',
                       Unit = 'YYYY-MM-DD'),
    hfe_fam1 = list( Description = 'I eat food I want my child to eat',
                 Levels = list ('1' = 'Never',
                                '2' = 'Rarely',
                                '3' = 'Sometimes',
                                '4' = 'Often',
                                '5' = 'Always')),
    hfe_fam2 = list( Description = 'My child learns to eat low-fat snacks from me',
                     Levels = list ('1' = 'Never',
                                    '2' = 'Rarely',
                                    '3' = 'Sometimes',
                                    '4' = 'Often',
                                    '5' = 'Always')),
    hfe_fam3 = list( Description = 'When I show my child I enjoy fruits/vegetables, he/she tries them',
                     Levels = list ('1' = 'Never',
                                    '2' = 'Rarely',
                                    '3' = 'Sometimes',
                                    '4' = 'Often',
                                    '5' = 'Always')),
    hfe_fam4 = list( Description = 'I sit with my child at mealtime',
                     Levels = list ('1' = 'Never',
                                    '2' = 'Rarely',
                                    '3' = 'Sometimes',
                                    '4' = 'Often',
                                    '5' = 'Always')),
    hfe_fam4 = list( Description = 'How often do you or another adult in the house cook an evening meal?',
                     Levels = list ('1' = 'Never',
                                    '2' = 'Rarely',
                                    '3' = 'Sometimes',
                                    '4' = 'Often',
                                    '5' = 'Always')),
    hfe_fam6 = list( Description = 'I encourage my child to eat fruit',
                     Levels = list ('1' = 'Never',
                                    '2' = 'Rarely',
                                    '3' = 'Sometimes',
                                    '4' = 'Often',
                                    '5' = 'Always')),
    hfe_fam7 = list( Description = 'I encourage my child to eat vegetables',
                     Levels = list ('1' = 'Never',
                                    '2' = 'Rarely',
                                    '3' = 'Sometimes',
                                    '4' = 'Often',
                                    '5' = 'Always')),
    hfe_fam8 = list( Description = 'At home, we have vegetables at dinner',
                     Levels = list ('1' = 'Never',
                                    '2' = 'Rarely',
                                    '3' = 'Sometimes',
                                    '4' = 'Often',
                                    '5' = 'Always')),
    hfe_fam9 = list( Description = 'I cut up fruits and vegetables for my child to eat in between meals',
                     Levels = list ('1' = 'Never',
                                    '2' = 'Rarely',
                                    '3' = 'Sometimes',
                                    '4' = 'Often',
                                    '5' = 'Always')),
    hfe_fam10 = list( Description = 'How often can your child eat snacks and/or sweets without your permission?',
                      Levels = list ('1' = 'Never',
                                     '2' = 'Rarely',
                                     '3' = 'Sometimes',
                                     '4' = 'Often',
                                     '5' = 'Always')),
    hfe_fam11 = list( Description = 'How often does your child eat while watching TV?',
                      Levels = list ('1' = 'Never',
                                     '2' = 'Rarely',
                                     '3' = 'Sometimes',
                                     '4' = 'Often',
                                     '5' = 'Always')),
    hfe_fam12 = list( Description = 'How often does your child eat in his/her bedroom?',
                      Levels = list ('1' = 'Never',
                                     '2' = 'Rarely',
                                     '3' = 'Sometimes',
                                     '4' = 'Often',
                                     '5' = 'Always')),
    hfe_fam13 = list( Description = 'How often does your child ask for or take a second helping?',
                      Levels = list ('1' = 'Never',
                                     '2' = 'Rarely',
                                     '3' = 'Sometimes',
                                     '4' = 'Often',
                                     '5' = 'Always')),
    hfe_track1 = list( Description = 'I have to be sure that my child does not eat too many high-fat foods',
                       Levels = list ('1' = 'Strongly Disagree',
                                      '2' = 'Slightly disagree',
                                      '3' = 'Neutral',
                                      '4' = 'Slightly agree',
                                      '5' = 'Agree')),
    hfe_track2 = list( Description = 'I have to be sure that my child does not eat too many sweets',
                       Levels = list ('1' = 'Strongly Disagree',
                                      '2' = 'Slightly disagree',
                                      '3' = 'Neutral',
                                      '4' = 'Slightly agree',
                                      '5' = 'Agree')),
    hfe_track3 = list( Description = 'If I did not guide or regulate my child\'s eating he/she would eat much less food than he/she should',
                       Levels = list ('1' = 'Strongly Disagree',
                                      '2' = 'Slightly disagree',
                                      '3' = 'Neutral',
                                      '4' = 'Slightly agree',
                                      '5' = 'Agree')),
    hfe_track4 = list( Description = 'I have to be especially careful to make sure my child eats enough',
                       Levels = list ('1' = 'Strongly Disagree',
                                      '2' = 'Slightly disagree',
                                      '3' = 'Neutral',
                                      '4' = 'Slightly agree',
                                      '5' = 'Agree')),
    hfe_track5 = list( Description = 'If my child says "I am not hungry" I try to get him/her to eat anyway',
                  Levels = list ('1' = 'Strongly Disagree',
                                 '2' = 'Slightly disagree',
                                 '3' = 'Neutral',
                                 '4' = 'Slightly agree',
                                 '5' = 'Agree')),
    hfe_track6 = list( Description = 'My child should always eat all of the food on his/her plate',
                       Levels = list ('1' = 'Strongly Disagree',
                                      '2' = 'Slightly disagree',
                                      '3' = 'Neutral',
                                      '4' = 'Slightly agree',
                                      '5' = 'Agree')),
    hfe_rules1 = list( Description = 'No second helpings at meals',
                       Levels = list ('0' = 'No',
                                      '1' = 'Yes')),
    hfe_rules2 = list( Description = 'Limited portion sizes at meals',
                       Levels = list ('0' = 'No',
                                      '1' = 'Yes')),
    hfe_rules3 = list( Description = 'No dessert until plate is cleaned',
                       Levels = list ('0' = 'No',
                                      '1' = 'Yes')),
    hfe_rules4 = list( Description = 'No dessert except fruit',
                       Levels = list ('0' = 'No',
                                      '1' = 'Yes')),
    hfe_rules5 = list( Description = 'No meals while watching TV/DVDs',
                  Levels = list ('0' = 'No',
                                  '1' = 'Yes')),
    hfe_rules6 = list( Description = 'No snacking while watching TV/DVDs',
                       Levels = list ('0' = 'No',
                                      '1' = 'Yes')),
    hfe_rules7 = list( Description = 'No sweet snacks',
                       Levels = list ('0' = 'No',
                                      '1' = 'Yes')),
    hfe_rules8 = list( Description = 'No fried snacks at home (such as potato chips)',
                       Levels = list ('0' = 'No',
                                      '1' = 'Yes')),
    hfe_rules9 = list( Description = 'Must eat dinner with family',
                        Levels = list ('0' = 'No',
                                       '1' = 'Yes')),
    hfe_rules10 = list( Description = 'Must eat fruit everyday',
                        Levels = list ('0' = 'No',
                                       '1' = 'Yes')),
    hfe_rules11 = list( Description = 'Must eat vegetables every day',
                        Levels = list ('0' = 'No',
                                       '1' = 'Yes')),
    hfe_rules12 = list( Description = 'Limited fast food',
                        Levels = list ('0' = 'No',
                                       '1' = 'Yes')),
    hfe_avail1  = list( Description = 'How often are the following foods/drinks available in your home: Chocolate candy',
                       Levels = list ('1' = 'Never',
                                      '2' = 'Rarely',
                                      '3' = 'Sometimes',
                                      '4' = 'Often',
                                      '5' = 'Always')),
    hfe_avail2 = list( Description = 'How often are the following foods/drinks available in your home: Other candy',
                       Levels = list ('1' = 'Never',
                                      '2' = 'Rarely',
                                      '3' = 'Sometimes',
                                      '4' = 'Often',
                                      '5' = 'Always')),
    hfe_avail3 = list( Description = 'How often are the following foods/drinks available in your home: Raw fruit (e.g., apples, oranges)',
                       Levels = list ('1' = 'Never',
                                      '2' = 'Rarely',
                                      '3' = 'Sometimes',
                                      '4' = 'Often',
                                      '5' = 'Always')),
    hfe_avail4 = list( Description = 'How often are the following foods/drinks available in your home: Cakes, brownies, muffins or cookies',
                       Levels = list ('1' = 'Never',
                                      '2' = 'Rarely',
                                      '3' = 'Sometimes',
                                      '4' = 'Often',
                                      '5' = 'Always')),
    hfe_avail5 = list( Description = 'How often are the following foods/drinks available in your home: Regular chips or crackers',
                       Levels = list ('1' = 'Never',
                                      '2' = 'Rarely',
                                      '3' = 'Sometimes',
                                      '4' = 'Often',
                                      '5' = 'Always')),
    hfe_avail6 = list( Description = 'How often are the following foods/drinks available in your home: Baked chips, low-fat crackers, pretzels',
                       Levels = list ('1' = 'Never',
                                      '2' = 'Rarely',
                                      '3' = 'Sometimes',
                                      '4' = 'Often',
                                      '5' = 'Always')),
    hfe_avail7 = list( Description = 'How often are the following foods/drinks available in your home: Raw vegetables (e.g., carrots)',
                       Levels = list ('1' = 'Never',
                                      '2' = 'Rarely',
                                      '3' = 'Sometimes',
                                      '4' = 'Often',
                                      '5' = 'Always')),
    hfe_avail8 = list( Description = 'How often are the following foods/drinks available in your home: 100% fruit juice',
                       Levels = list ('1' = 'Never',
                                      '2' = 'Rarely',
                                      '3' = 'Sometimes',
                                      '4' = 'Often',
                                      '5' = 'Always')),
    hfe_avail9 = list( Description = 'How often are the following foods/drinks available in your home: Juice drinks (e.g., Sunny Delight)',
                       Levels = list ('1' = 'Never',
                                      '2' = 'Rarely',
                                      '3' = 'Sometimes',
                                      '4' = 'Often',
                                      '5' = 'Always')),
    hfe_avail10 = list( Description = 'How often are the following foods/drinks available in your home: Regular sodas with sugar',
                       Levels = list ('1' = 'Never',
                                      '2' = 'Rarely',
                                      '3' = 'Sometimes',
                                      '4' = 'Often',
                                      '5' = 'Always')),
    hfe_avail11 = list( Description = 'How often are the following foods/drinks available in your home: Diet or sugar free sodas',
                       Levels = list ('1' = 'Never',
                                      '2' = 'Rarely',
                                      '3' = 'Sometimes',
                                      '4' = 'Often',
                                      '5' = 'Always')),
    hfe_avail12 = list( Description = 'How often are the following foods/drinks available in your home: Sports drinks (e.g., Gatorade)',
                       Levels = list ('1' = 'Never',
                                      '2' = 'Rarely',
                                      '3' = 'Sometimes',
                                      '4' = 'Often',
                                      '5' = 'Always')),
    hfe_avail13 = list( Description = 'How often are the following foods/drinks available in your home: Fruit roll-ups or other dried fruit',
                       Levels = list ('1' = 'Never',
                                      '2' = 'Rarely',
                                      '3' = 'Sometimes',
                                      '4' = 'Often',
                                      '5' = 'Always')),
    hfe_avail14 = list( Description = 'How often are the following foods/drinks available in your home: Regular or 2% milk',
                       Levels = list ('1' = 'Never',
                                      '2' = 'Rarely',
                                      '3' = 'Sometimes',
                                      '4' = 'Often',
                                      '5' = 'Always')),
    hfe_avail15 = list( Description = 'How often are the following foods/drinks available in your home: 1% or fat-free milk',
                       Levels = list ('1' = 'Never',
                                      '2' = 'Rarely',
                                      '3' = 'Sometimes',
                                      '4' = 'Often',
                                      '5' = 'Always')),
    hfe_avail16 = list( Description = 'How often are the following foods/drinks available in your home: Sweetened breakfast cereal',
                       Levels = list ('1' = 'Never',
                                      '2' = 'Rarely',
                                      '3' = 'Sometimes',
                                      '4' = 'Often',
                                      '5' = 'Always')),
    hfe_avail17 = list( Description = 'How often are the following foods/drinks available in your home: Unsweetened breakfast cereal',
                       Levels = list ('1' = 'Never',
                                      '2' = 'Rarely',
                                      '3' = 'Sometimes',
                                      '4' = 'Often',
                                      '5' = 'Always')),
    hfe_like1 = list( Description = 'My Child Likes: Low-fat versions of foods like salad dressing and cheeses',
                      Levels = list ('1' = 'Strongly disagree',
                                     '2' = 'Somewhat disagree',
                                     '3' = 'Neutral',
                                     '4' = 'Somewhat agree',
                                     '5' = 'Strongly agree')),
    hfe_like2 = list( Description = 'My Child Likes: Fruits',
                      Levels = list ('1' = 'Strongly disagree',
                                     '2' = 'Somewhat disagree',
                                     '3' = 'Neutral',
                                     '4' = 'Somewhat agree',
                                     '5' = 'Strongly agree')),
    hfe_like3 = list( Description = 'My Child Likes: Vegetables',
                      Levels = list ('1' = 'Strongly disagree',
                                     '2' = 'Somewhat disagree',
                                     '3' = 'Neutral',
                                     '4' = 'Somewhat agree',
                                     '5' = 'Strongly agree')),
    hfe_like4 = list( Description = 'My Child Likes: Non-fried snacks like pretzels or baked chips',
                      Levels = list ('1' = 'Strongly disagree',
                                     '2' = 'Somewhat disagree',
                                     '3' = 'Neutral',
                                     '4' = 'Somewhat agree',
                                     '5' = 'Strongly agree')),
    hfe_like5 = list( Description = 'My Child Likes: 1%, skim or nonfat milk',
                      Levels = list ('1' = 'Strongly disagree',
                                     '2' = 'Somewhat disagree',
                                     '3' = 'Neutral',
                                     '4' = 'Somewhat agree',
                                     '5' = 'Strongly agree')),
    hfe_like6 = list( Description = 'My Child Likes: Dessert items such as ice cream, cake, and cookies',
                      Levels = list ('1' = 'Strongly disagree',
                                     '2' = 'Somewhat disagree',
                                     '3' = 'Neutral',
                                     '4' = 'Somewhat agree',
                                     '5' = 'Strongly agree')),
    hfe_like7 = list( Description = 'My Child Likes: Fried foods like french fries or chips',
                      Levels = list ('1' = 'Strongly disagree',
                                     '2' = 'Somewhat disagree',
                                     '3' = 'Neutral',
                                     '4' = 'Somewhat agree',
                                     '5' = 'Strongly agree')),
    hfe_like8 = list( Description = 'My Child Likes: Only a few foods',
                      Levels = list ('1' = 'Strongly disagree',
                                     '2' = 'Somewhat disagree',
                                     '3' = 'Neutral',
                                     '4' = 'Somewhat agree',
                                     '5' = 'Strongly agree')),
    hfe_shop1 = list( Description = 'In the store where you usually by groceries: Low-fat foods cost too much',
                      Levels = list ('1' = 'Strongly disagree',
                                     '2' = 'Somewhat disagree',
                                     '3' = 'Neutral',
                                     '4' = 'Somewhat agree',
                                     '5' = 'Strongly agree')),
    hfe_shop2 = list( Description = 'In the store where you usually by groceries: There is a large selection of fresh fruits and vegetables',
                      Levels = list ('1' = 'Strongly disagree',
                                     '2' = 'Somewhat disagree',
                                     '3' = 'Neutral',
                                     '4' = 'Somewhat agree',
                                     '5' = 'Strongly agree')),
    hfe_shop3 = list( Description = 'In the store where you usually by groceries: There is a large selection of low-fat products available',
                      Levels = list ('1' = 'Strongly disagree',
                                     '2' = 'Somewhat disagree',
                                     '3' = 'Neutral',
                                     '4' = 'Somewhat agree',
                                     '5' = 'Strongly agree')),
    hfe_shop4 = list( Description = 'In the store where you usually by groceries: The condition of fresh fruits and vegetables is poor',
                      Levels = list ('1' = 'Strongly disagree',
                                     '2' = 'Somewhat disagree',
                                     '3' = 'Neutral',
                                     '4' = 'Somewhat agree',
                                     '5' = 'Strongly agree')),
    hfe_shop5 = list( Description = 'In the store where you usually by groceries: Fruits and vegetables cost too much',
                      Levels = list ('1' = 'Strongly disagree',
                                     '2' = 'Somewhat disagree',
                                     '3' = 'Neutral',
                                     '4' = 'Somewhat agree',
                                     '5' = 'Strongly agree')),
    hfe_shoploc1 = list( Description = 'How often do you/the main shopper in your family go to: Large supermarket or discount warehouse',
                      Levels = list ('1' = 'Never',
                                     '2' = 'Rarely',
                                     '3' = 'Sometimes',
                                     '4' = 'Often',
                                     '5' = 'Always')),
    hfe_shoploc2 = list( Description = 'How often do you/the main shopper in your family go to: Small to medium food store',
                         Levels = list ('1' = 'Never',
                                        '2' = 'Rarely',
                                        '3' = 'Sometimes',
                                        '4' = 'Often',
                                        '5' = 'Always')),
    hfe_shoploc3 = list( Description = 'How often do you/the main shopper in your family go to: Convenience Store',
                         Levels = list ('1' = 'Never',
                                        '2' = 'Rarely',
                                        '3' = 'Sometimes',
                                        '4' = 'Often',
                                        '5' = 'Always')),
    hfe_shoploc4 = list( Description = 'How often do you/the main shopper in your family go to: Farmer\'s market/produce stand',
                         Levels = list ('1' = 'Never',
                                        '2' = 'Rarely',
                                        '3' = 'Sometimes',
                                        '4' = 'Often',
                                        '5' = 'Always')),
    hfe_shoploc5 = list( Description = 'How often do you/the main shopper in your family go to: specify other location'),
    hfe_shoploc5a = list( Description = 'How often do you/the main shopper in your family go to: locations otherwise specified',
                         Levels = list ('1' = 'Never',
                                        '2' = 'Rarely',
                                        '3' = 'Sometimes',
                                        '4' = 'Often',
                                        '5' = 'Always')),
    hfe_eatout1 = list( Description = 'How often does your child eat breakfast away from home: ',
                        Levels = list ('1' = 'Never or almost never',
                                       '2' = 'Less than 1 time per week',
                                       '3' = '1-2 times per week',
                                       '4' = '3-4 times per week',
                                       '5' = '5 or more times per week')),
    hfe_eatout2 = list( Description = 'How often does your child eat lunch away from home: ',
                        Levels = list ('1' = 'Never or almost never',
                                       '2' = 'Less than 1 time per week',
                                       '3' = '1-2 times per week',
                                       '4' = '3-4 times per week',
                                       '5' = '5 or more times per week')),
    hfe_eatout3 = list( Description = 'How often does your child eat dinner away from home: ',
                        Levels = list ('1' = 'Never or almost never',
                                       '2' = 'Less than 1 time per week',
                                       '3' = '1-2 times per week',
                                       '4' = '3-4 times per week',
                                       '5' = '5 or more times per week')),
    hfe_eatout4 = list( Description = 'How often does your child eat snacks away from home: ',
                        Levels = list ('1' = 'Never or almost never',
                                       '2' = 'Less than 1 time per week',
                                       '3' = '1-2 times per week',
                                       '4' = '3-4 times per week',
                                       '5' = '5 or more times per week')),
    hfe_eatout5 = list( Description = 'How often does he/she eat at or from: Restaurant with waiter/waitress service or a buffet restaurant',
                        Levels = list ('1' = 'Never or almost never',
                                       '2' = 'Less than 1 time per week',
                                       '3' = '1-2 times per week',
                                       '4' = '3-4 times per week',
                                       '5' = '5 or more times per week')),
    hfe_eatout6 = list( Description = 'How often does he/she eat at or from: School cafeteria (during school)',
                        Levels = list ('1' = 'Never or almost never',
                                       '2' = 'Less than 1 time per week',
                                       '3' = '1-2 times per week',
                                       '4' = '3-4 times per week',
                                       '5' = '5 or more times per week')),
    hfe_eatout7 = list( Description = 'How often does he/she eat at or from: Fast food restaurant',
                        Levels = list ('1' = 'Never or almost never',
                                       '2' = 'Less than 1 time per week',
                                       '3' = '1-2 times per week',
                                       '4' = '3-4 times per week',
                                       '5' = '5 or more times per week')),
    hfe_eatout8 = list( Description = 'How often does he/she eat at or from: Convenience store (such as 7-11, AM/PM)',
                        Levels = list ('1' = 'Never or almost never',
                                       '2' = 'Less than 1 time per week',
                                       '3' = '1-2 times per week',
                                       '4' = '3-4 times per week',
                                       '5' = '5 or more times per week')),
    hfe_eatout9 = list( Description = 'How often does he/she eat at or from: Deli or bakery (stand-alone or in a shop)',
                        Levels = list ('1' = 'Never or almost never',
                                       '2' = 'Less than 1 time per week',
                                       '3' = '1-2 times per week',
                                       '4' = '3-4 times per week',
                                       '5' = '5 or more times per week')),
    hfe_eatout10 = list( Description = 'How often does he/she eat at or from: Vending machine outside of school',
                        Levels = list ('1' = 'Never or almost never',
                                       '2' = 'Less than 1 time per week',
                                       '3' = '1-2 times per week',
                                       '4' = '3-4 times per week',
                                       '5' = '5 or more times per week')),
    hfe_eatout11 = list( Description = 'How often does he/she eat at or from: Pizza place',
                        Levels = list ('1' = 'Never or almost never',
                                       '2' = 'Less than 1 time per week',
                                       '3' = '1-2 times per week',
                                       '4' = '3-4 times per week',
                                       '5' = '5 or more times per week')),
    hfe_nbh1 = list( Description = 'The stores in your neighborhood, regardless of whether you shop at them: There is a large selection of low-fat products available',
                     Levels = list ('1' = 'Strongly disagree',
                                    '2' = 'Somewhat disagree',
                                    '3' = 'Neutral',
                                    '4' = 'Somewhat agree',
                                    '5' = 'Strongly agree')),
    hfe_nbh2 = list( Description = 'The stores in your neighborhood, regardless of whether you shop at them: The fresh produce is usually of high quality',
                     Levels = list ('1' = 'Strongly disagree',
                                    '2' = 'Somewhat disagree',
                                    '3' = 'Neutral',
                                    '4' = 'Somewhat agree',
                                    '5' = 'Strongly agree')),
    hfe_nbh3 = list( Description = 'The stores in your neighborhood, regardless of whether you shop at them: There is a large selection of fresh fruits and vegetables',
                     Levels = list ('1' = 'Strongly disagree',
                                    '2' = 'Somewhat disagree',
                                    '3' = 'Neutral',
                                    '4' = 'Somewhat agree',
                                    '5' = 'Strongly agree')),
    hfe_nbh4 = list( Description = 'The stores in your neighborhood, regardless of whether you shop at them: Fruits and vegetables cost too much',
                     Levels = list ('1' = 'Strongly disagree',
                                    '2' = 'Somewhat disagree',
                                    '3' = 'Neutral',
                                    '4' = 'Somewhat agree',
                                    '5' = 'Strongly agree')),
    hfe_nbh5 = list( Description = 'The stores in your neighborhood, regardless of whether you shop at them: Low fat foods cost too much',
                     Levels = list ('1' = 'Strongly disagree',
                                    '2' = 'Somewhat disagree',
                                    '3' = 'Neutral',
                                    '4' = 'Somewhat agree',
                                    '5' = 'Strongly agree')),
    hfe_shop_taste = list( Description = 'When you purchase food for you/your family, how important is: taste',
                           Levels = list ('1' = 'Not at all important',
                                          '2' = 'Low importance',
                                          '3' = 'Neutral',
                                          '4' = 'A little important',
                                          '5' = 'Very important')),
    hfe_shop_nutr = list( Description = 'When you purchase food for you/your family, how important is: nutrition',
                          Levels = list ('1' = 'Not at all important',
                                         '2' = 'Low importance',
                                         '3' = 'Neutral',
                                         '4' = 'A little important',
                                         '5' = 'Very important')),
    hfe_shop_cost = list( Description = 'When you purchase food for you/your family, how important is: cost',
                          Levels = list ('1' = 'Not at all important',
                                         '2' = 'Low importance',
                                         '3' = 'Neutral',
                                         '4' = 'A little important',
                                         '5' = 'Very important')),
    hfe_shop_convenience = list( Description = 'When you purchase food for you/your family, how important is: convienence',
                               Levels = list ('1' = 'Not at all important',
                                              '2' = 'Low importance',
                                              '3' = 'Neutral',
                                              '4' = 'A little important',
                                              '5' = 'Very important')),
    hfe_shop_weightcontrol = list( Description = 'When you purchase food for you/your family, how important is: weight control',
                                   Levels = list ('1' = 'Not at all important',
                                                  '2' = 'Low importance',
                                                  '3' = 'Neutral',
                                                  '4' = 'A little important',
                                                  '5' = 'Very important')),
    hfe_p_lunch_taste = list( Description = 'When you eat out at lunch, how important is: taste',
                              Levels = list ('1' = 'Not at all important',
                                             '2' = 'Low importance',
                                             '3' = 'Neutral',
                                             '4' = 'A little important',
                                             '5' = 'Very important')),
    hfe_p_lunch_nutr = list( Description = 'When you eat out at lunch, how important is: nutrition',
                             Levels = list ('1' = 'Not at all important',
                                            '2' = 'Low importance',
                                            '3' = 'Neutral',
                                            '4' = 'A little important',
                                            '5' = 'Very important')),
    hfe_p_lunch_cost = list( Description = 'When you eat out at lunch, how important is: cost',
                             Levels = list ('1' = 'Not at all important',
                                            '2' = 'Low importance',
                                            '3' = 'Neutral',
                                            '4' = 'A little important',
                                            '5' = 'Very important')),
    hfe_p_lunch_convenience = list( Description = 'When you eat out at lunch, how important is: convenience',
                                  Levels = list ('1' = 'Not at all important',
                                                 '2' = 'Low importance',
                                                 '3' = 'Neutral',
                                                 '4' = 'A little important',
                                                 '5' = 'Very important')),
    hfe_p_lunch_weightcontrol = list( Description = 'When you eat out at lunch, how important is: weight control',
                                      Levels = list ('1' = 'Not at all important',
                                                     '2' = 'Low importance',
                                                     '3' = 'Neutral',
                                                     '4' = 'A little important',
                                                     '5' = 'Very important')),
    hfe_eatout_taste = list( Description = 'When you eat out at dinner, how important is: taste',
                             Levels = list ('1' = 'Not at all important',
                                            '2' = 'Low importance',
                                            '3' = 'Neutral',
                                            '4' = 'A little important',
                                            '5' = 'Very important')),
    hfe_eatout_nutr = list( Description = 'When you eat out at dinner, how important is: nutrition',
                            Levels = list ('1' = 'Not at all important',
                                           '2' = 'Low importance',
                                           '3' = 'Neutral',
                                           '4' = 'A little important',
                                           '5' = 'Very important')),
    hfe_eatout_cost = list( Description = 'When you eat out at dinner, how important is: cost',
                            Levels = list ('1' = 'Not at all important',
                                           '2' = 'Low importance',
                                           '3' = 'Neutral',
                                           '4' = 'A little important',
                                           '5' = 'Very important')),
    hfe_eatout_convenience = list( Description = 'When you eat out at dinner, how important is: convenience',
                                 Levels = list ('1' = 'Not at all important',
                                                '2' = 'Low importance',
                                                '3' = 'Neutral',
                                                '4' = 'A little important',
                                                '5' = 'Very important')),
    hfe_eatout_weightcontrol = list( Description = 'When you eat out at dinner, how important is: weight control',
                                      Levels = list ('1' = 'Not at all important',
                                                     '2' = 'Low importance',
                                                     '3' = 'Neutral',
                                                     '4' = 'A little important',
                                                     '5' = 'Very important')),
    hfe_p4a = list( Description = 'How confident that you could consistently (e.g., 6 mo) motivate your self to: Stick to low fat, low calorie foods when you feel bored, or tense',
                    Levels = list ('1' = 'Definitely can\'t',
                                   '2' = 'Probably can\'t',
                                   '3' = 'Maybe',
                                   '4' = 'Probably can',
                                   '5' = 'Definitely can')),
    hfe_p4b = list( Description = 'How confident that you could consistently (e.g., 6 mo) motivate your self to: Stick to low fat, low calorie foods when dining with friends or co-workers',
                    Levels = list ('1' = 'Definitely can\'t',
                                   '2' = 'Probably can\'t',
                                   '3' = 'Maybe',
                                   '4' = 'Probably can',
                                   '5' = 'Definitely can')),
    hfe_p4c = list( Description = 'How confident that you could consistently (e.g., 6 mo) motivate your self to: Eat smaller portions',
                    Levels = list ('1' = 'Definitely can\'t',
                                   '2' = 'Probably can\'t',
                                   '3' = 'Maybe',
                                   '4' = 'Probably can',
                                   '5' = 'Definitely can')),
    hfe_p4d = list( Description = 'How confident that you could consistently (e.g., 6 mo) motivate your self to: Eat meatless (vegetarian) entrees for dinner',
                    Levels = list ('1' = 'Definitely can\'t',
                                   '2' = 'Probably can\'t',
                                   '3' = 'Maybe',
                                   '4' = 'Probably can',
                                   '5' = 'Definitely can')),
    hfe_p4e = list( Description = 'How confident that you could consistently (e.g., 6 mo) motivate your self to: Substitute low or non-fat milk for whole milk',
                    Levels = list ('1' = 'Definitely can\'t',
                                   '2' = 'Probably can\'t',
                                   '3' = 'Maybe',
                                   '4' = 'Probably can',
                                   '5' = 'Definitely can')),
    hfe_p4f = list( Description = 'How confident that you could consistently (e.g., 6 mo) motivate your self to: Eat poultry and fish instead of red meat at dinner',
                    Levels = list ('1' = 'Definitely can\'t',
                                   '2' = 'Probably can\'t',
                                   '3' = 'Maybe',
                                   '4' = 'Probably can',
                                   '5' = 'Definitely can')),
    hfe_p4g = list( Description = 'How confident that you could consistently (e.g., 6 mo) motivate your self to: Eat a portion of fruit or vegetables at every meal',
                    Levels = list ('1' = 'Definitely can\'t',
                                   '2' = 'Probably can\'t',
                                   '3' = 'Maybe',
                                   '4' = 'Probably can',
                                   '5' = 'Definitely can')),
    hfe_p5a = list( Description = 'How often do the following prevent you from eating healthy foods: Eating my favorite high calorie foods satisfies my hunger',
                    Levels = list ('1' = 'Never',
                                   '2' = 'Rarely',
                                   '3' = 'Sometimes',
                                   '4' = 'Often',
                                   '5' = 'Very Often')),
    hfe_p5b = list( Description = 'How often do the following prevent you from eating healthy foods: I enjoy eating high calorie foods',
                    Levels = list ('1' = 'Never',
                                   '2' = 'Rarely',
                                   '3' = 'Sometimes',
                                   '4' = 'Often',
                                   '5' = 'Very Often')),
    hfe_p5c = list( Description = 'How often do the following prevent you from eating healthy foods: I am confused by conflicting advice I see about  eating healthy',
                    Levels = list ('1' = 'Never',
                                   '2' = 'Rarely',
                                   '3' = 'Sometimes',
                                   '4' = 'Often',
                                   '5' = 'Very Often')),
    hfe_p5d = list( Description = 'How often do the following prevent you from eating healthy foods: I would rather eat sweets or high fat snacks than fruits  and vegetables',
                    Levels = list ('1' = 'Never',
                                   '2' = 'Rarely',
                                   '3' = 'Sometimes',
                                   '4' = 'Often',
                                   '5' = 'Very Often')),
    hfe_p5e = list( Description = 'How often do the following prevent you from eating healthy foods: The length of time it takes to prepare fruits and vegetables',
                    Levels = list ('1' = 'Never',
                                   '2' = 'Rarely',
                                   '3' = 'Sometimes',
                                   '4' = 'Often',
                                   '5' = 'Very Often')),
    hfe_p5f = list( Description = 'How often do the following prevent you from eating healthy foods: I think high calorie foods taste better',
                    Levels = list ('1' = 'Never',
                                   '2' = 'Rarely',
                                   '3' = 'Sometimes',
                                   '4' = 'Often',
                                   '5' = 'Very Often')),
    hfe_p5g = list( Description = 'How often do the following prevent you from eating healthy foods: Eating fruits and vegetables does not satisfy my  hunger',
                    Levels = list ('1' = 'Never',
                                   '2' = 'Rarely',
                                   '3' = 'Sometimes',
                                   '4' = 'Often',
                                   '5' = 'Very Often')),
    hfe_p6a = list( Description = 'During the past six months, how often did your family or anyone living in your household do or say the following: ',
                    Levels = list ('0' = 'Never or Rarely',
                                   '1' = 'Sometimes',
                                   '2' = 'Often',
                                   '3' = 'Almost Always')),
    hfe_p6b = list( Description = 'During the past six months, how often did your family or anyone living in your household do or say the following: Eat high fat or high calorie foods in front of you',
                    Levels = list ('1' = 'Never or Rarely',
                                   '2' = 'Sometimes',
                                   '3' = 'Often',
                                   '4' = 'Almost Always')),
    hfe_p6c = list( Description = 'During the past six months, how often did your family or anyone living in your household do or say the following: Join you in eating a healthy meal',
                    Levels = list ('1' = 'Never or Rarely',
                                   '2' = 'Sometimes',
                                   '3' = 'Often',
                                   '4' = 'Almost Always')),
    hfe_p6d = list( Description = 'During the past six months, how often did your family or anyone living in your household do or say the following: Bring home foods you\'re trying not to eat',
                    Levels = list ('1' = 'Never or Rarely',
                                   '2' = 'Sometimes',
                                   '3' = 'Often',
                                   '4' = 'Almost Always')),
    hfe_p6e = list( Description = 'During the past six months, how often did your family or anyone living in your household do or say the following: Encourage you to eat low fat, low calorie foods',
                    Levels = list ('1' = 'Never or Rarely',
                                    '2' = 'Sometimes',
                                    '3' = 'Often',
                                    '4' = 'Almost Always')),
    hfe_p6f = list( Description = 'During the past six months, how often did your family or anyone living in your household do or say the following: Get angry when you encouraged them to eat low fat, low calorie foods',
                    Levels = list ('1' = 'Never or Rarely',
                                   '2' = 'Sometimes',
                                   '3' = 'Often',
                                   '4' = 'Almost Always')),
    hfe_p6g = list( Description = 'During the past six months, how often did your family or anyone living in your household do or say the following: Complimented you on your healthy eating habits',
                    Levels = list ('1' = 'Never or Rarely',
                                   '2' = 'Sometimes',
                                   '3' = 'Often',
                                   '4' = 'Almost Always')),
    hfe_modeling = list( Description = 'Parental modeling of healthy eating patterns.', 
                         Derivative = TRUE),
    hfe_restrictive_practices = list( Description = 'Restrictive feeding practices.', 
                      Derivative = TRUE),
    hfe_permissive_practices = list( Description = 'Permissive feeding practices.', 
                           Derivative = TRUE),
    hfe_pressure_eat = list( Description = 'Parental pressure to eat.', 
                    Derivative = TRUE),
    hfe_food_rules = list( Description = 'Number of family food rules endorsed.', 
                           Derivative = TRUE),
    hfe_highED_homefood = list( Description = 'Home availability of higher-ED/less healthy foods.', 
                     Derivative = TRUE),
    hfe_lowED_homefood = list( Description = 'Home availability of lower-ED/healthier foods.', 
                     Derivative = TRUE),
    hfe_highED_childlike = list( Description = 'Child liking for higher-ED/less healthy foods.', 
                               Derivative = TRUE),
    hfe_lowED_childlike = list( Description = 'Child liking for lower-ED/healthier foods.', 
                               Derivative = TRUE),
    hfe_eat_away = list( Description = 'Frequency of child eating away from home.', 
                               Derivative = TRUE),
    hfe_eat_school = list( Description = 'Frequency of child eating at school.', 
                               Derivative = TRUE),
    hfe_eatout = list( Description = 'Frequency of child eating out.', 
                               Derivative = TRUE),
    hfe_nbh_grocery_available = list( Description = 'Perceived availability of fresh/healthy foods at neighborhood grocery stores.', 
                       Derivative = TRUE),
    hfe_nbh_grocery_cost = list( Description = 'Perceived cost of healthy foods at neighborhood grocery stores.', 
                       Derivative = TRUE),
    hfe_p_healthyeating_conf = list( Description = 'Parent\'s confidence in following healthy eating patterns.', 
                       Derivative = TRUE),
    hfe_p_healthyeating_barriers = list( Description = 'Parent impacted by healthy eating barriers (high ED food tempations).', 
                       Derivative = TRUE),
    hfe_fam_pos_influence = list( Description = 'Family members positively influence healthy eating behaviors.', 
                       Derivative = TRUE),
    hfe_fam_neg_influence = list( Description = 'Family members negatively influence healthy eating behaviors.', 
                                  Derivative = TRUE))
  
  # convert formatting to JSON
  nki_hfe_json <- RJSONIO::toJSON(nki_hfe_list, pretty = TRUE)
  
  # double check
  if (isFALSE(RJSONIO::isValidJSON(nki_hfe_json, asText = TRUE))){
    print('nki_hfe JSON file may be invalid')
  }
  
  return(nki_hfe_json)
  
}