#' json_cbq: Generates a json file for the Child Behavior Questionnaire
#'
#' This function generates a json file for the scored Child Behavior Questionnaire and raw participant responses. This function provides accurate json files ONLY if data is processed using score_cbq function in dataprepr and is only accurate for data collected in Study BRAKE.
#'
#' @return A json file documenting the raw inputs and scored values for the Child Behavior Questionnaire
#'
#'
#' @export

json_cbq <- function() {
  
  cbq_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Child Behavior Questionnaire',
      Reference = 'Putnam SP, Rothbart MK. Development of Short and Very Short Forms of the Children’s Behavior Questionnaire. Journal of Personality Assessment. 2006;87(1):102-112. doi:10.1207/s15327752jpa8701_09', 
      TermURL = 'https://pubmed.ncbi.nlm.nih.gov/16856791/'),
    participant_id = list( Description = 'participant id number'),
    cbq1 = list( Description = 'Seems always in a big hurry to get from one place to another.',
                 Levels = list ('1' =	'extremely untrue of your child',
                                '2'	= 'quite untrue of your child',
                                '3' =	'slightly untrue of your child',
                                '4'	= 'neither true nor false of your child',
                                '5'	= 'slightly true of your child',
                                '6'	= 'quite true of your child',
                                '7'	= 'extremely true of your child',
                                'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq2 = list( Description = 'Gets angry when told s/he has to go to bed.',
                 Levels = list ('1' =	'extremely untrue of your child',
                                '2'	= 'quite untrue of your child',
                                '3' =	'slightly untrue of your child',
                                '4'	= 'neither true nor false of your child',
                                '5'	= 'slightly true of your child',
                                '6'	= 'quite true of your child',
                                '7'	= 'extremely true of your child',
                                'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq3 = list( Description = 'Is not very bothered by pain.',
                 Levels = list ('1' =	'extremely untrue of your child',
                                '2'	= 'quite untrue of your child',
                                '3' =	'slightly untrue of your child',
                                '4'	= 'neither true nor false of your child',
                                '5'	= 'slightly true of your child',
                                '6'	= 'quite true of your child',
                                '7'	= 'extremely true of your child',
                                'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq4 = list( Description = 'Likes going down high slides or other adventurous activities.',
                 Levels = list ('1' =	'extremely untrue of your child',
                                '2'	= 'quite untrue of your child',
                                '3' =	'slightly untrue of your child',
                                '4'	= 'neither true nor false of your child',
                                '5'	= 'slightly true of your child',
                                '6'	= 'quite true of your child',
                                '7'	= 'extremely true of your child',
                                'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq5 = list( Description = 'Notices the smoothness or roughness of objects s/he touches.',
                 Levels = list ('1' =	'extremely untrue of your child',
                                '2'	= 'quite untrue of your child',
                                '3' =	'slightly untrue of your child',
                                '4'	= 'neither true nor false of your child',
                                '5'	= 'slightly true of your child',
                                '6'	= 'quite true of your child',
                                '7'	= 'extremely true of your child',
                                'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq6 = list( Description = 'Gets so worked up before an exciting event that s/he has trouble sitting still.',
                 Levels = list ('1' =	'extremely untrue of your child',
                                '2'	= 'quite untrue of your child',
                                '3' =	'slightly untrue of your child',
                                '4'	= 'neither true nor false of your child',
                                '5'	= 'slightly true of your child',
                                '6'	= 'quite true of your child',
                                '7'	= 'extremely true of your child',
                                'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq7 = list( Description = 'Usually rushes into an activity without thinking about it.',
                 Levels = list ('1' =	'extremely untrue of your child',
                                '2'	= 'quite untrue of your child',
                                '3' =	'slightly untrue of your child',
                                '4'	= 'neither true nor false of your child',
                                '5'	= 'slightly true of your child',
                                '6'	= 'quite true of your child',
                                '7'	= 'extremely true of your child',
                                'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq8 = list( Description = 'Cries sadly when a favorite toy gets lost or broken.',
                 Levels = list ('1' =	'extremely untrue of your child',
                                '2'	= 'quite untrue of your child',
                                '3' =	'slightly untrue of your child',
                                '4'	= 'neither true nor false of your child',
                                '5'	= 'slightly true of your child',
                                '6'	= 'quite true of your child',
                                '7'	= 'extremely true of your child',
                                'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq9 = list( Description = 'Becomes quite uncomfortable when cold and/or wet.',
                 LLevels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq10 = list( Description = 'Likes to play so wild and recklessly that s/he might get hurt.',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq11 = list( Description = 'Seems to be at ease with almost any person.',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq12 = list( Description = 'Tends to run rather than walk from room to room.',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq13 = list( Description = 'Notices it when parents are wearing new clothing.',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq14 = list( Description = 'Has temper tantrums when s/he doesn\'t get what s/he wants.',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq15 = list( Description = 'Gets very enthusiastic about the things s/he does.',
                 Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq16 = list( Description = 'When practicing an activity, has a hard time keeping her/his mind on it.',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq17 = list( Description = 'Is afraid of burglars or the "boogie man."',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq18 = list( Description = 'When outside, often sits quietly.',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq19 = list( Description = 'Enjoys funny stories but usually doesn\'t laugh at them.',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq20 = list( Description = 'Tends to become sad if the family\'s plans don\'t work out.',
                 Levels = list ('1' =	'extremely untrue of your child',
                                '2'	= 'quite untrue of your child',
                                '3' =	'slightly untrue of your child',
                                '4'	= 'neither true nor false of your child',
                                '5'	= 'slightly true of your child',
                                '6'	= 'quite true of your child',
                                '7'	= 'extremely true of your child',
                                'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq21 = list( Description = 'My child complains about being overweight',
                 Levels = list ('1' =	'extremely untrue of your child',
                                '2'	= 'quite untrue of your child',
                                '3' =	'slightly untrue of your child',
                                '4'	= 'neither true nor false of your child',
                                '5'	= 'slightly true of your child',
                                '6'	= 'quite true of your child',
                                '7'	= 'extremely true of your child',
                                'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq22 = list( Description = 'My child complains about being teased',
                 Levels = list ('1' =	'extremely untrue of your child',
                                '2'	= 'quite untrue of your child',
                                '3' =	'slightly untrue of your child',
                                '4'	= 'neither true nor false of your child',
                                '5'	= 'slightly true of your child',
                                '6'	= 'quite true of your child',
                                '7'	= 'extremely true of your child',
                                'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq23 = list( Description = 'My child complains about not having enough friends',
                 Levels = list ('1' =	'extremely untrue of your child',
                                '2'	= 'quite untrue of your child',
                                '3' =	'slightly untrue of your child',
                                '4'	= 'neither true nor false of your child',
                                '5'	= 'slightly true of your child',
                                '6'	= 'quite true of your child',
                                '7'	= 'extremely true of your child',
                                'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq24 = list( Description = 'My child complains about being unattractive',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq25 = list( Description = 'My child complains about not fitting into clothes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq26 = list( Description = 'My child does not notice when his/her behavior causes negative reactions',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq27 = list( Description = 'My child reacts more strongly to situations than other children',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq28 = list( Description = 'My child has trouble remembering things, even for a few minutes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq29 = list( Description = 'My child makes careless errors',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq30 = list( Description = 'My child becomes upset with new situations',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq31 = list( Description = 'Confidence deal with: My child throws a tantrum about food',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq32 = list( Description = 'My child has trouble concentrating on tasks, schoolwork, etc.',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq33 = list( Description = 'My child has poor handwriting',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq34 = list( Description = 'My child\'s mood changes frequently',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq35 = list( Description = 'My child has good ideas but cannot get them on paper',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq36 = list( Description = 'My child has trouble counting to three',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq37 = list( Description = 'My child leaves messes that others have to clean up',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq38 = list( Description = 'My child needs to be told when to begin a task even when willing',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq39 = list( Description = 'My child acts too wild or "out of control"',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq40 = list( Description = 'My child thinks too much about the same topic',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq41 = list( Description = 'My child forgets what he/she was doing',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq42 = list( Description = 'My child does not check work for mistakes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq43 = list( Description = 'My child\'s angry or tearful outbursts are intense but end suddenly',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq44 = list( Description = 'My child becomes overwhelmed by large assignments',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq45 = list( Description = 'My child loses lunch box, lunch money, permission slips, homework, etc.',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq46 = list( Description = 'My child needs help from an adult to stay on task',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq47 = list( Description = 'My child forgets to hand in homework, even when completed',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq48 = list( Description = 'My child has trouble putting the brakes on his/her actions',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq49 = list( Description = 'My child resists change of routine, foods, places, etc.',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq50 = list( Description = 'My child has trouble getting started on homework or tasks',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq51= list( Description = 'My child\'s mood is easily influenced by the situation',
                 Levels = list ('1' =	'extremely untrue of your child',
                                '2'	= 'quite untrue of your child',
                                '3' =	'slightly untrue of your child',
                                '4'	= 'neither true nor false of your child',
                                '5'	= 'slightly true of your child',
                                '6'	= 'quite true of your child',
                                '7'	= 'extremely true of your child',
                                'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq52 = list( Description = 'My child underestimates time needed to finish tasks',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq53 = list( Description = 'My child does not bring home homework, assignment sheets, materials, etc.',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq54 = list( Description = 'My child cannot find the front door of home',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq55 = list( Description = 'My child does not take initiative',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq56 = list( Description = 'My child becomes upset too easily',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq57 = list( Description = 'My child starts assignments or tasks at the last minute',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq58 = list( Description = 'My child has trouble moving from one activity to another',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq59 = list( Description = 'My child has trouble carrying out the actions needed to reach goals (saving money for special item, studying to get a good grade, etc.)',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq60 = list( Description = 'My child is disturbed by change of teacher or class',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq61 = list( Description = 'My child has trouble organizing activities with friends',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq62 = list( Description = 'My child becomes too silly',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq63 = list( Description = 'My child leaves a trail of belongings wherever he/she goes',
                  Levels = list ('1' =	'extremely untrue of your child',
                                 '2'	= 'quite untrue of your child',
                                 '3' =	'slightly untrue of your child',
                                 '4'	= 'neither true nor false of your child',
                                 '5'	= 'slightly true of your child',
                                 '6'	= 'quite true of your child',
                                 '7'	= 'extremely true of your child',
                                 'NA' = 'cannot answer because you have never seen the child in that situation')),
    cbq_inhibit = list( Description = 'Inhibition', 
                     Derivative = TRUE),
    cbq_inhibit_t = list( Description = 'Inhibition T-score', 
                           Derivative = TRUE),
    cbq_inhibit_p = list( Description = 'Inhibition Percentile', 
                           Derivative = TRUE),
    cbq_selfmon = list( Description = 'Self-Monitoring', 
                       Derivative = TRUE),
    cbq_selfmon_t = list( Description = 'Self-Monitoring T-score', 
                           Derivative = TRUE),
    cbq_selfmon_p = list( Description = 'Self-Monitoring Percentile', 
                           Derivative = TRUE),
    cbq_shift = list( Description = 'Shifting', 
                       Derivative = TRUE),
    cbq_shift_t = list( Description = 'Shifting T-score', 
                         Derivative = TRUE),
    cbq_shift_p = list( Description = 'Shifting Percentile', 
                         Derivative = TRUE),
    cbq_emcont = list( Description = 'Emotional Control', 
                       Derivative = TRUE),
    cbq_emcont_t = list( Description = 'Emotional Control T-score', 
                          Derivative = TRUE),
    cbq_emcont_p = list( Description = 'Emotional Control Percentile', 
                          Derivative = TRUE),
    cbq_initiate = list( Description = 'Initiate', 
                       Derivative = TRUE),
    cbq_initiate_t = list( Description = 'Initiate T-score', 
                            Derivative = TRUE),
    cbq_initiate_p = list( Description = 'Initiate Percentile', 
                            Derivative = TRUE),
    cbq_wm = list( Description = 'Working Memory', 
                          Derivative = TRUE),
    cbq_wm_t = list( Description = 'Working Memory T-score', 
                      Derivative = TRUE),
    cbq_wm_p = list( Description = 'Working Memory Percentile', 
                      Derivative = TRUE),
    cbq_planorg = list( Description = 'Planning/Organization', 
                          Derivative = TRUE),
    cbq_planorg_t = list( Description = 'Planning/Organization T-score', 
                           Derivative = TRUE),
    cbq_planorg_p = list( Description = 'Planning/Organization Percentile', 
                           Derivative = TRUE),
    cbq_taskmon = list( Description = 'Task Monitoring', 
                          Derivative = TRUE),
    cbq_taskmon_t = list( Description = 'Task Monitoring T-score', 
                           Derivative = TRUE),
    cbq_taskmon_p = list( Description = 'Task Monitoring Percentile', 
                           Derivative = TRUE),
    cbq_orgmat = list( Description = 'Organiation of Materials', 
                          Derivative = TRUE),
    cbq_orgmat_t = list( Description = 'Organiation of Materials T-score', 
                          Derivative = TRUE),
    cbq_orgmat_p = list( Description = 'Organiation of Materials Percentile', 
                          Derivative = TRUE),
    cbq_bri = list( Description = 'Behavioral Regulation Index', 
                          Derivative = TRUE),
    cbq_bri_t = list( Description = 'Behavioral Regulation Index T-score', 
                       Derivative = TRUE),
    cbq_bri_p = list( Description = 'Behavioral Regulation Index Percentile', 
                       Derivative = TRUE),
    cbq_eri = list( Description = 'Emotional Regulaiton Index', 
                       Derivative = TRUE),
    cbq_eri_t = list( Description = 'Emotional Regulaiton Index T-score', 
                       Derivative = TRUE),
    cbq_eri_p = list( Description = 'Emotional Regulaiton Index Percentile', 
                       Derivative = TRUE),
    cbq_cri = list( Description = 'Cognitive Regulation Index', 
                       Derivative = TRUE),
    cbq_cri_t = list( Description = 'Cognitive Regulation Index T-score', 
                       Derivative = TRUE),
    cbq_cri_p = list( Description = 'Cognitive Regulation Index Percentile', 
                       Derivative = TRUE),
    cbq_gec = list( Description = 'General Executive Composite', 
                       Derivative = TRUE),
    cbq_gec_t = list( Description = 'General Executive Composite T-score', 
                       Derivative = TRUE),
    cbq_gec_p = list( Description = 'General Executive Composite Percentile', 
                       Derivative = TRUE),
    cbq_negativity = list( Description = 'Negativity Check', 
                       Derivative = TRUE),
    cbq_negativity_p = list( Description = 'Negativity Check Percentile', 
                              Derivative = TRUE),
    cbq_negativity_cat = list( Description = 'Negativity Check Category',
                                  Levels = list ('0' = '<=98',
                                                 '1' = '99', 
                                                 '2' = '>99'),
                                  Derivative = TRUE),
    cbq_inconsistency = list( Description = 'Inconsistency Check', 
                       Derivative = TRUE),
    cbq_inconsistency_p = list( Description = 'Inconsistency Check Percentile', 
                                 Derivative = TRUE),
    cbq_inconsistency_cat = list( Description = 'Inconsistency Check Category', 
                                 Levels = list ('0' = '<=98',
                                                '1' = '99', 
                                                '2' = '>99'),
                                 Derivative = TRUE),
    cbq_infrequency = list( Description = 'Infrequency', 
                                 Derivative = TRUE),
    cbq_infrequency_p = list( Description = 'Infrequency Percentile', 
                               Derivative = TRUE),
    cbq_infrequency_cat = list( Description = 'Infrequency Category', 
                                   Levels = list ('0' = 'Acceptable',
                                                  '1' = 'Questionable'),
                                   Derivative = TRUE))
  

  # convert formatting to JSON
  cbq_json <- RJSONIO::toJSON(cbq_list, pretty = TRUE)
  
  # double check
  if (isFALSE(RJSONIO::isValidJSON(cbq_json, asText = TRUE))){
    print('cbq JSON file may be invalid')
  }
  
  return(cbq_json)
  
}