#' json_intake_de: Generates a json file for intake data from double entry REDCap
#'
#' This function generates a json file for intake data
#'
#' @return A string with data stored in JSON format containing meta-data for intake data
#'
#'
#' @export

json_intake_de <- function() {

  intake_de_list <- list(
    participant_id = list( Description = 'participant id number'),
    session_id = list( Description = 'BIDS session ID indicating when data was collected',
                       Levels = list ('ses-baseline' = 'baseline',
                                      'ses-followup' = '1-year follow-up')),
    visit_protocol = list( Description = 'child visit protocol number (does not necessarilty reflect visit order. See participants.tsv for child visit protocol dates)',
                           Levels = list ('1' =	'Child visit protocol 1 (baseline)',
                                          '2' =	'Child visit protocol 2 (baseline)',
                                          '3'	= 'Child visit protocol 3 (follow-up')),
    visit_date = list( Description = 'Date of visit',
                       Unit = 'YYYY-MM-DD'),
    mac_pre_w_o_plate = list( Description = 'Pre-meal weight of macaroni and cheese without plate',
                                Unit = "grams"),
    mac_pre_w_plate = list( Description = 'Pre-meal weight of macaroni and cheese with plate',
                                 Unit = "grams"),
    cknug_pre_w_o_plate = list( Description = 'Pre-meal weight of chicken nuggets without plate',
                                   Unit = "grams"),
    cknug_pre_w_plate = list( Description = 'Pre-meal weight of chicken nuggets with a plate',
                                 Unit = "grams"),
    grapes_pre_w_o_plate = list( Description = 'Pre-meal weight of grapes without plate',
                                         Unit = "grams"),
    grapes_pre_w_plate = list( Description = 'Pre-meal weight of grapes with plate',
                                       Unit = "grams"),
    carrots_pre_w_o_plate = list( Description = 'Post-meal weight of carrots without a plate',
                                        Unit = "grams"),
    carrots_pre_w_plate = list( Description = 'Pre-meal weight of carrots with plate',
                                 Unit = "grams"),
    ketchup_pre_w_o_plate = list( Description = 'Pre-meal weight of ketchup without plate',
                               Unit = "grams"),
    ketchup_pre_w_plate = list( Description = 'Pre-meal weight of ketchup with plate',
                                  Unit = "grams"),
    water_pre_w_o_plate = list( Description = 'Post-meal weight of water without cup',
                                Unit = "grams"),
    water_pre_w_plate = list( Description = 'Pre-meal weight of water with cup',
                                 Unit = "grams"),
    mac_post_w_plate = list( Description = 'Post-meal weight of macaroni and cheese with plate',
                            Unit = "grams"),
    cknug_post_w_plate = list( Description = 'Post-meal weight of chicken nuggets with a plate',
                              Unit = "grams"),
    grapes_post_w_plate = list( Description = 'Post-meal weight of grapes with plate',
                               Unit = "grams"),
    carrots_post_w_plate = list( Description = 'Post-meal weight of carrots with plate',
                                Unit = "grams"),
    ketchup_post_w_plate = list( Description = 'Post-meal weight of ketchup with plate',
                                Unit = "grams"),
    water_post_w_plate = list( Description = 'Post-meal weight of water with cup',
                              Unit = "grams"),
   
    hershey_pre_w_o_plate = list( Description = 'Pre-EAH weight of Hersheys kiss without plate',
                               Unit = "grams"),
    hershey_pre_w_plate = list( Description = 'Pre-EAH weight of Hersheys kiss with plate',
                             Unit = "grams"),
    starburst_pre_w_o_plate = list( Description = 'Pre-EAH weight of starbursts without plate',
                                    Unit = "grams"),
    starburst_pre_w_plate = list( Description = 'Pre-EAH weight of starbursts with plate',
                                  Unit = "grams"),
    oreo_pre_w_o_plate = list( Description = 'Pre-EAH weight of oreos without plate',
                               Unit = "grams"),
    oreo_pre_w_plate = list( Description = 'Pre-EAH weight of oreos with plate',
                             Unit = "grams"),
    popcorn_pre_w_o_plate = list( Description = 'Pre-EAH weight of popcorn without plate',
                                  Unit = "grams"),
    popcorn_pre_w_plate = list( Description = 'Pre-EAH weight of popcorn with plate',
                                Unit = "grams"),
    fritos_pre_w_o_plate = list( Description = 'Pre-EAH weight of Fritos without plate',
                                    Unit = "grams"),
    fritos_pre_w_plate = list( Description = 'Pre-EAH weight of Fritos with plate',
                                  Unit = "grams"),
    pretzel_pre_w_o_plate = list( Description = 'Pre-EAH weight of pretzels without plate',
                                  Unit = "grams"),
    pretzel_pre_w_plate = list( Description = 'Pre-EAH weight of pretzels with plate',
                                Unit = "grams"),
    skittles_pre_w_o_plate = list( Description = 'Pre-EAH weight of Skilles without plate',
                                  Unit = "grams"),
    skittles_pre_w_plate = list( Description = 'Pre-EAH weight of brownies with plate',
                                Unit = "grams"),
    brownie_pre_w_o_plate = list( Description = 'Pre-EAH weight of brownies without plate',
                                  Unit = "grams"),
    brownie_pre_w_plate = list( Description = 'Pre-EAH weight of brownies with plate',
                                Unit = "grams"),
    ice_cream_pre_w_o_plate = list( Description = 'Pre-EAH weight of Ice cream without plate',
                                    Unit = "grams"),
    ice_cream_pre_w_plate = list( Description = 'Pre-EAH weight of Ice cream with plate',
                                  Unit = "grams"),
    water_eah_pre_w_o_plate = list( Description = 'Pre-EAH weight of water without container',
                                    Unit = "grams"),
    water_eah_pre_w_plate = list( Description = 'Pre-EAH weight of water with container',
                                  Unit = "grams"),
    hershy_post_w_plate = list( Description = 'Post-EAH weight of Hersheys kiss with plate',
                              Unit = "grams"),
    starburst_post_w_plate = list( Description = 'Post-EAH weight of starbursts with plate',
                                   Unit = "grams"),
    oreo_post_w_plate = list( Description = 'Post-EAH weight of oreos with plate',
                              Unit = "grams"),
    popcorn_post_w_plate = list( Description = 'Post-EAH weight of popcorn with plate',
                                 Unit = "grams"),
    fritos_post_w_plate = list( Description = 'Post-EAH weight of Fritos with plate',
                                   Unit = "grams"),
    pretzel_post_w_plate = list( Description = 'Post-EAH weight of pretzels with plate',
                                 Unit = "grams"),
    skittles_post_w_plate = list( Description = 'Post-EAH weight of Skittles with plate',
                                 Unit = "grams"),
    brownie_post_w_plate = list( Description = 'Post-EAH weight of brownies with plate',
                                 Unit = "grams"),
    ice_cream_post_w_plate = list( Description = 'Post-EAH weight of Ice cream with plate',
                                   Unit = "grams"),
    water_eah_post_w_plate = list( Description = 'Post-EAH weight of water with container',
                                   Unit = "grams"),
    preweight_notes = list( Description = 'Notes about meal pre-weights'),
    mac_post_notes = list( Description = 'Notes about macaroni and cheese'),
    cknug_post_notes = list( Description = 'Notes about chicken nugges'),
    grapes_post_notes = list( Description = 'Notes about grapes'),
    carrots_post_notes = list( Description = 'Notes about carrots'),
    ketchup_post_notes = list( Description = 'Notes about ketchup'),
    water_post_notes = list( Description = 'Notes about water'),
    postweight_notes = list( Description = 'Notes about meal post-weights'),
    pretzel_notes = list( Description = 'Notes about pretzel'),
    eah_preweight_notes = list( Description = 'Notes about EAH pre-weights'),
    eah_taste_prep_notes = list( Description = 'Notes about EAH taste sample prep'),
    hershey_post_notes = list( Description = 'Notes about Hershey Kiss'),
    starburst_post_notes = list( Description = 'Notes about Starbursts'),
    oreos_post_notes = list( Description = 'Notes about Oreos'),
    popcorn_post_notes = list( Description = 'Notes about popcorn'),
    fritos_post_notes = list( Description = 'Notes about Fritos'),
    pretzel_post_notes = list( Description = 'Notes about pretzels'),
    skittles_post_notes = list( Description = 'Notes about Skittles'),
    brownie_post_notes = list( Description = 'Notes about brownies'),
    icecream_post_notes = list( Description = 'Notes about ice-cream'),
    eah_postweight_notes = list( Description = 'Notes about EAH post-weights')
  )

  # convert formatting to JSON
  intake_de_json <- RJSONIO::toJSON(intake_de_list, pretty = TRUE)

  # double check
  if (isFALSE(RJSONIO::isValidJSON(intake_de_json, asText = TRUE))){
    print('Double-entered intake JSON file may be invalid')
  }

  return(intake_de_json)

}
