#' json_cshq: Generates a json file for the Children's Sleep Habits Questionnaire
#'
#' This function generates a json file for the scored Children's Sleep Habits Questionnaire and raw participant responses. This function provides accurate json files ONLY if data is processed using score_cshq function in dataprepr and is only accurate for data collected in Study BRAKE.
#'
#' @return A json file documenting the raw inputs and scored values for the Children's Sleep Habits Questionnaire
#'
#'
#' @export

json_cshq <- function() {
  
  cshq_list <- list(
    'MeasurementToolMetadata' = list(
      Description = 'Children\'s Sleep Habits Questionnaire.',
      Reference = 'Owens, J. A., Spirito, A., & McGuinn, M. (2000). The Children’s Sleep Habits Questionnaire (CSHQ): Psychometric Properties of A Survey Instrument for School-Aged Children. SLEEP, 23(8), 1043–1052', 
      TermURL = 'https://pubmed.ncbi.nlm.nih.gov/11145319/'),
    participant_id = list( Description = 'participant id number'),
    cshq_bed_time = list( Description = 'Child\'s bedtime (Please answer with a 24 hour clock):'),
    cshq_wake_time = list( Description = 'Child\'s usual wake time (Please answer with a 24 hour clock):'),
    cshq_sleep_total_hours = list( Description = 'Child\'s usual amount of sleep each night (no naps): _ hours'),
    cshq_sleep_total_mins = list( Description = 'Child\'s usual amount of sleep each night (no naps): _ minutes'),
    cshq_nap_hours = list( Description = 'Child\'s usual amount of sleep each day (naps): _ hours'),
    cshq_nap_mins = list( Description = 'Child\'s usual amount of sleep each day (naps): _ minutes'),
    cshq_1 = list( Description = 'Child goes to bed at the same time at night', 
                 Levels = list ('1' = 'Usually (5-7 day/wk)',
                                '2' = 'Sometimes (2-4 days/wk)',
                                '3' = 'Rarely (0-1 days/wk)')),
    cshq_2 = list( Description = 'Child falls asleep alone in own bed',
                   Levels = list ('1' = 'Usually (5-7 day/wk)',
                                  '2' = 'Sometimes (2-4 days/wk)',
                                  '3' = 'Rarely (0-1 days/wk)')),
    cshq_3 = list( Description = 'Child falls asleep within 20 minutes after going to bed',
                   Levels = list ('1' = 'Usually (5-7 day/wk)',
                                  '2' = 'Sometimes (2-4 days/wk)',
                                  '3' = 'Rarely (0-1 days/wk)')),
    cshq_4 = list( Description = 'Child sleeps the right amount',
                   Levels = list ('1' = 'Usually (5-7 day/wk)',
                                  '2' = 'Sometimes (2-4 days/wk)',
                                  '3' = 'Rarely (0-1 days/wk)')),
    cshq_5 = list( Description = 'Child sleeps about the same amount each day',
                   Levels = list ('1' = 'Usually (5-7 day/wk)',
                                  '2' = 'Sometimes (2-4 days/wk)',
                                  '3' = 'Rarely (0-1 days/wk)')),
    cshq_6 = list( Description = 'Child wakes up by him/herself',
                   Levels = list ('1' = 'Usually (5-7 day/wk)',
                                  '2' = 'Sometimes (2-4 days/wk)',
                                  '3' = 'Rarely (0-1 days/wk)')),
    cshq_1_prob = list( Description = 'Do you consider this a problem?',
                  Levels = list ('0' = 'No',
                                 '1' = 'Yes')),
    cshq_2_prob = list( Description = 'Do you consider this a problem?',
                        Levels = list ('0' = 'No',
                                       '1' = 'Yes')),
    cshq_3_prob = list( Description = 'Do you consider this a problem?',
                        Levels = list ('0' = 'No',
                                       '1' = 'Yes')),
    cshq_4_prob = list( Description = 'Do you consider this a problem?',
                        Levels = list ('0' = 'No',
                                       '1' = 'Yes')),
    cshq_5_prob = list( Description = 'Do you consider this a problem?',
                        Levels = list ('0' = 'No',
                                       '1' = 'Yes')),
    cshq_6_prob = list( Description = 'Do you consider this a problem?',
                        Levels = list ('0' = 'No',
                                       '1' = 'Yes')),
    cshq_7 = list( Description = 'Has your child appeared very sleepy or fallen asleep during the following: Watching TV',
                  Levels = list ('0' = 'Not Sleepy',
                                 '1' = 'Very Sleepy',
                                 '2' = 'Falls Asleep')),
    cshq_8 = list( Description = 'Has your child appeared very sleepy or fallen asleep during the following: Riding in a car',
                   Levels = list ('0' = 'Not Sleepy',
                                  '1' = 'Very Sleepy',
                                  '2' = 'Falls Asleep')),
    cshq_9 = list( Description = 'Child falls asleep in parent\'s or sibling\'s bed',
                   Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                  '2' = 'Sometimes (2-4 days/wk)',
                                  '3' = 'Usually (5-7 day/wk)')),
    cshq_10 = list( Description = 'Child struggles at bedtime (cries, refuses to stay in bed, etc.)',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_11 = list( Description = 'Child needs parent in the room to fall asleep',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_12 = list( Description = 'Child is afraid of sleeping alone',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_13 = list( Description = 'Child sleeps too little',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_14 = list( Description = 'Child is afraid of sleeping in the dark',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_15 = list( Description = 'Child has trouble sleeping away from home (visiting relatives, vacation',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_16 = list( Description = 'Child moves to someone else\'s bed during the night (parent, sibling, etc.)',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_17 = list( Description = 'Child awakens once during the night',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_18 = list( Description = 'Child awakens more than once during the night',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_18_notes = list( Description = 'Write the number of minutes a night waking usually lasts:'),
    cshq_9_prob = list( Description = 'Do you consider this a problem?',
                        Levels = list ('0' = 'No',
                                       '1' = 'Yes')),
    cshq_10_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_11_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_12_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_13_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_14_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_15_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_16_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_17_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_18_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_19 = list( Description = 'Child talks during sleep',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_20 = list( Description = 'Child is restless and moves a lot during sleep',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_21 = list( Description = 'Child sleepwalks during the night',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_22 = list( Description = 'Child wets the bed at night',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_23 = list( Description = 'Child grind teeth during sleep (your dentist may have told you this)',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_24 = list( Description = 'Child awakens alarmed by a frightening dream',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_25 = list( Description = 'Child snores loudly',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_26 = list( Description = 'Child seems to stop breathing during sleep',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_27 = list( Description = 'Child seems to stop breathing during sleep',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_28 = list( Description = 'Child snorts and/or gasps during sleep',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_29 = list( Description = 'Child wakes up in a negative mood',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_30 = list( Description = 'Adults or siblings wake up child',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_31 = list( Description = 'Child has difficulty getting out of bed in the morning',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_32 = list( Description = 'Child takes a long time to become alert in the morning',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_33 = list( Description = 'Child seems tired in the morning',
                    Levels = list ('1' = 'Rarely (0-1 days/wk)',
                                   '2' = 'Sometimes (2-4 days/wk)',
                                   '3' = 'Usually (5-7 day/wk)')),
    cshq_19_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_20_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_21_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_22_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_23_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_24_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_25_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_26_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_27_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_28_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_29_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_30_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_31_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_32_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_33_prob = list( Description = 'Do you consider this a problem?',
                         Levels = list ('0' = 'No',
                                        '1' = 'Yes')),
    cshq_bedtime_resit = list( Description = 'Betime Resistance.', 
                         Derivative = TRUE),
    cshq_sleep_delay = list( Description = 'Sleep Onset Delay.', 
                      Derivative = TRUE),
    cshq_sleepdur = list( Description = 'Sleep Duration.', 
                           Derivative = TRUE),
    cshq_anxiety = list( Description = 'Sleep Anxiety.', 
                    Derivative = TRUE),
    cshq_nightwake = list( Description = 'Night Wakings.', 
                           Derivative = TRUE),
    cshq_parasomnias = list( Description = 'Parasomnias.', 
                     Derivative = TRUE),
    cshq_dis_breathing = list( Description = 'Sleep Disordered Breathing.', 
                     Derivative = TRUE),
    cshq_daysleepy = list( Description = 'Daytime Sleepiness.', 
                               Derivative = TRUE),
    cshq_total = list( Description = 'Total Score.', 
                               Derivative = TRUE))
  
  # convert formatting to JSON
  cshq_json <- RJSONIO::toJSON(cshq_list, pretty = TRUE)
  
  # double check
  if (isFALSE(RJSONIO::isValidJSON(cshq_json, asText = TRUE))){
    print('cshq JSON file may be invalid')
  }
  
  return(cshq_json)
  
}