#' util_merge_questionnaires: merges data for questionnaires that were repeated at baseline and follow-up
#'
#' This function data for questionnaires that were repeated at baseline and follow-up. The following questionnaires will be merged across visits and returned individually in a list:
#'
#'
#' @param child_v1_data full set of child visit 1 data generated by util_redcap_child_v1
#' @param child_v2_data full set of child visit 2 data generated by util_redcap_child_v4
#' @param child_v3_data full set of child visit 3 data generated by util_redcap_child_v5
#' @param parent_v1_data full set of parent visit 1 data generated by util_redcap_parent_v1
#' @param parent_v2_data full set of parent visit 2 data generated by util_redcap_parent_v2
#' @param parent_v3_data full set of parent visit 3 data generated by util_redcap_parent_v3
#' 
#' @return Will return a list of merged data files:
#'  \itemize{
#'    \item{hfi_all}
#'    \item{loc_all}
#'    \item{sic_all}
#'    \item{household_all}
#'    \item{cebq_all}
#'    \item{cbq_all}
#'    \item{cshq_all}
#'    \item{pstca_all}
#'    \item{audit_all}
#'    \item{pmum_all}
#'    \item{cfpq_all}
#'    \item{rank_all}
#'    \item{class_all}
#'    \item{puberty_all}
#'    \item{updates_all}
#'  }
#'
#' @examples
#'
#' # process data
#' merged_qs_list <- util_merge_questionnaires(child_v1_data, child_v2_data, child_v3_data, parent_v1_data, parent_v2_data, parent_v3_data)
#'
#' @seealso [proc_redcap(), util_redcap_child1(), util_redcap_child2(),util_redcap_child3(), util_redcap_parent_v1(), util_redcap_parent_v2(), util_redcap_parent_v3()]
#'
#' @export
#'


util_merge_questionnaires <- function(child_v1_data, child_v2_data, child_v3_data, parent_v1_data, parent_v2_data, parent_v3_data) {

  hfi_all <- rbind.data.frame(child_v1_data$hfi_data$data$bids_phenotype, parent_v3_data$hfi_data$data$bids_phenotype)

  loc_all <- rbind(data.table::setDT(child_v2_data$loc_data$data), data.table::setDT(child_v3_data$loc_data$data), fill = TRUE)
  loc_all <- as.data.frame(loc_all)

  sic_all <- rbind.data.frame(child_v2_data$sic_data$data$bids_phenotype, child_v3_data$sic_data$data$bids_phenotype)

  household_all <- rbind.data.frame(parent_v1_data$household_data$data, parent_v3_data$household_data$data)
  
  puberty_all <- rbind(data.table::setDT(parent_v1_data$puberty_data$data$bids_phenotype), data.table::setDT(parent_v3_data$puberty_data$data$bids_phenotype), fill = TRUE)
  puberty_all <- as.data.frame(puberty_all)
  
  cfq_all <- rbind.data.frame(parent_v1_data$cfq_data$data$bids_phenotype, parent_v3_data$cfq_data$data$bids_phenotype)

  cshq_all <- rbind.data.frame(parent_v1_data$cshq_data$data$bids_phenotype, parent_v3_data$cshq_data$data$bids_phenotype)

  efcr_all <- rbind.data.frame(parent_v1_data$efcr_data$data$bids_phenotype, parent_v3_data$efcr_data$data$bids_phenotype)

  ffq_all <- rbind.data.frame(parent_v1_data$ffq_data$data$bids_phenotype, parent_v3_data$ffq_data$data$bids_phenotype)
  
  bes_all <- rbind.data.frame(parent_v2_data$bes_data$data$bids_phenotype, parent_v3_data$bes_data$data$bids_phenotype)
  
  hfe_all <- rbind.data.frame(parent_v2_data$hfe_data$data$bids_phenotype, parent_v3_data$hfe_data$data$bids_phenotype)
  
  pwlb_all <- rbind.data.frame(parent_v2_data$pwlb_data$data$bids_phenotype, parent_v3_data$pwlb_data$data$bids_phenotype)
  
  # return data
  return(list(hfi_all = list(data = hfi_all, meta = child_v1_data$hfi_data$meta),
              loc_all = list(data = loc_all, meta = child_v3_data$loc_data$meta),
              sic_all = list(data = sic_all, meta = child_v2_data$sic_data$meta),
              household_all = list(data = household_all, meta = parent_v1_data$household_data$meta),
              puberty_all = list(data = puberty_all, meta = parent_v1_data$puberty_data$meta),
              cfq_all = list(data = cshq_all, meta = parent_v1_data$cfq_data$meta),
              cshq_all = list(data = cshq_all, meta = parent_v2_data$cshq_data$meta),
              efcr_all = list(data = efcr_all, meta = parent_v1_data$efcr_data$meta),
              ffq_all = list(data = ffq_all, meta = parent_v1_data$ffq_data$meta),
              bes_all = list(data = bes_all, meta = parent_v2_data$bes_data$meta),
              hfe_all = list(data = hfe_all, meta = parent_v2_data$hfe_data$meta),
              pwlb_all = list(data = pwlb_all, meta = parent_v2_data$pwlb_data$meta))
         )

}
