#' util_redcap_child1: Organize child visit 1 data from REDCap
#'
#' This function organizes REDCap data from REDCap visit data, event child_visit_1_arm_1
#'
#' @param data data from REDCap event child_visit_1_arm_1
#' @param data_data date data generated by util_redcap_dates.R
#'
#' @return Will return a list including:
#' \itemize{
#'  \item{clean raw child visit 1 datasets}
#'  \item{meta-data formated as json for each dataset}
#'  }
#'
#'  Returned data includes:
#'  \itemize{
#'    \item{fnirs_cap}
#'    \item{anthro_data}
#'    \item{shapegame_info}
#'    \item{fnirs_tasks_info}
#'    \item{meal_info}
#'    \item{toolbox_info}
#'    \item{sleep_wk_data}
#'    \item{hfi_data}
#'  }
#' @examples
#'
#' # process REDCap data
#' child_visit1_list <- util_redcap_child1(data)
#'
#' \dontrun{
#' }
#'
#' @seealso [proc_redcap(), util_redcap_dates()]
#'
#' @export
#' 
#' 

util_redcap_child1 <- function(data, date_data) {
  
  #### Set up/initial checks #####
  
  # check that audit_data exist and is a data.frame
  data_arg <- methods::hasArg(data)
  
  if (isTRUE(data_arg)) {
    if (!is.data.frame(data)) {
      stop('data must be a data.frame')
    }
  } else if (isFALSE(data_arg)) {
    stop('child data for REDCap event child_visit_1_arm_1 must be entered as a data.frame')
  }
  
  date_data_arg <- methods::hasArg(date_data)
  
  if (isTRUE(date_data_arg)) {
    if (!is.data.frame(date_data)) {
      stop('date_data must be a data.frame')
    }
  } else if (isFALSE(date_data_arg)) {
    stop('date_data from util_redcap_dates() must be entered as a data.frame')
  }
  
  # update name of participant ID column
  names(data)[names(data) == 'record_id'] <- 'participant_id'
  
  # add session column
  data['session_id'] <- 'ses-baseline'
  
  # add visit number
  data['visit_protocol'] <- 1
  
  # merge with date_data
  data <- merge(data, date_data[c('participant_id', 'v1_date')], by = 'participant_id', all.x = TRUE)
  names(data)[names(data) == 'v1_date'] <- 'visit_date'
  data['visit_date'] <- lubridate::as_date(data[['visit_date']])
  
  
  ## fNIRS fit ####
  fnirs_cap <- data[grepl('_id|^visit|capfit', names(data))]
  
  #reduce columns and reorder
  fnirs_cap <- fnirs_cap[!grepl('hfi|mid', names(fnirs_cap))]
  
  fnirs_cap <- fnirs_cap[c('participant_id','session_id', 'visit_date', 'visit_protocol', names(fnirs_cap)[grepl('capfit', names(fnirs_cap))])]
  
  #update names
  names(fnirs_cap) <- gsub('capfit', 'fnirs', names(fnirs_cap))
  names(fnirs_cap)[names(fnirs_cap) == 'fnirs_frontback'] <- 'fnirs_frontback_cm'
  names(fnirs_cap)[names(fnirs_cap) == 'fnirs_ears'] <- 'fnirs_ears_cm'
  names(fnirs_cap)[names(fnirs_cap) == 'fnirs_circ'] <- 'fnirs_circ_cm'
  
  fnirs_cap_json <- json_fnirscap()
  
  ## anthro ####
  child_anthro <- data[grepl('_id|^visit|weight|height|notes|relationship', names(data))]
  
  #reduce columns and reorder
  child_anthro <- child_anthro[!grepl('_ft|_in|_lbs|meal|eah|pre|post|shapegame|food|capfit|toolbox|status', names(child_anthro))]
  
  child_anthro <- child_anthro[c('participant_id', 'session_id', 'visit_protocol', 'visit_date', 'relationship', names(child_anthro)[grepl('c_', names(child_anthro))], names(child_anthro)[grepl('p_', names(child_anthro))], 'heightweight_notes')]
  
  #update names
  names(child_anthro) <- gsub('avg', 'mean', names(child_anthro))
  names(child_anthro) <- gsub('c_', '', names(child_anthro))
  names(child_anthro) <- gsub('p_', 'parent1_', names(child_anthro))
  names(child_anthro)[names(child_anthro) == 'relationship'] <- 'parent1_relationship'
  
  child_anthro_json <- json_child_anthro()
  
  ## Shape Game information ####
  shapegame_info <- data[grepl('_id|^visit|shape', names(data))]
  
  shapegame_info <- shapegame_info[!grepl('ffcheck|prize_check', names(shapegame_info))]
  
  # update names
  names(shapegame_info) <- gsub('_snack_hungry', '_postsnack_hungry', names(shapegame_info))
  names(shapegame_info) <- gsub('^shapegame_snack', 'pre_shapegame_snack', names(shapegame_info))
  
  names(shapegame_info)[names(shapegame_info) == 'pre_shapegame_snack_hungry'] <- 'pre_shapegame_postsnack_hungry'
  names(shapegame_info)[names(shapegame_info) == 'shapegame_check'] <- 'shapegame_complete'
  names(shapegame_info)[names(shapegame_info) == 'shapegame_eye_check'] <- 'shapegame_eyetrack_good'
  names(shapegame_info)[names(shapegame_info) == 'shape_game_snack'] <- 'shapegame_candy'
  
  shapegame_info <- shapegame_info[c('participant_id', 'session_id', 'visit_protocol', 'visit_date', names(shapegame_info)[grepl('pre', names(shapegame_info))], names(shapegame_info)[grepl('^shape', names(shapegame_info))])]
  
  shapegame_info_json <- json_shapegame_info()
  
  ## fNIRS task information ####
  fnirs_info <- data[grepl('_id|^visit|pre_fnirs|rating|choice', names(data))]
  
  fnirs_info <- fnirs_info[!grepl('ffcheck', names(fnirs_info))]
  
  # update names
  names(fnirs_info) <- gsub('_snack_hungry', '_postsnack_hungry', names(fnirs_info))
  names(fnirs_info) <- gsub('_check', '_complete', names(fnirs_info))
  
  names(fnirs_info)[names(fnirs_info) == 'foodchoice_eye_complete'] <- 'foodchoice_eye_good'
  
  fnirs_info <- fnirs_info[c('participant_id', 'session_id', 'visit_protocol', 'visit_date', names(fnirs_info)[grepl('pre', names(fnirs_info))], names(fnirs_info)[grepl('rating', names(fnirs_info))], names(fnirs_info)[grepl('choice', names(fnirs_info))])]
  
  fnirs_info_json <- json_fnirstasks_info()
  
  ## meal information - NOTE: meal intake and freddy data are double entered ####
  meal_info <- data[grepl('_id|^visit|ff|vas|test_meal|want|wan|eah', names(data))]
  
  meal_info <- meal_info[!grepl('ffcheck|fnirs|ff_check|min_check|record|prac|freddy_check', names(meal_info))]
  
  # update names
  names(meal_info) <- gsub('wan_', 'want_', names(meal_info))
  names(meal_info) <- gsub('ff', 'fullness', names(meal_info))
  names(meal_info) <- gsub('freddy', 'fullness', names(meal_info))
  
  names(meal_info)[names(meal_info) == 'vas_eah_want_notes'] <- 'liking_want_eah_notes'
  names(meal_info)[names(meal_info) == 'eah_game_wanting_notes'] <- 'game_want_eah_notes'
  
  names(meal_info) <- gsub('vas', 'liking', names(meal_info))
  
  names(meal_info)[names(meal_info) == 'want_cornchip'] <- 'want_corn_chip'
  names(meal_info)[names(meal_info) == 'want_cookie'] <- 'want_oreo'
  
  meal_info <- meal_info[c('participant_id', 'session_id', 'visit_protocol', 'visit_date', names(meal_info)[grepl('fullness', names(meal_info))], names(meal_info)[grepl('^liking', names(meal_info))], names(meal_info)[grepl('^want|^game', names(meal_info))], names(meal_info)[grepl('test_meal', names(meal_info))], names(meal_info)[grepl('^eah', names(meal_info))])]
  
  names(meal_info) <- gsub('^want_', 'eah_wanting_', names(meal_info))
  
  
  meal_info_json <- json_meal_info_v1()
  
  ## Toolbox info ####
  toolbox_data <- data[grepl('_id|^visit|toolbox', names(data))]
  
  ## Sleep Week data ####
  sleep_data <- data[grepl('_id|^visit|_mon|_tu|_wed|_th|_fri|_sat|_sun', names(data))]
  
  sleep_data <- sleep_data[!grepl('hfi', names(sleep_data))]
  
  # score data
  library(lubridate)
  sleep_wk_scored <- dataprepr::score_sleeplog(sleep_data, id = 'participant_id', summer_start = '2023-06-06', summer_end = '2023-08-23')
  
  child_sleep_json <- json_sleeplog()
  
  ## HFI data ####
  hfi_data <- data[grepl('_id|^visit|hfi', names(data))] 
  
  hfi_data <- hfi_data[!grepl('qcheck', names(hfi_data))]
  
  hfi_data <- hfi_data[c('participant_id', 'session_id', 'visit_date', 'visit_protocol', names(hfi_data)[!grepl('_id|^visit', names(hfi_data))])]
  
  # update names
  names(hfi_data) <- gsub('___', '', names(hfi_data))
  names(hfi_data) <- gsub('visible', 'accessible', names(hfi_data))
  
  hfi_scored <- dataprepr::score_hfi(hfi_data, id = 'participant_id', base_zero = TRUE)
  hfi_json <- json_hfi()
  
  return(list(
    fnirs_cap = list(data = fnirs_cap, meta = fnirs_cap_json),
    anthro_data = list(data = child_anthro, meta = child_anthro_json),
    shapegame_info = list(data = shapegame_info, meta = shapegame_info_json),
    fnirs_tasks_info = list(data = fnirs_info, meta = fnirs_info_json),
    meal_info = list(data = meal_info, meta = meal_info_json), 
    toolbox_info = toolbox_data,
    sleep_wk_data = list(data = sleep_wk_scored, meta = child_sleep_json),
    hfi_data = list(data = hfi_scored, meta = hfi_json)))
}

