#' util_merged_intake: merges and formats all data related to meals and EAH
#'
#' This function merges all data related to meals and EAH and calculates intake values
#'
#' @param child_v1_data full set of child_v1_data generated by util_redcap_child1
#' @param child_v3_data full set of child_v1_data generated by util_redcap_child1
#' @param proc_de_data full set of processed double-entry data generated by util_redcap_de
#' @param tastetest_data (optional - needed only for intake data) processed Taste-Test data from fNIRS task so can add liking data to intake data
#' 
#' @examples
#'
#' # process data
#' merged_intake <- util_merged_intake(child_v1_data, child_v3_data, proc_de_data, tastetest_data)
#'
#' @seealso [proc_redcap(), util_redcap_child1(), util_redcap_child3(), proc_task_derivs(), util_group_tastetest(), util_redcap_de(), util_calc_intake()]
#'
#' @export
#'


util_merged_intake <- function(child_v1_data, child_v3_data, proc_de_data, tastetest_data) {

  ## meal info ####
  # meal information for v1 (fullness notes, liking, wanting, notes)
  v1_meal_info <- child_v1_data$meal_info$data
  
  # meal information for v1 (fullness notes, liking, wanting, notes)
  v3_meal_info <- child_v3_data$meal_info$data 

  # get v3 liking data and merge with intake data
  v3_liking <- tastetest_data[c('participant_id', 'pre_cknug_mean_like', 'pre_mac_mean_like', 'pre_grape_mean_like', 'pre_carrot_like')]
  names(v3_liking) <- c('participant_id', 'liking_cknug', 'liking_mac', 'liking_grapes', 'liking_carrot')
  
  v3_meal_info <- merge(v3_meal_info, v3_liking, by = 'participant_id', all.x = TRUE)
  

  meal_info_all <- rbind(data.table::setDT(v1_meal_info), data.table::setDT(v3_meal_info), fill=TRUE)
  meal_info_all <- as.data.frame(meal_info_all)

  ## fullness merge ####
  
  # v1 fullness
  v1_fullness <- proc_de_data$fullness_baseline_data$data
  v1_fullness <- v1_fullness[!grepl('fnirs|shape|v2', names(v1_fullness))]
  names(v1_fullness)[names(v1_fullness) == 'v1_date'] <- 'visit_date'
  
  v3_fullness <- proc_de_data$fullness_followup_data$data
  
  names(v3_fullness)[names(v3_fullness) == 'fullness_premeal_prefnirs'] <- 'fullness_preliking_meal'
  v3_fullness <- v3_fullness[!grepl('fnirs', names(v3_fullness))]
  
  
  fullness_all <- rbind(data.table::setDT(v1_fullness), data.table::setDT(v3_fullness), fill=TRUE)
  fullness_all <- as.data.frame(fullness_all)
  
  ## merge all with intake ####
  intake_de_data <- proc_de_data$intake_data$data

  intake_data <- merge(meal_info_all, fullness_all[!grepl('visit_date', names(fullness_all))], by = c('participant_id', 'session_id'), all = TRUE)
  intake_data <- merge(intake_data, intake_de_data[!grepl('visit_date', names(intake_de_data))], by = c('participant_id', 'session_id'), all = TRUE)
  
  #update names
  names(intake_data) <- gsub('fullness_preliking_meal', 'pre_liking_fullness', names(intake_data))
  names(intake_data) <- gsub('fullness_premeal', 'pre_meal_fullness', names(intake_data))
  names(intake_data) <- gsub('fullness_postmeal', 'post_meal_fullness', names(intake_data))
  names(intake_data) <- gsub('fullness_preliking_eah', 'pre_wanting_liking_fullness', names(intake_data))
  names(intake_data) <- gsub('fullness_pre_eah', 'pre_eah_fullness', names(intake_data))
  names(intake_data) <- gsub('fullness_post_eah', 'post_eah_fullness', names(intake_data))
  
  names(intake_data) <- gsub('liking_cornchip', 'liking_fritos', names(intake_data))
  names(intake_data) <- gsub('liking_want_eah_notes', 'want_liking_eah_notes', names(intake_data))
  names(intake_data) <- gsub('eah_wanting_corn_chip', 'eah_wanting_fritos', names(intake_data))
 
  intake_data <- intake_data[c('participant_id', 'session_id', 'visit_protocol', 'visit_date', names(intake_data)[grepl('pre_liking.+time$|pre_liking.+ness$', names(intake_data))], names(intake_data)[grepl('^liking', names(intake_data))], names(intake_data)[grepl('pre_meal.+time$|pre_meal.+ness$', names(intake_data))], names(intake_data)[grepl('meal_start|meal_end|meal_dur|meal_book', names(intake_data))], names(intake_data)[grepl('^mac.+plate$|^cknug.+plate$|^carrot.+plate$|^grapes.+plate$|^water.+plate$|^ketchup.+plate$', names(intake_data))], names(intake_data)[grepl('post_meal.+time$|post_meal.+ness$', names(intake_data))], names(intake_data)[grepl('pre_wanting.+time$|pre_wanting.+ness$', names(intake_data))], names(intake_data)[grepl('eah_wanting', names(intake_data))], names(intake_data)[grepl('pre_eah.+time$|pre_eah.+ness$', names(intake_data))], names(intake_data)[grepl('eah_start|eah_end', names(intake_data))], names(intake_data)[grepl('^hershey.+plate$|^starburst.+plate$|^oreos.+plate$|^popcorn.+plate$|^fritos.+plate$|^pretzel.+plate$|^skittles.+plate$|^brownie.+plate$|^icecream.+plate$|^eah_water.+plate', names(intake_data))], names(intake_data)[grepl('post_eah.+time$|post_eah.+ness$', names(intake_data))], names(intake_data)[grepl('_notes$', names(intake_data))])]

  #### calc intake ####

  intake_all <- util_calc_intake(intake_data)
  
  #re-order
  intake_all <- intake_all[c('participant_id', 'session_id', 'visit_protocol', 'visit_date', names(intake_all)[grepl('pre_liking.+time$|pre_liking.+ness$', names(intake_all))], names(intake_all)[grepl('^liking', names(intake_all))], names(intake_all)[grepl('pre_meal.+time$|pre_meal.+ness$', names(intake_all))], names(intake_all)[grepl('meal_start|meal_end|meal_dur|meal_book', names(intake_all))], names(intake_all)[grepl('^mac.+plate$|^cknug.+plate$|^carrot.+plate$|^grapes.+plate$|^water.+plate$|^ketchup.+plate$|^water.+plate$', names(intake_all))], names(intake_all)[grepl('^mac.+ed$|^cknug.+ed$|^carrot.+ed$|^grapes.+ed$|^water.+ed$|^ketchup.+ed$|meal.+ed$|meal.+water$', names(intake_all))], names(intake_all)[grepl('post_meal.+time$|post_meal.+ness$', names(intake_all))], names(intake_all)[grepl('pre_wanting.+time$|pre_wanting.+ness$', names(intake_all))], names(intake_all)[grepl('eah_wanting', names(intake_all))], names(intake_all)[grepl('pre_eah.+time$|pre_eah.+ness$', names(intake_all))], names(intake_all)[grepl('eah_start|eah_end', names(intake_all))], names(intake_all)[grepl('^hershey.+plate$|^starburst.+plate$|^oreos.+plate$|^popcorn.+plate$|^fritos.+plate$|^pretzel.+plate$|^skittles.+plate$|^brownie.+plate$|^icecream.+plate$|^eah_water.+plate$', names(intake_all))], names(intake_all)[grepl('^hershey.+ed$|^starburst.+ed$|^oreos.+ed$|^popcorn.+ed$|^fritos.+ed$|^pretzel.+ed$|^skittles.+ed$|^brownie.+ed$|^icecream.+ed$|^eah_water.+ed$|eah.+ed$|eah.+water$|total.+ed', names(intake_all))], names(intake_all)[grepl('post_eah.+time$|post_eah.+ness$', names(intake_all))], names(intake_all)[grepl('_notes$', names(intake_all))])]
  
  intake_all_json <- json_intake()
  

  # return data
  return(intake_all = list(data = intake_all, meta = intake_all_json))

}
